= 응용 프로그램 역할
:allow-uri-read: 




== 응용 프로그램 역할

응용 프로그램 역할은 Active IQ 디지털 어드바이저(디지털 어드바이저)와 같은 BlueXP  응용 프로그램에 대한 액세스를 제공합니다.



=== 스토리지 관리자

사용자가 BlueXP 에서 소프트웨어 업데이트, BlueXP  작업 환경 생성 및 삭제와 같은 스토리지 관리 기능을 수행할 수 있습니다.

권한:: BlueXP  캔버스를 볼 수 있습니다. BlueXP  커넥터를 생성 및 관리할 수 있습니다. 다음을 포함하여 BlueXP 의 스토리지 상태 및 거버넌스 기능에 대한 읽기/쓰기 액세스가 있습니다.
+
--
* 디지털 자문업체
* 운영 복원력
* 소프트웨어 업데이트(소프트웨어 업데이트 수행 가능)
* 디지털 지갑
* 경제적인 효율성
* Sustainability 대시보드
* 경고


--




=== 스토리지 뷰어

BlueXP 의 상태 및 거버넌스 기능에 대한 읽기 전용 액세스를 제공합니다. 이 역할은 일반적으로 조직의 스토리지 리소스 상태를 모니터링하는 역할을 담당하는 사용자에게 할당됩니다. 이 역할을 가진 사용자는 BlueXP  내에서 여러 애플리케이션을 확인하여 소프트웨어 업데이트 계획과 효율성 계획을 수립하고 전반적인 스토리지 상태를 볼 수 있습니다.

권한:: 다음을 포함하여 BlueXP 의 스토리지 상태 및 거버넌스 기능에 대한 읽기 전용 액세스 권한이 있습니다.
+
--
* 디지털 자문업체
* 운영 복원력
* 소프트웨어 업데이트(업그레이드 계획 다운로드 가능)
* 디지털 지갑
* 경제적인 효율성
* Sustainability 대시보드
* 경고


--


작업의 예: 예를 들어 자원 계층 구조 내에 포함된 각 프로젝트(작업 환경)를 나타내는 7개의 프로젝트가 있는 경우 세 프로젝트에 대해 스토리지 관리자 역할을 한 다음 나머지 프로젝트에 대해 다른 구성원을 스토리지 관리자로 할당할 수 있습니다. 한 사용자에게 전체 조직의 스토리지 관리자 역할을 할당할 수도 있습니다. 조직의 필요에 따라 구성원 역할을 관리할 수 있습니다.
