---
sidebar: sidebar 
permalink: concept-overview.html 
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers 
summary: NetApp BlueXP는 사내 및 클라우드 환경 전반에서 데이터를 구축, 보호, 관리할 수 있는 단일 제어 계층을 제공합니다. BlueXP SaaS 플랫폼에는 스토리지 관리, 데이터 이동성, 데이터 보호, 데이터 분석 및 제어 기능을 제공하는 스토리지 및 데이터 서비스가 포함되어 있습니다. 관리 기능은 웹 기반 콘솔 및 API를 통해 제공됩니다. 
---
= BlueXP에 대해 자세히 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP는 사내 및 클라우드 환경 전반에서 데이터를 구축, 보호, 관리할 수 있는 단일 제어 계층을 제공합니다. BlueXP SaaS 플랫폼에는 스토리지 관리, 데이터 이동성, 데이터 보호, 데이터 분석 및 제어 기능을 제공하는 스토리지 및 데이터 서비스가 포함되어 있습니다. 관리 기능은 웹 기반 콘솔 및 API를 통해 제공됩니다.



== 피처

BlueXP 플랫폼은 스토리지, 이동성, 보호, 분석 및 제어라는 네 가지 주요 데이터 관리 기능을 제공합니다.

스토리지:: AWS, Azure, Google Cloud 또는 온프레미스에 상관없이 스토리지를 검색, 구축, 관리할 수 있습니다.
+
--
* 설정 및 사용 https://bluexp.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] 클라우드 전반에서 효율적인 멀티 프로토콜 데이터 관리
* 클라우드 파일 스토리지 서비스 설정 및 사용:
+
** https://bluexp.netapp.com/azure-netapp-files["Azure NetApp Files"^]
** https://bluexp.netapp.com/fsx-for-ontap["ONTAP용 Amazon FSx"^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp["Google Cloud용 Cloud Volumes Service"^]


* 검색 및 관리 https://bluexp.netapp.com/netapp-on-premises["높지 않습니다"^]:
+
** E-Series 시스템
** ONTAP 클러스터
** StorageGRID 시스템


* 데이터 오케스트레이션 및 보호 https://bluexp.netapp.com/solutions/kubernetes["Kubernetes 영구 데이터"^]


--
이동성:: 데이터를 동기화, 복사, 계층화 및 캐싱하여 필요한 위치로 데이터를 이동합니다.
+
--
* https://bluexp.netapp.com/cloud-sync-service["복사 및 동기화"^]
* https://bluexp.netapp.com/global-file-cache["에지 캐싱"^]
* https://bluexp.netapp.com/cloud-tiering["계층화"^]


--
보호:: 자동화된 보호 메커니즘을 사용하여 데이터 손실, 계획되지 않은 운영 중단, 랜섬웨어 및 기타 사이버 위협으로부터 데이터를 보호합니다.
+
--
* https://bluexp.netapp.com/cloud-backup["백업 및 복구"^]
* https://bluexp.netapp.com/replication["복제"^]


--
분석 및 제어:: 툴을 사용하여 데이터 스토리지 및 인프라를 모니터링, 매핑 및 최적화할 수 있습니다.
+
--
* https://bluexp.netapp.com/netapp-cloud-data-sense["분류"^]
* https://bluexp.netapp.com/digital-advisor["디지털 자문업체"^]
* https://bluexp.netapp.com/ransomware-protection["랜섬웨어 보호"^]


--


https://bluexp.netapp.com/["BlueXP를 사용하여 조직에 도움을 주는 방법에 대해 자세히 알아보십시오"^]



== 지원되는 클라우드 공급자

BlueXP를 사용하면 Amazon Web Services, Microsoft Azure 및 Google Cloud에서 클라우드 스토리지를 관리하고 클라우드 서비스를 사용할 수 있습니다.



== 비용

BlueXP의 가격은 사용할 서비스에 따라 다릅니다. https://bluexp.netapp.com/pricing["BlueXP 가격에 대해 알아보십시오"^]



== BlueXP의 작동 방식

BlueXP에는 SaaS 계층을 통해 제공되는 웹 기반 콘솔, 멀티 테넌시를 제공하는 계정, Cloud Volumes ONTAP 및 기타 클라우드 서비스를 관리하는 커넥터가 포함되어 있습니다.



=== 서비스형 소프트웨어

BlueXP는 을 통해 액세스할 수 있습니다 https://console.bluexp.netapp.com["웹 기반 콘솔"^] API를 사용해 보십시오. 이 SaaS 환경을 통해 최신 기능이 릴리스될 때 자동으로 액세스할 수 있으며 BlueXP 계정과 커넥터 간에 쉽게 전환할 수 있습니다.



=== BlueXP 계정

BlueXP에 처음 로그인하면 _BlueXP 계정 _ 을(를) 생성하라는 메시지가 나타납니다. 이 계정은 다중 테넌시를 제공하며 사용자가 isolated_worksaces_에서 사용자 및 리소스를 구성할 수 있도록 합니다.

link:concept-netapp-accounts.html["어카운트에 대해 자세히 알아보십시오"].



=== 커넥터

BlueXP를 시작하기 위해 커넥터가 필요하지 않지만 모든 BlueXP 기능 및 서비스를 잠금 해제하려면 커넥터를 만들어야 합니다. Connector를 사용하면 사내 환경과 클라우드 환경 전반에서 리소스와 프로세스를 관리할 수 있습니다. Cloud Volumes ONTAP 및 기타 데이터 서비스를 사용해야 합니다.

link:concept-connectors.html["커넥터에 대해 자세히 알아보십시오"].



=== 제한된 모드 및 비공개 모드

BlueXP는 보안 및 연결 제한이 있는 환경에서도 지원됩니다. _restricted mode_or_private mode_를 사용하여 BlueXP SaaS 계층에 대한 아웃바운드 연결을 제한할 수 있습니다.

link:concept-modes.html["BlueXP 배포 모드에 대해 자세히 알아보십시오"].



== SOC 2 Type 2 인증

독립적인 공인회계사 및 서비스 감사원이 BlueXP를 조사하여 해당 신뢰 서비스 기준에 따라 SOC 2 Type 2 보고서를 획득하였다는 것을 확인했습니다.

https://www.netapp.com/company/trust-center/compliance/soc-2/["NetApp의 SOC 2 보고서 보기"^]
