---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Connector는 클라우드 네트워크 또는 사내 네트워크에서 실행되는 NetApp 소프트웨어입니다. 데이터 인프라를 관리하기 위해 BlueXP에서 수행해야 하는 작업을 실행합니다. Connector는 수행해야 하는 작업에 대해 BlueXP SaaS 레이어를 지속적으로 폴링합니다. BlueXP를 시작하기 위해 커넥터가 필요하지 않지만 모든 BlueXP 기능 및 서비스를 잠금 해제하려면 커넥터를 만들어야 합니다. 
---
= BlueXP  커넥터에 대해 알아봅니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A_Connector _ 는 클라우드 네트워크 또는 사내 네트워크에서 실행되는 NetApp 소프트웨어입니다. BlueXP 서비스를 사용자의 스토리지 환경에 연결하는 데 사용됩니다.



== 커넥터 없이 수행할 수 있는 작업

BlueXP를 시작하기 위해 커넥터가 필요하지 않습니다. Connector를 만들지 않고도 BlueXP 내에서 여러 기능 및 서비스를 사용할 수 있습니다.

커넥터 없이 다음 BlueXP 기능 및 서비스를 사용할 수 있습니다.

* NetApp ONTAP용 Amazon FSx
+
일부 작업에는 커넥터 또는 BlueXP  워크로드 팩토리 링크가 필요합니다. https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["커넥터 또는 링크가 필요한 작업에 대해 알아봅니다"^]

* 자동화 카탈로그
* Azure NetApp Files
+
Azure NetApp Files를 설정하고 관리하는 데 커넥터가 필요하지 않지만 Azure NetApp Files 데이터를 스캔하기 위해 BlueXP 분류를 사용하려면 커넥터가 필요합니다.

* Google Cloud용 Cloud Volumes Service
* 복사 및 동기화
* 디지털 자문업체
* 디지털 지갑(라이센스만, 구독 모니터링에는 커넥터가 필요함)
+
거의 모든 경우 커넥터 없이 디지털 지갑에 라이센스를 추가할 수 있습니다.

+
디지털 지갑에 라이센스를 추가하는 데 Connector가 필요한 유일한 시간은 Cloud Volumes ONTAP_node-based_licenses입니다. 이 경우 Cloud Volumes ONTAP 시스템에 설치된 라이센스에서 데이터를 가져왔기 때문에 커넥터가 필요합니다.

* 사내 ONTAP 클러스터를 직접 검색
+
사내 ONTAP 클러스터를 직접 검색하는 데는 커넥터가 필요하지 않지만 추가 BlueXP 기능을 사용하려면 커넥터가 필요합니다.

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["온프레미스 ONTAP 클러스터에 대한 검색 및 관리 옵션에 대해 자세히 알아보세요."^]

* 소프트웨어 업데이트
* 지속 가능성
* 워크로드 공장




== 커넥터가 필요한 경우

표준 모드에서 BlueXP를 사용하는 경우 BlueXP의 다음 기능 및 서비스에 커넥터가 필요합니다.

* 경고
* ONTAP용 Amazon FSx 관리 기능
* Amazon S3 스토리지
* Azure Blob 저장소
* 백업 및 복구
* 분류
* Cloud Volumes ONTAP
* 재해 복구
* E-Series 시스템
* 경제 효율성 ^1^
* Google Cloud Storage 버킷
* BlueXP 데이터 서비스와 사내 ONTAP 클러스터 통합
* 랜섬웨어 보호
* StorageGRID 시스템
* 계층화
* 볼륨 캐싱


^1^ 커넥터 없이 이러한 서비스에 액세스할 수 있는 동안 서비스에서 작업을 시작하려면 Connector가 필요합니다.

BlueXP가 제한된 모드 또는 프라이빗 모드로 사용하려면 커넥터가 필요합니다.



== 커넥터는 항상 작동해야 합니다

커넥터는 BlueXP 서비스 아키텍처의 기본 부분입니다. 관련 커넥터가 항상 가동, 작동 및 액세스 가능한지 확인하는 것은 귀하의 책임입니다. 이 서비스는 커넥터 가용성의 짧은 중단을 극복하도록 설계되었지만, 인프라 장애를 해결하기 위해 필요한 경우 즉각적인 조치를 취해야 합니다.

이 문서는 EULA의 적용을 받습니다. 설명서에 따라 제품을 작동하지 않을 경우, 제품의 기능 및 작동, 그리고 EULA에 따른 귀하의 권리에 부정적인 영향을 미칠 수 있습니다.



== 지원되는 위치

커넥터는 다음 위치에서 지원됩니다.

* Amazon Web Services에서 직접 지원합니다
* Microsoft Azure를 참조하십시오
+
Azure의 커넥터는 관리하는 Cloud Volumes ONTAP 시스템과 동일한 Azure 지역 또는 Cloud Volumes ONTAP 시스템용 에 배포해야 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure 지역 쌍"^] 합니다. 이 요구 사항은 Cloud Volumes ONTAP와 관련 저장소 계정 간에 Azure Private Link 연결이 사용되도록 보장합니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Cloud Volumes ONTAP에서 Azure 프라이빗 링크를 사용하는 방법에 대해 알아보십시오"^]

* Google 클라우드
+
Google Cloud에서 BlueXP 서비스를 사용하려면 Google Cloud에서 실행되는 Connector를 사용해야 합니다.

* 온프레미스




== 클라우드 공급자와 커뮤니케이션

Connector는 AWS, Azure 및 Google Cloud와의 모든 통신에 TLS 1.3를 사용합니다.



== 제한된 모드 및 비공개 모드

제한된 모드 또는 비공개 모드에서 BlueXP를 사용하려면 Connector를 설치한 다음 Connector에서 로컬로 실행되는 사용자 인터페이스에 액세스하여 BlueXP를 시작합니다.

link:concept-modes.html["BlueXP 배포 모드에 대해 알아보십시오"].



== 커넥터를 설치하는 방법

BlueXP에서 직접 커넥터를 설치하거나, 클라우드 공급업체의 마켓플레이스를 이용하거나, 직접 Linux 호스트에 소프트웨어를 수동으로 설치할 수 있습니다. 표준 모드, 제한 모드 또는 비공개 모드에서 BlueXP를 사용하고 있는지 여부에 따라 시작 방법이 달라집니다.

* link:concept-modes.html["BlueXP 배포 모드에 대해 알아보십시오"]
* link:task-quick-start-standard-mode.html["표준 모드에서 BlueXP를 시작하십시오"]
* link:task-quick-start-restricted-mode.html["제한된 모드에서 BlueXP를 시작하십시오"]
* link:task-quick-start-private-mode.html["프라이빗 모드에서 BlueXP를 시작하십시오"]




== 권한

BlueXP에서 직접 Connector를 만들려면 특정 권한이 필요하며 Connector 인스턴스 자체에 다른 권한 집합이 필요합니다. BlueXP에서 직접 AWS 또는 Azure에서 커넥터를 생성하는 경우 BlueXP는 필요한 권한으로 Connector를 생성합니다.

표준 모드에서 BlueXP를 사용할 때 사용 권한을 제공하는 방법은 Connector를 생성하는 계획에 따라 다릅니다.

사용 권한을 설정하는 방법에 대한 자세한 내용은 다음을 참조하십시오.

* 표준 모드
+
** link:concept-install-options-aws.html["AWS의 커넥터 설치 옵션"]
** link:concept-install-options-azure.html["Azure의 커넥터 설치 옵션"]
** link:concept-install-options-google.html["Google Cloud의 커넥터 설치 옵션"]
** link:task-install-connector-on-prem.html#step-4-set-up-cloud-permissions["온프레미스 배포에 대한 클라우드 권한 설정"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["제한된 모드에 대한 권한을 설정합니다"]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["비공개 모드에 대한 권한을 설정합니다"]


Connector에 일상적인 작업에 필요한 정확한 사용 권한을 보려면 다음 페이지를 참조하십시오.

* link:reference-permissions-aws.html["Connector에서 AWS 권한을 사용하는 방법에 대해 알아보십시오"]
* link:reference-permissions-azure.html["Connector에서 Azure 권한을 사용하는 방법에 대해 알아봅니다"]
* link:reference-permissions-gcp.html["Connector가 Google Cloud 권한을 사용하는 방법에 대해 알아보십시오"]


이후 릴리스에 새 권한이 추가되면 Connector 정책을 업데이트할 책임은 사용자에게 있습니다. 새 권한이 필요한 경우 릴리스 노트에 해당 권한이 나열됩니다.



== 커넥터 업그레이드

일반적으로 매월 커넥터 소프트웨어를 업데이트하여 새로운 기능을 소개하고 안정성 향상을 제공합니다. BlueXP  플랫폼의 대부분의 서비스와 기능은 SaaS 기반 소프트웨어를 통해 제공되지만 커넥터 버전에 따라 몇 가지 기능이 달라집니다. 여기에는 Cloud Volumes ONTAP 관리, 온프레미스 ONTAP 클러스터 관리, 설정 및 도움말이 포함됩니다.

표준 모드 또는 제한된 모드에서 BlueXP를 사용할 경우, 소프트웨어 업데이트를 받을 수 있도록 아웃바운드 인터넷에 액세스할 수 있는 경우 Connector에서 소프트웨어를 자동으로 최신 버전으로 업데이트합니다. 비공개 모드에서 BlueXP를 사용하는 경우 커넥터를 수동으로 업그레이드해야 합니다.

link:task-upgrade-connector.html["비공개 모드를 사용할 때 커넥터 소프트웨어를 수동으로 업그레이드하는 방법에 대해 알아봅니다"]..



== 운영 체제 및 VM 유지 보수

커넥터 호스트에서 운영 체제를 유지 관리하는 것은 고객의 책임입니다. 예를 들어, 귀사(고객)는 운영 체제 배포에 대한 회사의 표준 절차에 따라 Connector 호스트의 운영 체제에 보안 업데이트를 적용해야 합니다.

고객(고객)은 사소한 보안 업데이트를 적용할 때 Connector 호스트의 서비스를 중지할 필요가 없습니다.

Connector VM을 중지했다가 시작해야 하는 경우 클라우드 공급자의 콘솔에서 또는 온프레미스 관리를 위한 표준 절차를 사용해야 합니다.

<<커넥터는 항상 작동해야 합니다,커넥터는 항상 작동해야 합니다>>.



== 다중 작업 환경 및 커넥터

커넥터는 BlueXP에서 여러 작업 환경을 관리할 수 있습니다. 단일 커넥터가 관리해야 하는 최대 작업 환경 수는 서로 다릅니다. 운영 환경의 유형, 볼륨 수, 관리되는 용량 및 사용자 수에 따라 달라집니다.

대규모 구축이 있는 경우 NetApp 담당자와 협력하여 환경을 사이징합니다. 도중에 문제가 발생하는 경우 제품 내 채팅을 통해 문의해 주십시오.

경우에 따라 하나의 커넥터만 필요할 수 있지만 둘 이상의 커넥터가 필요할 수 있습니다.

다음은 몇 가지 예입니다.

* 멀티클라우드 환경(예: AWS와 Azure)이 있고 AWS에 하나의 커넥터를 두고 Azure에 다른 커넥터를 두는 것을 선호합니다. 각 는 이러한 환경에서 실행되는 Cloud Volumes ONTAP 시스템을 관리합니다.
* 서비스 공급자는 하나의 BlueXP  조직을 사용하여 고객에게 서비스를 제공하고 다른 조직을 사용하여 하나의 사업부에 대한 재해 복구를 제공할 수 있습니다. 각 조직에는 별도의 커넥터가 있습니다.

