---
sidebar: sidebar 
permalink: concept-data-services.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Connector는 클라우드 네트워크 또는 사내 네트워크에서 실행되는 NetApp 소프트웨어입니다. 데이터 인프라를 관리하기 위해 BlueXP에서 수행해야 하는 작업을 실행합니다. Connector는 수행해야 하는 작업에 대해 BlueXP SaaS 레이어를 지속적으로 폴링합니다. BlueXP를 시작하기 위해 커넥터가 필요하지 않지만 모든 BlueXP 기능 및 서비스를 잠금 해제하려면 커넥터를 만들어야 합니다. 
---
= BlueXP  서비스에 관해 자세히 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP는 사내 및 클라우드 환경 전반에서 데이터를 구축, 보호, 관리할 수 있는 단일 제어 계층을 제공합니다.

BlueXP  SaaS 서비스(표준 모드), 제한된 클라우드 환경에서 BlueXP 를 실행할지(제한된 모드), 아니면 자체 온프레미스 데이터 센터(프라이빗 모드)에 설치할지를 선택할 수 있습니다. 어떤 환경에서든 중앙 집중식 관리 및 추가 데이터 서비스를 활용하여 스토리지 리소스의 상태를 유지하고 안전하게 보호할 수 있습니다.

선택한 모드에 따라 사용 가능한 서비스와 관리할 수 있는 스토리지 리소스가 결정됩니다.

시작하기 전에 각 모드에서 지원하는 다양한 스토리지 리소스와 사용 가능한 데이터 서비스를 비교하여 회사의 요구 사항에 적합한 스토리지 리소스를 결정하십시오.



== 데이터 서비스

다음 표에서는 각 배포 모드에서 사용할 수 있는 데이터 서비스, 구독이 필요한지 여부 및 지원 계정이 필요한 시기를 보여 줍니다.

[NOTE]
====
* 커넥터 * 테이블의 커넥터 열은 표준 모드용 커넥터가 필요한 시기를 나타냅니다. BlueXP 를 제한 모드 또는 비공개 모드로 사용하는 경우 항상 커넥터가 있어야 합니다.

====
[cols="24,19,19,19,19"]
|===
|  | 지원 계정이 필요합니다 | 커넥터가 필요합니다 | 구독이 필요합니다 | 모드 가용성 


| 경고 | 예 | 예 | 아니요 | 모두 


| 백업 및 복구 | 예 | 예 | 예 | 표준, 제한 


| 분류 | 예 | 아니요 | 아니요 | 모두 


| 복사 및 동기화 | 아니요 | 아니요 | 예 |  


| 디지털 자문업체 | 예 | 아니요 | 아니요 | 모두 


| 디지털 지갑 | 예 | 아니요 * | 아니요 | 모두 


| 재해 복구 | 아니요 | 예 | 예 | 표준, 제한 


| 경제적인 효율성 | 예 | 예 | 아니요 |  


| 운영 복원력 | 예 | 예 * | 아니요 |  


| 랜섬웨어 보호 | 아니요 | 예 | 아니요 | 표준 


| 복제 | 아니요 | 아니요 * | 아니요 | 표준, 제한 


| 소프트웨어 업데이트 | 예 | 아니요 | 아니요 | 모두 


| 지원 케이스 관리 | 예 | 아니요 | 아니요 | 모두 


| 계층화 | 아니요 | 아니요 * | 예 | 표준 


| 볼륨 캐싱 | 아니요 | 아니요 | 아니요 | 표준 
|===


== NetApp 스토리지

대부분의 NetApp 스토리지 리소스를 BlueXP 에서 직접 관리할 수 있으므로 동일한 애플리케이션에서 모든 리소스를 볼 수 있습니다.

다음 표에는 각 배포 모드에서 관리할 수 있는 스토리지 리소스 및 Connector 또는 구독이 필요한 경우에 대한 목록이 나와 있습니다.

[NOTE]
====
* 커넥터 * 테이블의 커넥터 열은 표준 모드용 커넥터가 필요한 시기를 나타냅니다. BlueXP 를 제한 모드 또는 비공개 모드로 사용하는 경우 항상 커넥터가 있어야 합니다.

====
[cols="24,19,19,19,19"]
|===
|  | 지원 계정이 필요합니다 | 커넥터가 필요합니다 | 구독이 필요합니다 | 모드 가용성 


| NetApp ONTAP용 Amazon FSx | 예 | 없음 1 | 예 | 표준 


| Amazon S3 스토리지 | 예 | 아니요 | 예 | 표준 


| Azure Blob 저장소 | 예 | 아니요 | 아니요 | 표준 


| Azure NetApp Files | 아니요 | 없음 2 | 예 | 표준, 제한 


| Cloud Volumes ONTAP | 예 | 예 | 예 | 표준, 제한 


| Google Cloud용 Cloud Volumes Service | 아니요 | 아니요 | 예? | 표준 


| E-Series 시스템 | 아니요 | 예 | 아니요 | 표준 


| Google 클라우드 스토리지 | 아니요 | 예 | 예? | 표준 


| 온프레미스 ONTAP 클러스터 | 예 | 없음 3 | 아니요 | 모두 


| StorageGRID | 예 | 예 | 아니요 | 표준, 제한 
|===
일부 작업에는 커넥터 또는 BlueXP  워크로드 팩토리 링크가 필요합니다. https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["커넥터 또는 링크가 필요한 작업에 대해 알아봅니다"^]

BlueXP  분류를 사용하여 Azure NetApp Files 데이터를 스캔하려면 커넥터가 필요하지만 Azure NetApp Files를 설정하고 관리하는 데 커넥터가 필요하지 않습니다.

ONTAP 클러스터 직접 검색에 커넥터는 필요하지 않지만 추가 BlueXP  기능을 사용하려면 커넥터가 필요합니다. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["온프레미스 ONTAP 클러스터를 위한 검색 및 관리 옵션에 대해 자세히 알아보십시오"^]
