---
settings:
  name: Set up and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: 설정 및 관리 문서
    url: "/index.html"
  - title: 릴리스 정보
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
    - title: 제한 사항
      url: "/reference-limitations.html"
  - title: 시작하십시오
    entries:
    - title: Cloud Manager에 대해 자세히 알아보십시오
      url: "/concept-overview.html"
    - title: 시작 체크리스트
      url: "/reference-checklist-cm.html"
    - title: Cloud Central에 가입하십시오
      url: "/task-signing-up.html"
    - title: Cloud Manager에 로그인합니다
      url: "/task-logging-in.html"
    - title: NetApp 계정 설정
      entries:
      - title: NetApp 계정 에 대해 알아보십시오
        url: "/concept-netapp-accounts.html"
      - title: 작업 영역 및 사용자를 설정합니다
        url: "/task-setting-up-netapp-accounts.html"
    - title: 커넥터를 설정합니다
      entries:
      - title: 커넥터에 대해 자세히 알아보십시오
        url: "/concept-connectors.html"
      - title: AWS에서 커넥터를 생성합니다
        url: "/task-creating-connectors-aws.html"
      - title: Azure에서 커넥터를 만듭니다
        url: "/task-creating-connectors-azure.html"
      - title: Google Cloud에서 Connector를 생성합니다
        url: "/task-creating-connectors-gcp.html"
    - title: 다음 단계로 넘어갑니다
      url: "/reference-whats-next.html"
  - title: Cloud Manager 관리
    entries:
    - title: NetApp 계정
      entries:
      - title: 계정을 관리합니다
        url: "/task-managing-netapp-accounts.html"
      - title: 계정의 작업을 모니터링합니다
        url: "/task-monitor-cm-operations.html"
      - title: 사용자 역할
        url: "/reference-user-roles.html"
    - title: 커넥터
      entries:
      - title: 고급 구축
        entries:
        - title: AWS Marketplace에서 생성
          url: "/task-launching-aws-mktp.html"
        - title: Azure Marketplace에서 생성
          url: "/task-launching-azure-mktp.html"
        - title: 인터넷을 사용하여 자신의 호스트에 설치합니다
          url: "/task-installing-linux.html"
        - title: 인터넷 없이 온-프레미스에 설치합니다
          url: "/task-install-connector-onprem-no-internet.html"
      - title: 커넥터의 시스템 ID를 찾습니다
        url: "/task-finding-system-id.html"
      - title: 기존 커넥터 관리
        url: "/task-managing-connectors.html"
      - title: HTTPS 인증서를 설치합니다
        url: "/task-installing-https-cert.html"
      - title: 프록시 설정을 구성합니다
        url: "/task-configuring-proxy.html"
      - title: 기본 구성
        url: "/reference-connector-default-config.html"
    - title: 검색된 클라우드 스토리지
      entries:
      - title: Amazon S3 버킷을 확인합니다
        url: "/task-viewing-amazon-s3.html"
      - title: Azure Blob 계정을 봅니다
        url: "/task-viewing-azure-blob.html"
      - title: Google Cloud Storage 버킷을 확인하십시오
        url: "/task-viewing-gcp-storage.html"
    - title: AWS 자격 증명
      entries:
      - title: 개요
        url: "/concept-accounts-aws.html"
      - title: 자격 증명 및 구독을 관리합니다
        url: "/task-adding-aws-accounts.html"
    - title: Azure 자격 증명
      entries:
      - title: 개요
        url: "/concept-accounts-azure.html"
      - title: 자격 증명 및 구독을 관리합니다
        url: "/task-adding-azure-accounts.html"
    - title: Google Cloud 자격 증명
      entries:
      - title: 개요
        url: "/concept-accounts-gcp.html"
      - title: 자격 증명 및 구독을 관리합니다
        url: "/task-adding-gcp-accounts.html"
    - title: NetApp Support 사이트 계정
      url: "/task-adding-nss-accounts.html"
    - title: My Opportunities를 사용하여 검색
      url: "/concept-my-opportunities.html"
  - title: 참조하십시오
    entries:
    - title: 권한
      entries:
      - title: 권한 요약
        url: "/reference-permissions.html"
      - title: Connector에 대한 AWS 권한
        url: "/reference-permissions-aws.html"
      - title: Connector에 대한 Azure 권한
        url: "/reference-permissions-azure.html"
      - title: Connector에 대한 Google Cloud 권한
        url: "/reference-permissions-gcp.html"
    - title: 포트
      entries:
      - title: AWS의 보안 그룹 규칙
        url: "/reference-ports-aws.html"
      - title: Azure의 보안 그룹 규칙
        url: "/reference-ports-azure.html"
      - title: Google Cloud의 방화벽 규칙
        url: "/reference-ports-gcp.html"
      - title: 사내 커넥터용 포트
        url: "/reference-ports-on-prem.html"
  - title: 지식 및 지원
    entries:
    - title: 지원을 위해 등록하십시오
      url: "/task-support-registration.html"
    - title: 도움을 받으십시오
      url: "/task-get-help.html"
  - title: 법적 고지
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: Cloud Manager에 대해 자세히 알아보십시오
      url: concept-overview.html
    - title: 시작 체크리스트
      url: reference-checklist-cm.html
  - title: 커넥터
    links:
    - title: 커넥터에 대해 자세히 알아보십시오
      url: concept-connectors.html
    - title: 커넥터 관리
      url: task-managing-connectors.html
  - title: NetApp 계정
    links:
    - title: NetApp 계정 에 대해 알아보십시오
      url: concept-netapp-accounts.html
    - title: 작업 영역 및 사용자를 설정합니다
      url: task-setting-up-netapp-accounts.html
    - title: NetApp 계정을 관리합니다
      url: task-managing-netapp-accounts.html
  - title: 클라우드 공급자 계정
    links:
    - title: AWS 자격 증명 관리
      url: task-adding-aws-accounts.html
    - title: Azure 자격 증명을 관리합니다
      url: task-adding-azure-accounts.html
    - title: Google Cloud 자격 증명을 관리합니다
      url: task-adding-gcp-accounts.html
  - title: 블로그 커뮤니티
    links:
    - title: NetApp 커뮤니티
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central 블로그
      url: https://cloud.netapp.com/blog/topic/cloud-manager
    - title: 클라우드 웨비나
      url: https://cloud.netapp.com/events
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
  sidebar_label: 모든 Cloud Manager 설명서
