---
settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 설치 및 관리 문서
    url: "/index.html"
  - title: 릴리스 정보
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
    - title: 제한 사항
      url: "/reference-limitations.html"
  - title: 시작하십시오
    entries:
    - title: 기본 사항 학습
      entries:
      - title: BlueXP 개요
        url: "/concept-overview.html"
      - title: 계정
        url: "/concept-netapp-accounts.html"
      - title: 커넥터
        url: "/concept-connectors.html"
      - title: 배포 모드
        url: "/concept-modes.html"
    - title: 표준 모드로 시작하십시오
      entries:
      - title: 빠른 시작
        url: "/task-quick-start-standard-mode.html"
      - title: 콘솔 액세스를 위한 네트워킹
        url: "/reference-networking-saas-console.html"
      - title: BlueXP에 등록하십시오
        url: "/task-sign-up-saas.html"
      - title: BlueXP에 로그인합니다
        url: "/task-logging-in.html"
      - title: 커넥터를 작성합니다
        entries:
        - title: 설치하고
          entries:
          - title: 빠른 시작
            url: "/task-quick-start-connector-aws.html"
          - title: 설치 옵션
            url: "/concept-install-options-aws.html"
          - title: 네트워킹 설정
            url: "/task-set-up-networking-aws.html"
          - title: 호스트 요구 사항을 검토합니다
            url: "/reference-host-requirements-aws.html"
          - title: AWS 권한을 설정합니다
            url: "/task-set-up-permissions-aws.html"
          - title: 커넥터를 작성합니다
            url: "/task-install-connector-aws.html"
          - title: BlueXP에 대한 권한을 제공합니다
            url: "/task-provide-permissions-aws.html"
        - title: Azure를 지원합니다
          entries:
          - title: 빠른 시작
            url: "/task-quick-start-connector-azure.html"
          - title: 설치 옵션
            url: "/concept-install-options-azure.html"
          - title: 네트워킹 설정
            url: "/task-set-up-networking-azure.html"
          - title: 호스트 요구 사항을 검토합니다
            url: "/reference-host-requirements-azure.html"
          - title: Azure 권한을 설정합니다
            url: "/task-set-up-permissions-azure.html"
          - title: 커넥터를 작성합니다
            url: "/task-install-connector-azure.html"
          - title: BlueXP에 대한 권한을 제공합니다
            url: "/task-provide-permissions-azure.html"
        - title: Google 클라우드
          entries:
          - title: 빠른 시작
            url: "/task-quick-start-connector-google.html"
          - title: 설치 옵션
            url: "/concept-install-options-google.html"
          - title: 네트워킹 설정
            url: "/task-set-up-networking-google.html"
          - title: 호스트 요구 사항을 검토합니다
            url: "/reference-host-requirements-google.html"
          - title: Google Cloud 권한을 설정합니다
            url: "/task-set-up-permissions-google.html"
          - title: Google Cloud API를 활성화합니다
            url: "/task-enable-apis-google.html"
          - title: 커넥터를 작성합니다
            url: "/task-install-connector-google.html"
          - title: BlueXP에 대한 권한을 제공합니다
            url: "/task-provide-permissions-google.html"
        - title: 온프레미스
          entries:
          - title: 빠른 시작
            url: "/task-quick-start-connector-on-prem.html"
          - title: 네트워킹 설정
            url: "/task-set-up-networking-on-prem.html"
          - title: 호스트 요구 사항을 검토합니다
            url: "/reference-host-requirements-on-prem.html"
          - title: 클라우드 권한 설정
            url: "/task-set-up-permissions-on-prem.html"
          - title: 커넥터를 작성합니다
            url: "/task-install-connector-on-prem.html"
          - title: BlueXP에 대한 권한을 제공합니다
            url: "/task-provide-permissions-on-prem.html"
      - title: BlueXP에 가입하십시오
        url: "/task-subscribe-standard-mode.html"
      - title: 다음에 할 수 있는 일
        url: "/reference-whats-next.html"
    - title: 제한된 모드로 시작하십시오
      entries:
      - title: 빠른 시작
        url: "/task-quick-start-restricted-mode.html"
      - title: 배포를 준비합니다
        url: "/task-prepare-restricted-mode.html"
      - title: 커넥터를 배포합니다
        url: "/task-install-restricted-mode.html"
      - title: BlueXP에 로그인합니다
        url: "/task-log-in-restricted-mode.html"
      - title: BlueXP에 가입하십시오
        url: "/task-subscribe-restricted-mode.html"
      - title: 다음에 할 수 있는 일
        url: "/reference-whats-next-restricted-mode.html"
    - title: 비공개 모드로 시작하십시오
      entries:
      - title: 빠른 시작
        url: "/task-quick-start-private-mode.html"
      - title: 배포를 준비합니다
        url: "/task-prepare-private-mode.html"
      - title: 커넥터를 배포합니다
        url: "/task-install-private-mode.html"
      - title: BlueXP에 로그인합니다
        url: "/task-log-in-private-mode.html"
      - title: 다음에 할 수 있는 일
        url: "/reference-whats-next-private-mode.html"
  - title: BlueXP 관리
    entries:
    - title: ID 제휴
      url: "/concept-federation.html"
    - title: BlueXP 계정
      entries:
      - title: 계정을 관리합니다
        url: "/task-managing-netapp-accounts.html"
      - title: 계정의 작업을 모니터링합니다
        url: "/task-monitor-cm-operations.html"
      - title: 다른 계정을 만듭니다
        url: "/task-create-account.html"
      - title: 사용자 역할
        url: "/reference-user-roles.html"
    - title: 커넥터
      entries:
      - title: 커넥터의 시스템 ID를 찾습니다
        url: "/task-finding-system-id.html"
      - title: 기존 커넥터 관리
        url: "/task-managing-connectors.html"
      - title: HTTPS 인증서를 설치합니다
        url: "/task-installing-https-cert.html"
      - title: 프록시 설정을 구성합니다
        url: "/task-configuring-proxy.html"
      - title: 기본 구성
        url: "/reference-connector-default-config.html"
    - title: 자격 증명
      entries:
      - title: AWS 자격 증명 관리
        entries:
        - title: 개요
          url: "/concept-accounts-aws.html"
        - title: 자격 증명 및 구독을 관리합니다
          url: "/task-adding-aws-accounts.html"
      - title: Azure 자격 증명을 관리합니다
        entries:
        - title: 개요
          url: "/concept-accounts-azure.html"
        - title: 자격 증명 및 구독을 관리합니다
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud 자격 증명을 관리합니다
        entries:
        - title: 개요
          url: "/concept-accounts-gcp.html"
        - title: 자격 증명 및 구독을 관리합니다
          url: "/task-adding-gcp-accounts.html"
      - title: BlueXP 계정과 연결된 NSS 자격 증명을 관리합니다
        url: "/task-adding-nss-accounts.html"
      - title: BlueXP 로그인과 관련된 자격 증명을 관리합니다
        url: "/task-manage-user-credentials.html"
    - title: 검색된 클라우드 스토리지
      entries:
      - title: Amazon S3 버킷을 관리합니다
        url: "/task-viewing-amazon-s3.html"
      - title: Azure Blob 계정을 관리합니다
        url: "/task-viewing-azure-blob.html"
      - title: Google Cloud Storage 버킷 관리
        url: "/task-viewing-gcp-storage.html"
  - title: 참조하십시오
    entries:
    - title: 권한
      entries:
      - title: 권한 요약
        url: "/reference-permissions.html"
      - title: Connector에 대한 AWS 권한
        url: "/reference-permissions-aws.html"
      - title: Connector에 대한 Azure 권한
        url: "/reference-permissions-azure.html"
      - title: Connector에 대한 Google Cloud 권한
        url: "/reference-permissions-gcp.html"
    - title: 포트
      entries:
      - title: AWS의 보안 그룹 규칙
        url: "/reference-ports-aws.html"
      - title: Azure의 보안 그룹 규칙
        url: "/reference-ports-azure.html"
      - title: Google Cloud의 방화벽 규칙
        url: "/reference-ports-gcp.html"
      - title: 사내 커넥터용 포트
        url: "/reference-ports-on-prem.html"
  - title: 지식 및 지원
    entries:
    - title: 지원을 위해 등록하십시오
      url: "/task-support-registration.html"
    - title: 도움을 받으십시오
      url: "/task-get-help.html"
  - title: 법적 고지
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: BlueXP에 대해 자세히 알아보십시오
      url: concept-overview.html
    - title: 배포 모드에 대해 알아봅니다
      url: concept-modes.html
    - title: 표준 모드로 시작하십시오
      url: "/task-quick-start-standard-mode.html"
    - title: 제한된 모드로 시작하십시오
      url: "/task-quick-start-restricted-mode.html"
    - title: 비공개 모드로 시작하십시오
      url: "/task-quick-start-private-mode.html"
  - title: BlueXP 계정
    links:
    - title: BlueXP 계정에 대해 알아보십시오
      url: concept-netapp-accounts.html
    - title: BlueXP 계정을 관리합니다
      url: task-managing-netapp-accounts.html
    - title: 계정의 작업을 모니터링합니다
      url: task-monitor-cm-operations.html
  - title: 커넥터
    links:
    - title: 커넥터에 대해 자세히 알아보십시오
      url: concept-connectors.html
    - title: AWS에서 커넥터 생성(표준 모드)
      url: task-quick-start-connector-aws.html
    - title: Azure에서 커넥터 만들기(표준 모드)
      url: task-quick-start-connector-azure.html
    - title: Google Cloud에서 커넥터 생성(표준 모드)
      url: task-quick-start-connector-google.html
    - title: 온-프레미스 커넥터 만들기(표준 모드)
      url: task-quick-start-connector-on-prem.html
    - title: 커넥터 관리
      url: task-managing-connectors.html
  - title: 권한
    links:
    - title: 권한 요약
      url: reference-permissions.html
    - title: Connector에 대한 AWS 권한
      url: reference-permissions-aws.html
    - title: Connector에 대한 Azure 권한
      url: reference-permissions-azure.html
    - title: Connector에 대한 Google Cloud 권한
      url: reference-permissions-gcp.html
  - title: 자격 증명
    links:
    - title: AWS 자격 증명 관리
      url: task-adding-aws-accounts.html
    - title: Azure 자격 증명을 관리합니다
      url: task-adding-azure-accounts.html
    - title: Google Cloud 자격 증명을 관리합니다
      url: task-adding-gcp-accounts.html
    - title: 계정의 NSS 자격 증명을 관리합니다
      url: task-adding-nss-accounts.html
  - title: 블로그 및 커뮤니티
    links:
    - title: NetApp 커뮤니티
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXP 블로그
      url: https://bluexp.netapp.com/blog
    - title: 클라우드 웨비나
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: 모든 BlueXP 설명서
