---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: SaaS 계층을 통해 제공되는 BlueXP 웹 기반 콘솔을 사용할 때 몇 가지 관리 작업을 완료하면 여러 개의 엔드포인트에 연결됩니다. BlueXP 콘솔에 액세스하는 컴퓨터는 이러한 엔드포인트에 연결해야 합니다. 
---
= BlueXP  콘솔에 대한 네트워킹을 준비합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
웹 기반 콘솔에 로그인하여 사용하면 BlueXP는 여러 엔드포인트에 연결하여 사용자가 시작한 작업을 완료합니다. 콘솔에 액세스하는 컴퓨터는 이러한 엔드포인트에 연결되어 있어야 합니다.

이러한 끝점은 다음 두 가지 시나리오로 연결됩니다.

* 섹션을 완료할 때 사용자 컴퓨터에서 https://console.bluexp.netapp.com["BlueXP 웹 기반 콘솔"^] 서비스형 소프트웨어(SaaS)로 제공됩니다.
* 사용자 컴퓨터에서 웹 브라우저를 열고 커넥터 호스트의 IP 주소를 입력한 다음 커넥터에 로그인하고 설정합니다. 커넥터를 수동으로 설치하는 경우 다음 단계를 수행해야 합니다.


[cols="2*"]
|===
| 엔드포인트 | 목적 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | 이는 웹 기반 콘솔을 사용하기 위해 웹 브라우저에 입력하는 엔드포인트입니다. 


| \https://api.bluexp.netapp.com | 웹 기반 콘솔은 이 엔드포인트에 접속하여 권한 부여, 라이선싱, 구독, 자격 증명, 알림 등과 관련된 작업을 위한 API와 상호 작용합니다. 


| \https://aiq.netapp.com | 디지털 어드바이저에 접속하려면 필요합니다. 


 a| 
AWS 서비스(amazonaws.com):

* CloudFormation 을 참조하십시오
* EC2(탄력적인 컴퓨팅 클라우드)
* 키 관리 서비스(KMS)
* 보안 토큰 서비스(STS)
* S3(Simple Storage Service)

| AWS의 BlueXP에서 커넥터를 구축하는 데 필요합니다. 정확한 엔드포인트는 커넥터를 배포하는 지역에 따라 달라집니다.  https://docs.aws.amazon.com/general/latest/gr/rande.html["자세한 내용은 AWS 문서를 참조하세요."] 제안:  https://docs.aws.amazon.com/general/latest/gr/rande.html["자세한 내용은 AWS 문서를 참조하세요."] 


| \https://management.azure.com

\https://login.microsoftonline.com | 대부분의 Azure 지역에서 BlueXP의 커넥터를 배포하는 데 필요합니다. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Azure 독일 지역의 BlueXP에서 커넥터를 배포하는 데 필요합니다. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Azure US Gov 지역의 BlueXP에서 커넥터를 배포하는 데 필요합니다. 


| \https://www.googleapis.com | Google Cloud의 BlueXP에서 커넥터를 배포하는 데 필요합니다. 


| \https://signin.b2c.netapp.com | NetApp Support 사이트(NSS) 자격 증명을 업데이트하거나 BlueXP에 새 NSS 자격 증명을 추가하는 데 필요합니다. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | 웹 브라우저는 BlueXP를 통한 중앙 집중식 사용자 인증을 위해 이러한 엔드포인트에 연결됩니다. 


| \https://widget.intercom.io | NetApp 지원팀과 상담할 수 있는 제품 내 채팅입니다. 
|===
커넥터가 일상적인 작업을 위해 엔드포인트에 연결하기 위한 아웃바운드 인터넷 액세스를 제공하는지 확인하세요. 아래 섹션의 링크를 따라가면 이러한 엔드포인트 목록을 확인할 수 있습니다.

.관련 정보
* 커넥터를 위한 네트워킹을 준비합니다
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["AWS 네트워킹 설정"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Azure 네트워킹을 설정합니다"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Google Cloud 네트워킹을 설정합니다"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["온프레미스 네트워킹 설정"]


* BlueXP 서비스를 위한 네트워킹을 준비합니다
+
각 BlueXP 서비스에 대한 문서를 참조하십시오.

+
https://docs.netapp.com/us-en/bluexp-family/["BlueXP 설명서"^]


