---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP  ID 및 액세스 관리에는 조직의 구성원에게 할당할 수 있는 미리 정의된 여러 역할이 포함되어 있습니다. 
---
= 사전 정의된 BlueXP  IAM 역할 및 권한
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  IAM(ID 및 액세스 관리)에는 리소스 계층 구조의 다양한 수준에서 조직 구성원에게 할당할 수 있는 미리 정의된 여러 역할이 포함되어 있습니다. 이러한 역할을 할당하기 전에 각 역할에 포함된 사용 권한을 이해해야 합니다. 역할은 플랫폼, 애플리케이션 및 데이터 서비스의 세 가지 범주로 분류됩니다.



== 플랫폼 역할

플랫폼 역할은 사용자에게 할당할 수 있는 가장 광범위한 역할이며 역할 할당 및 사용자 추가, 모든 BlueXP  기능 수행 등 BlueXP  관리에 대한 광범위한 권한을 허용합니다. BlueXP  IAM에는 조직 관리자 및 폴더 또는 프로젝트 관리자의 두 가지 플랫폼 역할이 포함되어 있습니다. 두 BlueXP  IAM 플랫폼 역할의 주된 차이점은 범위입니다.



=== 조직 관리자

사용자가 조직 내의 모든 프로젝트 및 폴더에 제한 없이 액세스하고, 프로젝트 또는 폴더에 구성원을 추가하고, BlueXP  작업을 수행하고 모든 데이터 서비스를 사용할 수 있도록 합니다.



=== 폴더 또는 프로젝트 관리자

사용자가 할당된 특정 프로젝트 및 폴더에 대해 무제한 액세스를 허용합니다. 자신이 관리하는 프로젝트 또는 폴더에 구성원을 추가할 수 있을 뿐 아니라 BlueXP  작업을 수행하고 할당된 폴더 또는 프로젝트 내의 모든 데이터 서비스를 사용할 수 있습니다.

폴더 또는 프로젝트 관리자 역할은 커넥터를 만들 수 없습니다.



=== 플랫폼 역할 비교 표

[cols="24,19,19"]
|===
| 작업 | 조직 관리자 | 폴더 또는 프로젝트 관리자 


| 커넥터를 작성합니다 | 예 | 아니요 


| 작업 환경 생성, 수정 또는 삭제(BlueXP  Canvas를 사용하여 새 리소스 추가 또는 검색) | 예 | 예 


| 삭제를 포함하여 프로젝트/폴더를 작성합니다 | 예 | 아니요 


| 기존 프로젝트/폴더 이름을 바꿉니다 | 예 | 예 


| 역할을 할당하고 사용자를 추가합니다 | 예 | 예 


| 자원을 폴더 및 프로젝트와 연결합니다 | 예 | 예 


| 커넥터를 폴더 및 프로젝트에 연결합니다 | 예 | 아니요 


| 폴더 및 프로젝트에서 커넥터를 제거합니다 | 예 | 아니요 


| 커넥터 관리(인증서, 설정 등 편집) | 예 | 아니요 


| 설정 > 자격 증명에서 자격 증명을 관리합니다 | 예 | 예 


| BlueXP  타임라인을 봅니다 | 예 | 예 


| BlueXP  서비스 사용 | 예 | 예 


| 지원에 BlueXP 를 등록하고 사례를 제출합니다 | 예 | 예 
|===
대규모 다국적 조직에 대한 BlueXP 의 조직 역할의 예:: 다국적 기업인 XYZ Corporation은 북미, 유럽 및 아시아 태평양을 기준으로 데이터 스토리지 리소스에 대한 액세스 권한을 분리하는 것을 목표로 합니다. 이들은 각 지역에서 리소스를 독점적으로 제어하면서 중앙 집중식 감독을 유지하기를 원합니다.
+
--
이를 위해 XYZ Corporation의 BlueXP 에서 조직 관리자 역할을 할당한 사람이 초기 작업 환경을 만든 다음 BlueXP 에 각 지역에 대해 별도의 폴더를 만듭니다. 각 영역의 폴더에는 해당 영역과 관련된 프로젝트(관련 리소스 포함)가 포함되어 있습니다. 조직 관리자는 각 지역의 BlueXP  사용자에게 폴더/프로젝트 관리자 역할을 할당합니다.

초기 설정이 완료되면 폴더 또는 프로젝트 관리자 역할을 가진 지역 관리자는 새 작업 환경을 만들고 해당 지역 내에 사용자를 추가할 수 있습니다. 이러한 지역 관리자는 할당된 폴더 및 프로젝트를 추가/제거/이름 변경할 수도 있습니다. 조직 관리자는 새로운 작업 환경 또는 리소스에 대한 권한을 상속하여 전체 조직 전체의 스토리지 사용량에 대한 가시성을 유지합니다.

--




== 응용 프로그램 역할

응용 프로그램 역할은 Active IQ 디지털 어드바이저(디지털 어드바이저)와 같은 BlueXP  응용 프로그램에 대한 액세스를 제공합니다.



=== 스토리지 관리자

사용자가 BlueXP 에서 소프트웨어 업데이트, BlueXP  작업 환경 생성 및 삭제와 같은 스토리지 관리 기능을 수행할 수 있습니다.

권한:: BlueXP  캔버스를 볼 수 있습니다. BlueXP  커넥터를 생성 및 관리할 수 있습니다. 다음을 포함하여 BlueXP 의 스토리지 상태 및 거버넌스 기능에 대한 읽기/쓰기 액세스가 있습니다.
+
--
* 디지털 자문업체
* 운영 복원력
* 소프트웨어 업데이트(소프트웨어 업데이트 수행 가능)
* 디지털 지갑
* 경제적인 효율성
* Sustainability 대시보드
* 경고


--




=== 스토리지 뷰어

BlueXP 의 상태 및 거버넌스 기능에 대한 읽기 전용 액세스를 제공합니다. 이 역할은 일반적으로 조직의 스토리지 리소스 상태를 모니터링하는 역할을 담당하는 사용자에게 할당됩니다. 이 역할을 가진 사용자는 BlueXP  내에서 여러 애플리케이션을 확인하여 소프트웨어 업데이트 계획과 효율성 계획을 수립하고 전반적인 스토리지 상태를 볼 수 있습니다.

권한:: 다음을 포함하여 BlueXP 의 스토리지 상태 및 거버넌스 기능에 대한 읽기 전용 액세스 권한이 있습니다.
+
--
* 디지털 자문업체
* 운영 복원력
* 소프트웨어 업데이트(업그레이드 계획 다운로드 가능)
* 디지털 지갑
* 경제적인 효율성
* Sustainability 대시보드
* 경고


--




== 데이터 서비스 역할

데이터 서비스 역할은 사용자에게 액세스 권한이 있는 조직, 프로젝트 또는 폴더 내의 데이터 서비스에 대한 사용 권한을 제공합니다.



=== SnapCenter 관리자

애플리케이션에 대한 BlueXP  백업 및 복구를 사용하여 온프레미스 ONTAP 클러스터의 스냅샷을 백업하는 기능을 제공합니다.

권한:: 이 역할을 가진 구성원은 BlueXP 에서 다음 작업을 수행할 수 있습니다.
+
--
* 백업 및 복구 > 애플리케이션에서 모든 작업을 완료합니다
* 권한이 있는 프로젝트 및 폴더의 모든 작업 환경을 관리합니다
* 모든 BlueXP  서비스 사용


--




=== 분류 뷰어

BlueXP  분류 스캔 결과를 볼 수 있는 기능을 제공합니다.

권한:: 규정 준수 정보를 보고 액세스 권한이 있는 리소스에 대한 보고서를 생성합니다. 이러한 사용자는 볼륨, 버킷 또는 데이터베이스 스키마의 스캔을 활성화하거나 비활성화할 수 없습니다.
+
--
이 역할을 가진 구성원은 다른 작업을 사용할 수 없습니다.

--




== 관련 링크

* link:concept-identity-and-access-management.html["BlueXP  ID 및 액세스 관리에 대해 자세히 알아보십시오"]
* link:task-iam-get-started.html["BlueXP  IAM을 시작하십시오"]
* link:task-iam-manage-members-permissions.html["BlueXP  구성원 및 해당 사용 권한을 관리합니다"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["BlueXP  IAM용 API에 대해 알아보십시오"^]

