---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: BlueXP를 시작할 때 네트워킹으로 BlueXP 콘솔의 특정 엔드포인트에 액세스할 수 있는지 확인합니다. BlueXP 사용 방법에 따라 커넥터 및 특정 BlueXP 서비스에 대한 네트워킹을 설정해야 할 수도 있습니다. 
---
= 네트워킹을 준비합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP를 시작할 때 네트워킹으로 BlueXP 콘솔의 특정 엔드포인트에 액세스할 수 있는지 확인합니다. BlueXP 사용 방법에 따라 커넥터 및 특정 BlueXP 서비스에 대한 네트워킹을 설정해야 할 수도 있습니다.



== BlueXP 콘솔에 대한 사용자 액세스를 위한 네트워킹을 준비합니다

SaaS 계층을 통해 제공되는 BlueXP 웹 기반 콘솔을 사용하면 여러 엔드포인트에 접속하여 데이터 관리 작업을 완료합니다. 웹 브라우저를 실행하는 컴퓨터에 이러한 끝점에 대한 연결이 있어야 합니다.

[cols="2*"]
|===
| 엔드포인트 | 목적 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | 웹 브라우저는 BlueXP 웹 기반 콘솔을 사용할 때 이러한 URL에 연락합니다. 


 a| 
AWS 서비스(amazonaws.com):

* CloudFormation 을 참조하십시오
* EC2(탄력적인 컴퓨팅 클라우드)
* 키 관리 서비스(KMS)
* 보안 토큰 서비스(STS)
* S3(Simple Storage Service)

| AWS의 BlueXP에서 커넥터를 구축하는 데 필요합니다. 정확한 끝점은 Connector를 배포하는 영역에 따라 다릅니다. https://docs.aws.amazon.com/general/latest/gr/rande.html["자세한 내용은 AWS 설명서를 참조하십시오."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | 대부분의 Azure 지역에서 BlueXP의 커넥터를 배포하는 데 필요합니다. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Azure 독일 지역의 BlueXP에서 커넥터를 배포하는 데 필요합니다. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Azure US Gov 지역의 BlueXP에서 커넥터를 배포하는 데 필요합니다. 


| \https://www.googleapis.com | Google Cloud의 BlueXP에서 커넥터를 배포하는 데 필요합니다. 


| \https://signin.b2c.netapp.com | NetApp Support 사이트(NSS) 자격 증명을 업데이트하거나 BlueXP에 새 NSS 자격 증명을 추가하는 데 필요합니다. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | 웹 브라우저는 BlueXP를 통한 중앙 집중식 사용자 인증을 위해 이러한 엔드포인트에 연결됩니다. 


| \https://widget.intercom.io | 제품 내에서 NetApp 클라우드 전문가와 상담할 수 있는 채팅을 제공합니다. 
|===
이러한 엔드포인트 외에도, Connector가 일상적인 작업을 위해 특정 엔드포인트에 대한 아웃바운드 인터넷 액세스를 가지고 있는지 확인해야 합니다. 아래 다음 섹션의 링크를 따라 이러한 끝점 목록을 찾을 수 있습니다.



== 커넥터를 위한 네트워킹을 준비합니다

Connector를 위한 네트워킹 준비 방법은 Connector를 설치할 계획이 있는 위치(클라우드 또는 구내)에 따라 다릅니다. 커넥터 네트워킹 요구 사항에 대한 자세한 내용은 다음 페이지를 참조하십시오.

* link:task-set-up-networking-aws.html["AWS 네트워킹 설정"]
* link:task-set-up-networking-azure.html["Azure 네트워킹을 설정합니다"]
* link:task-set-up-networking-google.html["Google Cloud 네트워킹을 설정합니다"]
* link:task-set-up-networking-on-prem.html["사내 네트워킹을 설정합니다"]




== BlueXP 서비스를 위한 네트워킹을 준비합니다

BlueXP를 시작할 때 사용하려는 BlueXP 서비스의 네트워킹 요구 사항을 충족하는지 확인해야 합니다. 자세한 내용은 각 서비스 설명서를 참조하십시오.

https://docs.netapp.com/us-en/bluexp-family/["BlueXP 설명서"^]
