---
sidebar: sidebar 
permalink: reference-connector-default-config.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux, connector configuration, connector installation folder, connector folder, connector log, ubuntu 
summary: Connector를 배포하기 전에 또는 문제를 해결해야 하는 경우에 대해 자세히 알아볼 수 있습니다. 
---
= Connector의 기본 설정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
커넥터 구성을 배포하기 전에 또는 문제를 해결해야 하는 경우에 대해 자세히 알아볼 수 있습니다.



== 인터넷 액세스가 가능한 기본 구성

BlueXP에서 Connector를 배포했거나 클라우드 공급업체의 마켓플레이스에서 커넥터를 배포했거나 인터넷에 액세스할 수 있는 온프레미스 Linux 호스트에 수동으로 설치한 경우 다음 구성 세부 정보가 적용됩니다.



=== AWS 세부 정보

BlueXP 또는 클라우드 제공업체의 마켓플레이스에서 Connector를 배포한 경우 다음 사항에 유의하십시오.

* EC2 인스턴스 유형은 T3.xLarge입니다.
* 이미지의 운영 체제는 Ubuntu 22.04 LTS입니다.
+
운영 체제에는 GUI가 포함되어 있지 않습니다. 시스템에 액세스하려면 터미널을 사용해야 합니다.

* 설치 과정에는 필요한 컨테이너 오케스트레이션 툴인 Docker Engine이 포함됩니다.
* EC2 Linux 인스턴스의 사용자 이름은 Ubuntu입니다(2023년 5월 이전에 생성된 커넥터의 경우 사용자 이름은 EC2-user입니다).
* 기본 시스템 디스크는 100GiB GP2 디스크입니다.




=== Azure 세부 정보

BlueXP 또는 클라우드 제공업체의 마켓플레이스에서 Connector를 배포한 경우 다음 사항에 유의하십시오.

* VM 유형은 DS3 v2입니다.
* 이미지의 운영 체제는 Ubuntu 22.04 LTS입니다.
+
운영 체제에는 GUI가 포함되어 있지 않습니다. 시스템에 액세스하려면 터미널을 사용해야 합니다.

* 설치 과정에는 필요한 컨테이너 오케스트레이션 툴인 Docker Engine이 포함됩니다.
* 기본 시스템 디스크는 100GiB 프리미엄 SSD 디스크입니다.




=== Google Cloud 세부 정보

BlueXP에서 커넥터를 배포한 경우 다음 사항에 유의하십시오.

* VM 인스턴스는 n2-standard-4입니다.
* 이미지의 운영 체제는 Ubuntu 22.04 LTS입니다.
+
운영 체제에는 GUI가 포함되어 있지 않습니다. 시스템에 액세스하려면 터미널을 사용해야 합니다.

* 설치 과정에는 필요한 컨테이너 오케스트레이션 툴인 Docker Engine이 포함됩니다.
* 기본 시스템 디스크는 100GiB SSD 영구 디스크입니다.




=== 설치 폴더

Connector 설치 폴더는 다음 위치에 있습니다.

/opt/application/netapp/cloudmanager입니다



=== 로그 파일

로그 파일은 다음 폴더에 들어 있습니다.

* /opt/application/netapp/cloudmanager/log입니다
또는
* /opt/application/netapp/service-manager-2/로그(새로운 3.9.23 설치부터 시작)
+
이러한 폴더의 로그는 커넥터에 대한 세부 정보를 제공합니다.

* /opt/application/netapp/cloudmanager/docker/데이터/로그
+
이 폴더의 로그에는 Connector에서 실행되는 클라우드 서비스 및 BlueXP 서비스에 대한 세부 정보가 나와 있습니다.





=== 커넥터 서비스

* BlueXP 서비스의 이름은 occm입니다.
* occm 서비스는 MySQL 서비스에 따라 달라진다.
+
MySQL 서비스가 다운되면 occm 서비스도 다운됩니다.





=== 포트

커넥터는 Linux 호스트에서 다음 포트를 사용합니다.

* HTTP 액세스용 80
* HTTPS 액세스용 443




== 인터넷 액세스가 없는 기본 구성

인터넷 액세스가 없는 온프레미스 Linux 호스트에 커넥터를 수동으로 설치한 경우 다음 구성이 적용됩니다. link:task-quick-start-private-mode.html["이 설치 옵션에 대해 자세히 알아보십시오"].

* Connector 설치 폴더는 다음 위치에 있습니다.
+
/opt/application/netapp/DS

* 로그 파일은 다음 폴더에 들어 있습니다.
+
/var/lib/docker/volumes/DS_occmpdata/_data/log

+
이 폴더의 로그에는 Connector 및 Docker 이미지에 대한 세부 정보가 나와 있습니다.

* 모든 서비스가 Docker 컨테이너 내부에서 실행 중입니다
+
서비스는 실행 중인 Docker 런타임 서비스에 따라 다릅니다

* 커넥터는 Linux 호스트에서 다음 포트를 사용합니다.
+
** HTTP 액세스용 80
** HTTPS 액세스용 443



