---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP  ID 및 액세스 관리에는 조직의 구성원에게 할당할 수 있는 미리 정의된 여러 역할이 포함되어 있습니다. 
---
= BlueXP  플랫폼 액세스 역할
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
플랫폼 역할은 사용자에게 할당할 수 있는 가장 광범위한 역할이며 역할 할당 및 사용자 추가를 포함하여 BlueXP 관리에 대한 모든 권한을 허용할 수 있습니다. 플랫폼 역할을 가진 사용자는 BlueXP  내의 모든 데이터 서비스와 애플리케이션에 액세스할 수 있습니다. BlueXP 에는 * 조직 관리자 * 와 * 폴더 또는 프로젝트 관리자 * 의 두 가지 플랫폼 역할이 포함되어 있습니다. 두 BlueXP  플랫폼 역할 간의 주요 차이점은 역할이 적용되는 범위입니다.

.대규모 다국적 조직에 대한 BlueXP 의 조직 역할의 예
다국적 기업인 XYZ Corporation은 북미, 유럽 및 아시아 태평양을 기준으로 데이터 스토리지 리소스에 대한 액세스 권한을 분리하는 것을 목표로 합니다. 이들은 각 지역에서 리소스를 독점적으로 제어하면서 중앙 집중식 감독을 유지하기를 원합니다.

이를 위해 XYZ Corporation의 BlueXP 에서 * 조직 관리자 * 역할을 할당한 사람이 초기 작업 환경을 만든 다음 각 지역에 대해 BlueXP 에 별도의 폴더를 만듭니다. 각 영역의 폴더에는 해당 영역과 관련된 프로젝트(관련 리소스 포함)가 포함되어 있습니다. 조직 관리자 * 는 각 지역의 BlueXP  사용자에게 * 폴더 또는 프로젝트 관리자 * 역할을 할당합니다.

초기 설정이 완료되면 * 폴더 또는 프로젝트 관리자 * 역할을 가진 지역 관리자가 새 작업 환경을 만들고 해당 지역 내에 사용자를 추가할 수 있습니다. 이러한 지역 관리자는 할당된 폴더 및 프로젝트를 추가/제거/이름 변경할 수도 있습니다. 조직 관리자 * 는 새로운 작업 환경 또는 리소스에 대한 권한을 상속하여 조직 전체의 스토리지 사용량을 지속적으로 확인할 수 있습니다.

다음 표에는 각 BlueXP  플랫폼 역할이 수행할 수 있는 작업이 나와 있습니다.

[cols="2,1,1"]
|===
| 작업 | 조직 관리자 | 폴더 또는 프로젝트 관리자 


| 커넥터 작성 | 예 | 아니요 


| 작업 환경 생성, 수정 또는 삭제(BlueXP  Canvas를 사용하여 새 리소스 추가 또는 검색) | 예 | 예 


| 삭제를 포함하여 폴더와 프로젝트를 작성합니다 | 예 | 아니요 


| 기존 폴더와 프로젝트의 이름을 바꿉니다 | 예 | 예 


| 역할을 할당하고 사용자를 추가합니다 | 예 | 예 


| 자원을 폴더 및 프로젝트와 연결합니다 | 예 | 예 


| 커넥터를 폴더 및 프로젝트와 연결합니다 | 예 | 아니요 


| 폴더 및 프로젝트에서 커넥터를 제거합니다 | 예 | 아니요 


| 커넥터 관리(인증서, 설정 등 편집) | 예 | 아니요 


| 설정 > 자격 증명에서 자격 증명을 관리합니다 | 예 | 예 


| BlueXP  타임라인을 봅니다 | 예 | 예 


| BlueXP  서비스 사용 | 예 | 예 


| 지원에 BlueXP 를 등록하고 사례를 제출합니다 | 예 | 예 
|===