---
sidebar: sidebar 
permalink: reference-permissions-azure.html 
keywords: permissions, azure, azure permissions 
summary: BlueXP가 Azure에서 Connector VM을 시작하면 Connector에 Azure 구독 내의 리소스 및 프로세스를 관리할 수 있는 권한을 제공하는 사용자 지정 역할을 VM에 연결합니다. Connector는 사용 권한을 사용하여 여러 Azure 서비스에 대한 API 호출을 수행합니다. 
---
= Connector에 대한 Azure 권한
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP가 Azure에서 Connector VM을 시작하면 Connector에 Azure 구독 내의 리소스 및 프로세스를 관리할 수 있는 권한을 제공하는 사용자 지정 역할을 VM에 연결합니다. Connector는 사용 권한을 사용하여 여러 Azure 서비스에 대한 API 호출을 수행합니다.



== 사용자 지정 역할 권한

아래 표시된 사용자 지정 역할은 Connector가 Azure 네트워크 내의 리소스 및 프로세스를 관리하는 데 필요한 권한을 제공합니다.

BlueXP에서 직접 커넥터를 만들면 BlueXP에서 자동으로 이 사용자 정의 역할을 커넥터에 적용합니다.

Azure Marketplace에서 Connector를 배포하거나 Linux 호스트에 Connector를 수동으로 설치하는 경우 사용자 지정 역할을 직접 설정해야 합니다.

이러한 정책 사용에 대한 단계별 지침을 보려면 다음 페이지를 참조하십시오.

* link:task-install-connector-azure-marketplace.html#step-3-set-up-permissions["Azure Marketplace 배포에 대한 사용 권한을 설정합니다"]
* link:task-install-connector-on-prem.html#step-3-set-up-cloud-permissions["온프레미스 배포에 대한 권한을 설정합니다"]
* link:task-prepare-restricted-mode.html#step-5-prepare-cloud-permissions["제한된 모드에 대한 권한을 설정합니다"]
* link:task-prepare-private-mode.html#step-5-prepare-cloud-permissions["비공개 모드에 대한 권한을 설정합니다"]


또한 후속 릴리스에 새 권한이 추가되므로 역할이 최신 상태인지 확인해야 합니다.

[source, json]
----
{
    "Name": "BlueXP Operator",
    "Actions": [
                    "Microsoft.Compute/disks/delete",
                    "Microsoft.Compute/disks/read",
                    "Microsoft.Compute/disks/write",
                    "Microsoft.Compute/locations/operations/read",
                    "Microsoft.Compute/locations/vmSizes/read",
                    "Microsoft.Resources/subscriptions/locations/read",
                    "Microsoft.Compute/operations/read",
                    "Microsoft.Compute/virtualMachines/instanceView/read",
                    "Microsoft.Compute/virtualMachines/powerOff/action",
                    "Microsoft.Compute/virtualMachines/read",
                    "Microsoft.Compute/virtualMachines/restart/action",
                    "Microsoft.Compute/virtualMachines/deallocate/action",
                    "Microsoft.Compute/virtualMachines/start/action",
                    "Microsoft.Compute/virtualMachines/vmSizes/read",
                    "Microsoft.Compute/virtualMachines/write",
                    "Microsoft.Compute/images/read",
                    "Microsoft.Network/locations/operationResults/read",
                    "Microsoft.Network/locations/operations/read",
                    "Microsoft.Network/networkInterfaces/read",
                    "Microsoft.Network/networkInterfaces/write",
                    "Microsoft.Network/networkInterfaces/join/action",
                    "Microsoft.Network/networkSecurityGroups/read",
                    "Microsoft.Network/networkSecurityGroups/write",
                    "Microsoft.Network/networkSecurityGroups/join/action",
                    "Microsoft.Network/virtualNetworks/read",
                    "Microsoft.Network/virtualNetworks/checkIpAddressAvailability/read",
                    "Microsoft.Network/virtualNetworks/subnets/read",
                    "Microsoft.Network/virtualNetworks/subnets/write",
                    "Microsoft.Network/virtualNetworks/subnets/virtualMachines/read",
                    "Microsoft.Network/virtualNetworks/virtualMachines/read",
                    "Microsoft.Network/virtualNetworks/subnets/join/action",
                    "Microsoft.Resources/deployments/operations/read",
                    "Microsoft.Resources/deployments/read",
                    "Microsoft.Resources/deployments/write",
                    "Microsoft.Resources/resources/read",
                    "Microsoft.Resources/subscriptions/operationresults/read",
                    "Microsoft.Resources/subscriptions/resourceGroups/delete",
                    "Microsoft.Resources/subscriptions/resourceGroups/read",
                    "Microsoft.Resources/subscriptions/resourcegroups/resources/read",
                    "Microsoft.Resources/subscriptions/resourceGroups/write",
                    "Microsoft.Storage/checknameavailability/read",
                    "Microsoft.Storage/operations/read",
                    "Microsoft.Storage/storageAccounts/listkeys/action",
                    "Microsoft.Storage/storageAccounts/read",
                    "Microsoft.Storage/storageAccounts/delete",
                    "Microsoft.Storage/storageAccounts/write",
                    "Microsoft.Storage/storageAccounts/blobServices/containers/read",
                    "Microsoft.Storage/storageAccounts/listAccountSas/action",
                    "Microsoft.Storage/usages/read",
                    "Microsoft.Compute/snapshots/write",
                    "Microsoft.Compute/snapshots/read",
                    "Microsoft.Compute/availabilitySets/write",
                    "Microsoft.Compute/availabilitySets/read",
                    "Microsoft.Compute/disks/beginGetAccess/action",
                    "Microsoft.MarketplaceOrdering/offertypes/publishers/offers/plans/agreements/read",
                    "Microsoft.MarketplaceOrdering/offertypes/publishers/offers/plans/agreements/write",
                    "Microsoft.Network/loadBalancers/read",
                    "Microsoft.Network/loadBalancers/write",
                    "Microsoft.Network/loadBalancers/delete",
                    "Microsoft.Network/loadBalancers/backendAddressPools/read",
                    "Microsoft.Network/loadBalancers/backendAddressPools/join/action",
                    "Microsoft.Network/loadBalancers/loadBalancingRules/read",
                    "Microsoft.Network/loadBalancers/probes/read",
                    "Microsoft.Network/loadBalancers/probes/join/action",
                    "Microsoft.Authorization/locks/*",
                    "Microsoft.Network/routeTables/join/action",
                    "Microsoft.NetApp/netAppAccounts/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/write",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/delete",
                    "Microsoft.Network/privateEndpoints/write",
                    "Microsoft.Storage/storageAccounts/PrivateEndpointConnectionsApproval/action",
                    "Microsoft.Storage/storageAccounts/privateEndpointConnections/read",
                    "Microsoft.Storage/storageAccounts/managementPolicies/read",
                    "Microsoft.Storage/storageAccounts/managementPolicies/write",
                    "Microsoft.Network/privateEndpoints/read",
                    "Microsoft.Network/privateDnsZones/write",
                    "Microsoft.Network/privateDnsZones/virtualNetworkLinks/write",
                    "Microsoft.Network/virtualNetworks/join/action",
                    "Microsoft.Network/privateDnsZones/A/write",
                    "Microsoft.Network/privateDnsZones/read",
                    "Microsoft.Network/privateDnsZones/virtualNetworkLinks/read",
                    "Microsoft.Resources/deployments/operationStatuses/read",
                    "Microsoft.Insights/Metrics/Read",
                    "Microsoft.Compute/virtualMachines/extensions/write",
                    "Microsoft.Compute/virtualMachines/extensions/delete",
                    "Microsoft.Compute/virtualMachines/extensions/read",
                    "Microsoft.Compute/virtualMachines/delete",
                    "Microsoft.Network/networkInterfaces/delete",
                    "Microsoft.Network/networkSecurityGroups/delete",
                    "Microsoft.Resources/deployments/delete",
                    "Microsoft.Compute/diskEncryptionSets/read",
                    "Microsoft.Compute/snapshots/delete",
                    "Microsoft.Network/privateEndpoints/delete",
                    "Microsoft.Compute/availabilitySets/delete",
                    "Microsoft.KeyVault/vaults/read",
                    "Microsoft.KeyVault/vaults/accessPolicies/write",
                    "Microsoft.Compute/diskEncryptionSets/write",
                    "Microsoft.KeyVault/vaults/deploy/action",
                    "Microsoft.Compute/diskEncryptionSets/delete",
                    "Microsoft.Resources/tags/read",
                    "Microsoft.Resources/tags/write",
                    "Microsoft.Resources/tags/delete",
                    "Microsoft.Network/applicationSecurityGroups/write",
                    "Microsoft.Network/applicationSecurityGroups/read",
                    "Microsoft.Network/applicationSecurityGroups/joinIpConfiguration/action",
                    "Microsoft.Network/networkSecurityGroups/securityRules/write",
                    "Microsoft.Network/applicationSecurityGroups/delete",
                    "Microsoft.Network/networkSecurityGroups/securityRules/delete",
                    "Microsoft.ContainerService/managedClusters/listClusterUserCredential/action",
                    "Microsoft.ContainerService/managedClusters/read",
                    "Microsoft.Synapse/workspaces/write",
                    "Microsoft.Synapse/workspaces/read",
                    "Microsoft.Synapse/workspaces/delete",
                    "Microsoft.Synapse/register/action",
                    "Microsoft.Synapse/checkNameAvailability/action",
                    "Microsoft.Synapse/workspaces/operationStatuses/read",
                    "Microsoft.Synapse/workspaces/firewallRules/read",
                    "Microsoft.Synapse/workspaces/replaceAllIpFirewallRules/action",
                    "Microsoft.Synapse/workspaces/operationResults/read",
                    "Microsoft.Synapse/workspaces/privateEndpointConnectionsApproval/action",
                    "Microsoft.ManagedIdentity/userAssignedIdentities/assign/action",
                    "Microsoft.Compute/images/write",
                    "Microsoft.Network/loadBalancers/frontendIPConfigurations/read"
    ],
    "NotActions": [],
    "AssignableScopes": [],
    "Description": "BlueXP Permissions",
    "IsCustom": "true"
}
----


== Azure 사용 권한 사용 방법

다음 섹션에서는 각 BlueXP 서비스에 대한 사용 권한이 어떻게 사용되는지 설명합니다. 이 정보는 기업 정책에 따라 사용 권한이 필요한 경우에만 제공된다는 내용이 지정되어 있는 경우에 유용합니다.



=== Azure NetApp Files

BlueXP 분류를 사용하여 Azure NetApp Files 데이터를 스캔할 때 커넥터는 다음과 같은 API 요청을 합니다.

* Microsoft.NetApp/netAppAccounts/read
* Microsoft.NetApp/netAppAccounts/capacityPools/read
* Microsoft.NetApp/netAppAccounts/capacityPools/volumes/write
* Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read
* Microsoft.NetApp/netAppAccounts/capacityPools/volumes/delete




=== 백업 및 복구

Connector는 BlueXP 백업 및 복구를 위해 다음과 같은 API 요청을 수행합니다.

* Microsoft.Storage/storageAccounts/listkeys/action
* Microsoft.Storage/storageAccounts/read를 참조하십시오
* Microsoft.Storage/storageAccounts/write입니다
* Microsoft.Storage/storageAccounts/blobServices/containers/read
* Microsoft.Storage/storageAccounts/listAccountSas/action
* Microsoft.KeyVault/볼트/읽기
* Microsoft.KeyVault/vaults/accessPolicies/write
* Microsoft.Network/networkInterfaces/read
* Microsoft.Resources/서브스크립션/위치/읽기
* Microsoft.Network/virtualNetworks/read
* Microsoft.Network/virtualNetworks/subnets/read
* Microsoft.Resources/Subscriptions/resourceGroups/read
* Microsoft.Resources/Subscriptions/resourcegroups/resources/read
* Microsoft.Resources/Subscriptions/resourceGroups/write입니다
* Microsoft.인증/잠금/ *
* Microsoft.Network/privateEndpoints/write
* Microsoft.Network/privateEndpoints/read
* Microsoft.Network/privateDnsZones/virtualNetworkLinks/write
* Microsoft.Network/virtualNetworks/join/action
* Microsoft.Network/privateDnsZones/A/write
* Microsoft.Network/privateDnsZones/read
* Microsoft.Network/privateDnsZones/virtualNetworkLinks/read
* Microsoft.Network/networkInterfaces/delete
* Microsoft.Network/networkSecurityGroups/delete
* Microsoft.Resources/Deployments/Delete 를 참조하십시오
* Microsoft.ManagedIdentity/userAssignedIdentities/assign/action 을 참조하십시오


Connector는 검색 및 복원 기능을 사용할 때 다음과 같은 API 요청을 수행합니다.

* Microsoft.Synapse/작업 공간/쓰기
* Microsoft.Synapse/작업 공간/읽기
* Microsoft.Synapse/작업 공간/삭제
* Microsoft.Synapse/등록/조치
* Microsoft.Synapse/checkNameAvailability/action
* Microsoft.Synapse/작업 공간/작업 상태/읽기
* Microsoft.Synapse/작업 공간/firewallwules/read
* Microsoft.Synapse/작업 공간/교체 eAllIpFirewallRules/action
* Microsoft.Synapse/작업 공간/작업 결과/읽기
* Microsoft.Synapse/작업 공간/privateEndpointConnectionsApproval/action




=== 분류

Connector는 BlueXP 분류를 사용할 때 다음과 같은 API 요청을 수행합니다.

[cols="3*"]
|===
| 조치 | 설정에 사용됩니까? | 일상적 운영에 사용됩니까? 


| Microsoft.Compute/locations/operations/read | 예 | 예 


| Microsoft.Compute/locations/vmSizes/read | 예 | 예 


| Microsoft.Compute/operations/read | 예 | 예 


| Microsoft.Compute/virtualMachines/instanceView/read | 예 | 예 


| Microsoft.Compute/virtualMachines/powerOff/action | 예 | 아니요 


| Microsoft.Compute/virtualMachines/read | 예 | 예 


| Microsoft.Compute/virtualMachines/restart/action | 예 | 아니요 


| Microsoft.Compute/virtualMachines/start/action | 예 | 아니요 


| Microsoft.Compute/virtualMachines/vmSizes/read | 아니요 | 예 


| Microsoft.Compute/virtualMachines/write | 예 | 아니요 


| Microsoft.Compute/images/read | 예 | 예 


| Microsoft.Compute/disks/delete | 예 | 아니요 


| Microsoft.Compute/disks/read | 예 | 예 


| Microsoft.Compute/disks/write | 예 | 아니요 


| Microsoft.Storage/CheckknameAvailability/read | 예 | 예 


| Microsoft.스토리지/작업/읽기 | 예 | 예 


| Microsoft.Storage/storageAccounts/listkeys/action | 예 | 아니요 


| Microsoft.Storage/storageAccounts/read를 참조하십시오 | 예 | 예 


| Microsoft.Storage/storageAccounts/write입니다 | 예 | 아니요 


| Microsoft.Storage/storageAccounts/blobServices/containers/read | 예 | 예 


| Microsoft.Network/networkInterfaces/read | 예 | 예 


| Microsoft.Network/networkInterfaces/write | 예 | 아니요 


| Microsoft.Network/networkInterfaces/join/action | 예 | 아니요 


| Microsoft.Network/networkSecurityGroups/read | 예 | 예 


| Microsoft.Network/networkSecurityGroups/write | 예 | 아니요 


| Microsoft.Resources/서브스크립션/위치/읽기 | 예 | 예 


| Microsoft.Network/locations/operationResults/read | 예 | 예 


| Microsoft.Network/locations/operations/read | 예 | 예 


| Microsoft.Network/virtualNetworks/read | 예 | 예 


| Microsoft.Network/virtualNetworks/checkIpAddressAvailability/read | 예 | 예 


| Microsoft.Network/virtualNetworks/subnets/read | 예 | 예 


| Microsoft.Network/virtualNetworks/subnets/virtualMachines/read | 예 | 예 


| Microsoft.Network/virtualNetworks/virtualMachines/read | 예 | 예 


| Microsoft.Network/virtualNetworks/subnets/join/action | 예 | 아니요 


| Microsoft.Network/virtualNetworks/subnets/write | 예 | 아니요 


| Microsoft.Network/routeTables/join/action | 예 | 아니요 


| Microsoft.Resources/Deployments/Operations/Read 를 참조하십시오 | 예 | 예 


| Microsoft.Resources/Deployments/Read 를 참조하십시오 | 예 | 예 


| Microsoft.Resources/Deployments/Write 를 참조하십시오 | 예 | 아니요 


| Microsoft.Resources/resources/read | 예 | 예 


| Microsoft.Resources/서브스크립션/운영 결과/읽기 | 예 | 예 


| Microsoft.Resources/Subscriptions/resourceGroups/delete | 예 | 아니요 


| Microsoft.Resources/Subscriptions/resourceGroups/read | 예 | 예 


| Microsoft.Resources/Subscriptions/resourcegroups/resources/read | 예 | 예 


| Microsoft.Resources/Subscriptions/resourceGroups/write입니다 | 예 | 아니요 
|===


=== Cloud Volumes ONTAP

Connector는 Azure에서 Cloud Volumes ONTAP를 배포 및 관리하기 위해 다음과 같은 API 요청을 수행합니다.

[cols="5*"]
|===
| 목적 | 조치 | 배포에 사용되었습니까? | 일상적 운영에 사용됩니까? | 삭제에 사용되었습니까? 


.14+| VM을 생성하고 관리합니다 | Microsoft.Compute/locations/operations/read | 예 | 예 | 아니요 


| Microsoft.Compute/locations/vmSizes/read | 예 | 예 | 아니요 


| Microsoft.Resources/서브스크립션/위치/읽기 | 예 | 아니요 | 아니요 


| Microsoft.Compute/operations/read | 예 | 예 | 아니요 


| Microsoft.Compute/virtualMachines/instanceView/read | 예 | 예 | 아니요 


| Microsoft.Compute/virtualMachines/powerOff/action | 예 | 예 | 아니요 


| Microsoft.Compute/virtualMachines/read | 예 | 예 | 아니요 


| Microsoft.Compute/virtualMachines/restart/action | 예 | 예 | 아니요 


| Microsoft.Compute/virtualMachines/start/action | 예 | 예 | 아니요 


| Microsoft.Compute/virtualMachines/deallocate/action | 아니요 | 예 | 예 


| Microsoft.Compute/virtualMachines/vmSizes/read | 아니요 | 예 | 아니요 


| Microsoft.Compute/virtualMachines/write | 예 | 예 | 아니요 


| Microsoft.Compute/virtualMachines/delete | 예 | 예 | 예 


| Microsoft.Resources/Deployments/Delete 를 참조하십시오 | 예 | 아니요 | 아니요 


.2+| VHD에서 배포를 활성화합니다 | Microsoft.Compute/images/read | 예 | 아니요 | 아니요 


| Microsoft.Compute/images/write | 예 | 아니요 | 아니요 


.4+| 대상 서브넷에서 네트워크 인터페이스를 생성하고 관리합니다 | Microsoft.Network/networkInterfaces/read | 예 | 예 | 아니요 


| Microsoft.Network/networkInterfaces/write | 예 | 예 | 아니요 


| Microsoft.Network/networkInterfaces/join/action | 예 | 예 | 아니요 


| Microsoft.Network/networkInterfaces/delete | 예 | 예 | 아니요 


.4+| 네트워크 보안 그룹을 만들고 관리합니다 | Microsoft.Network/networkSecurityGroups/read | 예 | 예 | 아니요 


| Microsoft.Network/networkSecurityGroups/write | 예 | 예 | 아니요 


| Microsoft.Network/networkSecurityGroups/join/action | 예 | 아니요 | 아니요 


| Microsoft.Network/networkSecurityGroups/delete | 아니요 | 예 | 예 


.8+| 지역, 대상 VNET 및 서브넷에 대한 네트워크 정보를 얻고 VM을 VNets에 추가합니다 | Microsoft.Network/locations/operationResults/read | 예 | 예 | 아니요 


| Microsoft.Network/locations/operations/read | 예 | 예 | 아니요 


| Microsoft.Network/virtualNetworks/read | 예 | 아니요 | 아니요 


| Microsoft.Network/virtualNetworks/checkIpAddressAvailability/read | 예 | 아니요 | 아니요 


| Microsoft.Network/virtualNetworks/subnets/read | 예 | 예 | 아니요 


| Microsoft.Network/virtualNetworks/subnets/virtualMachines/read | 예 | 예 | 아니요 


| Microsoft.Network/virtualNetworks/virtualMachines/read | 예 | 예 | 아니요 


| Microsoft.Network/virtualNetworks/subnets/join/action | 예 | 예 | 아니요 


.9+| 자원 그룹을 만들고 관리합니다 | Microsoft.Resources/Deployments/Operations/Read 를 참조하십시오 | 예 | 예 | 아니요 


| Microsoft.Resources/Deployments/Read 를 참조하십시오 | 예 | 예 | 아니요 


| Microsoft.Resources/Deployments/Write 를 참조하십시오 | 예 | 예 | 아니요 


| Microsoft.Resources/resources/read | 예 | 예 | 아니요 


| Microsoft.Resources/서브스크립션/운영 결과/읽기 | 예 | 예 | 아니요 


| Microsoft.Resources/Subscriptions/resourceGroups/delete | 예 | 예 | 예 


| Microsoft.Resources/Subscriptions/resourceGroups/read | 아니요 | 예 | 아니요 


| Microsoft.Resources/Subscriptions/resourcegroups/resources/read | 예 | 예 | 아니요 


| Microsoft.Resources/Subscriptions/resourceGroups/write입니다 | 예 | 예 | 아니요 


.10+| Azure 스토리지 계정 및 디스크를 관리합니다 | Microsoft.Compute/disks/read | 예 | 예 | 예 


| Microsoft.Compute/disks/write | 예 | 예 | 아니요 


| Microsoft.Compute/disks/delete | 예 | 예 | 예 


| Microsoft.Storage/CheckknameAvailability/read | 예 | 예 | 아니요 


| Microsoft.스토리지/작업/읽기 | 예 | 예 | 아니요 


| Microsoft.Storage/storageAccounts/listkeys/action | 예 | 예 | 아니요 


| Microsoft.Storage/storageAccounts/read를 참조하십시오 | 예 | 예 | 아니요 


| Microsoft.Storage/storageAccounts/delete | 아니요 | 예 | 예 


| Microsoft.Storage/storageAccounts/write입니다 | 예 | 예 | 아니요 


| Microsoft.스토리지/용도/읽기 | 아니요 | 예 | 아니요 


.3+| Blob 저장소로 백업 및 스토리지 계정 암호화 지원 | Microsoft.Storage/storageAccounts/blobServices/containers/read | 예 | 예 | 아니요 


| Microsoft.KeyVault/볼트/읽기 | 예 | 예 | 아니요 


| Microsoft.KeyVault/vaults/accessPolicies/write | 예 | 예 | 아니요 


.2+| 데이터 계층화를 위해 VNET 서비스 엔드포인트를 활성화합니다 | Microsoft.Network/virtualNetworks/subnets/write | 예 | 예 | 아니요 


| Microsoft.Network/routeTables/join/action | 예 | 예 | 아니요 


.4+| Azure 관리 스냅샷을 생성하고 관리합니다 | Microsoft.Compute/snapshots/write | 예 | 예 | 아니요 


| Microsoft.Compute/snapshots/read | 예 | 예 | 아니요 


| Microsoft.Compute/snapshots/delete | 아니요 | 예 | 예 


| Microsoft.Compute/disks/beginGetAccess/action | 아니요 | 예 | 아니요 


.2+| 가용성 세트 생성 및 관리 | Microsoft.Compute/availabilitySets/write | 예 | 아니요 | 아니요 


| Microsoft.Compute/availabilitySets/read | 예 | 아니요 | 아니요 


.2+| 시장에서 프로그래밍 방식으로 배포할 수 있습니다 | Microsoft.MarketplaceOrdering/offerstypes/publishers/Offers/Plans/Agreement/read | 예 | 아니요 | 아니요 


| Microsoft.MarketplaceOrdering/offersTypes/publishers/Offers/Plans/Agreement/write | 예 | 예 | 아니요 


.9+| HA 쌍에 대한 로드 밸런서를 관리합니다 | Microsoft.Network/loadBalancers/read | 예 | 예 | 아니요 


| Microsoft.Network/loadBalancers/write | 예 | 아니요 | 아니요 


| Microsoft.Network/loadBalancers/delete | 아니요 | 예 | 예 


| Microsoft.Network/loadBalancers/backendAddressPools/read | 예 | 아니요 | 아니요 


| Microsoft.Network/loadBalancers/backendAddressPools/join/action | 예 | 아니요 | 아니요 


| Microsoft.Network/loadBalancers/frontendIPConfigurations/read | 예 | 예 | 아니요 


| Microsoft.Network/loadBalancers/loadBalancingRules/read | 예 | 아니요 | 아니요 


| Microsoft.Network/loadBalancers/probes/read | 예 | 아니요 | 아니요 


| Microsoft.Network/loadBalancers/probes/join/action | 예 | 아니요 | 아니요 


| Azure 디스크에서 잠금 관리를 활성화합니다 | Microsoft.인증/잠금/ * | 예 | 예 | 아니요 


.10+| 서브넷 외부에 연결이 없는 경우 HA 쌍에 대한 개인 끝점을 설정합니다 | Microsoft.Network/privateEndpoints/write | 예 | 예 | 아니요 


| Microsoft.Storage/storageAccounts/PrivateEndpointConnectionsApproval/action 을 참조하십시오 | 예 | 아니요 | 아니요 


| Microsoft.Storage/storageAccounts/privateEndpointConnections/read | 예 | 예 | 예 


| Microsoft.Network/privateEndpoints/read | 예 | 예 | 예 


| Microsoft.Network/privateDnsZones/write | 예 | 예 | 아니요 


| Microsoft.Network/privateDnsZones/virtualNetworkLinks/write | 예 | 예 | 아니요 


| Microsoft.Network/virtualNetworks/join/action | 예 | 예 | 아니요 


| Microsoft.Network/privateDnsZones/A/write | 예 | 예 | 아니요 


| Microsoft.Network/privateDnsZones/read | 예 | 예 | 아니요 


| Microsoft.Network/privateDnsZones/virtualNetworkLinks/read | 예 | 예 | 아니요 


| 기본 물리적 하드웨어에 따라 일부 VM 배포에 필요합니다 | Microsoft.Resources/Deployments/operationStates/read 를 참조하십시오 | 예 | 예 | 아니요 


.2+| 배포 실패 또는 삭제 시 리소스 그룹에서 리소스를 제거합니다 | Microsoft.Network/privateEndpoints/delete | 예 | 예 | 아니요 


| Microsoft.Compute/availabilitySets/delete | 예 | 예 | 아니요 


.4+| API를 사용할 때 고객이 관리하는 암호화 키를 사용할 수 있도록 설정합니다 | Microsoft.Compute/diskEncryptionSets/read | 예 | 예 | 예 


| Microsoft.Compute/diskEncryptionSets/write | 예 | 예 | 아니요 


| Microsoft.KeyVault/볼트/배포/작업 | 예 | 아니요 | 아니요 


| Microsoft.Compute/diskEncryptionSets/delete | 예 | 예 | 예 


.6+| HA 인터커넥트 및 클러스터 네트워크 NIC를 격리하도록 HA 쌍에 대한 애플리케이션 보안 그룹을 구성합니다 | Microsoft.Network/applicationSecurityGroups/write | 아니요 | 예 | 아니요 


| Microsoft.Network/applicationSecurityGroups/read | 아니요 | 예 | 아니요 


| Microsoft.Network/applicationSecurityGroups/joinIpConfiguration/action | 아니요 | 예 | 아니요 


| Microsoft.Network/networkSecurityGroups/securityRules/write | 예 | 예 | 아니요 


| Microsoft.Network/applicationSecurityGroups/delete | 아니요 | 예 | 예 


| Microsoft.Network/networkSecurityGroups/securityRules/delete | 아니요 | 예 | 예 


.3+| Cloud Volumes ONTAP 리소스와 연결된 태그를 읽고, 쓰고, 삭제합니다 | Microsoft.Resources/tags/read | 아니요 | 예 | 아니요 


| Microsoft.Resources/tags/write(Microsoft.리소스/태그/쓰기 | 예 | 예 | 아니요 


| Microsoft.Resources/tags/delete(Microsoft.리소스/태그/삭제 | 예 | 아니요 | 아니요 


| 생성 중에 스토리지 계정을 암호화합니다 | Microsoft.ManagedIdentity/userAssignedIdentities/assign/action 을 참조하십시오 | 예 | 예 | 아니요 
|===


=== 에지 캐싱

Connector는 BlueXP 에지 캐싱을 사용할 때 다음과 같은 API 요청을 수행합니다.

* Microsoft.Insights/메트릭/읽기
* Microsoft.Compute/virtualMachines/extensions/write
* Microsoft.Compute/virtualMachines/extensions/read
* Microsoft.Compute/virtualMachines/extensions/delete
* Microsoft.Compute/virtualMachines/delete
* Microsoft.Network/networkInterfaces/delete
* Microsoft.Network/networkSecurityGroups/delete
* Microsoft.Resources/Deployments/Delete 를 참조하십시오




=== 쿠버네티스

Connector는 Azure Kubernetes Service(AKS)에서 실행 중인 클러스터를 검색하고 관리하기 위해 다음과 같은 API 요청을 수행합니다.

* Microsoft.Compute/virtualMachines/read
* Microsoft.Resources/서브스크립션/위치/읽기
* Microsoft.Resources/서브스크립션/운영 결과/읽기
* Microsoft.Resources/Subscriptions/resourceGroups/read
* Microsoft.Resources/Subscriptions/resourcegroups/resources/read
* Microsoft.ContainerService/managedClusters/read
* Microsoft.ContainerService/managedClusters/listClusterUserCredential/action입니다




=== 해결

Connector는 BlueXP 개선 기능을 사용할 때 Azure 리소스의 태그를 관리하기 위해 다음과 같은 API 요청을 수행합니다.

* Microsoft.Resources/resources/read
* Microsoft.Resources/서브스크립션/운영 결과/읽기
* Microsoft.Resources/Subscriptions/resourceGroups/read
* Microsoft.Resources/Subscriptions/resourcegroups/resources/read
* Microsoft.Resources/tags/read
* Microsoft.Resources/tags/write(Microsoft.리소스/태그/쓰기




=== 계층화

Connector는 BlueXP 계층화를 설정할 때 다음과 같은 API 요청을 수행합니다.

* Microsoft.Storage/storageAccounts/listkeys/action
* Microsoft.Resources/Subscriptions/resourceGroups/read
* Microsoft.Resources/서브스크립션/위치/읽기


Connector는 일상적인 작업에 대해 다음과 같은 API 요청을 수행합니다.

* Microsoft.Storage/storageAccounts/blobServices/containers/read
* Microsoft.Storage/storageAccounts/managementPolicies/read를 참조하십시오
* Microsoft.Storage/storageAccounts/managementPolicies/write를 참조하십시오
* Microsoft.Storage/storageAccounts/read를 참조하십시오




== 변경 로그

권한이 추가되고 제거됨에 따라 아래 섹션에 해당 권한이 표시됩니다.



=== 2023년 12월 5일

볼륨 데이터를 Azure Blob 스토리지에 백업할 때 BlueXP 백업 및 복구에 더 이상 다음 권한이 필요하지 않습니다.

* Microsoft.Compute/virtualMachines/read
* Microsoft.Compute/virtualMachines/start/action
* Microsoft.Compute/virtualMachines/deallocate/action
* Microsoft.Compute/virtualMachines/extensions/delete
* Microsoft.Compute/virtualMachines/delete


이러한 권한은 다른 BlueXP 스토리지 서비스에 필요하므로 다른 스토리지 서비스를 사용하는 경우에도 Connector의 사용자 지정 역할이 유지됩니다.



=== 2023년 5월 12일

JSON 정책에는 Cloud Volumes ONTAP 관리에 필요한 다음과 같은 권한이 추가되었습니다.

* Microsoft.Compute/images/write
* Microsoft.Network/loadBalancers/frontendIPConfigurations/read


다음 권한은 더 이상 필요하지 않으므로 JSON 정책에서 제거되었습니다.

* Microsoft.Storage/storageAccounts/blobServices/containers/write
* Microsoft.Network/publicIPAddresses/delete




=== 2023년 3월 23일

BlueXP 분류에는 "Microsoft.Storage/storageAccounts/delete" 권한이 더 이상 필요하지 않습니다.

이 권한은 Cloud Volumes ONTAP에 여전히 필요합니다.



=== 2023년 1월 5일

JSON 정책에 다음 권한이 추가되었습니다.

* Microsoft.Storage/storageAccounts/listAccountSas/action
* Microsoft.Synapse/작업 공간/privateEndpointConnectionsApproval/action
+
이러한 권한은 BlueXP 백업 및 복구에 필요합니다.

* Microsoft.Network/loadBalancers/backendAddressPools/join/action
+
이 권한은 Cloud Volumes ONTAP 배포에 필요합니다.


