---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, BlueXP, Cloud Volumes ONTAP, days, running, Connectors should remain running, imdsv2, httpstokens 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오. 
---
= 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.

커넥터, SaaS(Software as a Service) 플랫폼 등 BlueXP  설정 및 관리에 따라 달라집니다.



== 커넥터 제한



=== 투명 프록시 서버는 지원되지 않습니다

BlueXP는 Connector를 통해 투명한 프록시 서버를 지원하지 않습니다.

link:task-configuring-proxy.html["커넥터를 사용하여 프록시 서버를 사용하는 방법에 대해 자세히 알아보십시오"].



=== 172 범위의 IP 주소와 충돌할 수 있습니다

BlueXP는 172.17.0.0/16 및 172.18.0.0/16 범위의 IP 주소를 가진 두 개의 인터페이스로 커넥터를 배포합니다.

네트워크에 이러한 범위 중 하나로 구성된 서브넷이 있는 경우 BlueXP에서 연결 오류가 발생할 수 있습니다. 예를 들어, BlueXP에서 온프레미스 ONTAP 클러스터를 검색하지 못할 수 있습니다.

기술 자료 문서를 참조하십시오 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["BlueXP 커넥터 IP가 기존 네트워크와 충돌합니다"] 커넥터 인터페이스의 IP 주소를 변경하는 방법에 대한 지침은 을 참조하십시오.



=== SSL 암호 해독은 지원되지 않습니다

BlueXP는 SSL 암호 해독이 활성화된 방화벽 구성을 지원하지 않습니다. SSL 암호 해독이 활성화된 경우 오류 메시지가 BlueXP에 나타나고 Connector 인스턴스가 비활성으로 표시됩니다.

보안 강화를 위해 을(를) 선택할 수 있습니다 link:task-installing-https-cert.html["CA(인증 기관)에서 서명한 HTTPS 인증서 설치"].



=== 로컬 UI를 로드할 때 빈 페이지입니다

Connector에서 실행 중인 웹 기반 콘솔을 로드하는 경우 인터페이스가 표시되지 않을 수 있으며 빈 페이지가 표시될 수도 있습니다.

이 문제는 캐싱 문제와 관련이 있습니다. 해결 방법은 익명 또는 개인 웹 브라우저 세션을 사용하는 것입니다.



=== 공유 Linux 호스트는 지원되지 않습니다

Connector는 다른 애플리케이션과 공유되는 VM에서 지원되지 않습니다. VM은 Connector 소프트웨어 전용이어야 합니다.



=== 타사 에이전트 및 내선 번호

타사 에이전트 또는 VM 확장은 커넥터 VM에서 지원되지 않습니다.
