---
sidebar: sidebar 
permalink: reference-user-roles.html 
keywords: user, users, roles, role, task, permission, permissions, tasks, admin, Account Admin, Workspace Admin, Cloud Compliance Viewer, Cloud Data Sense, SnapCenter Admin 
summary: 계정 관리자, 작업 영역 관리자, 규정 준수 뷰어 및 SnapCenter 관리자 역할은 사용자에게 특정 권한을 제공합니다. 새 사용자를 BlueXP 계정에 연결할 때 이러한 역할 중 하나를 할당할 수 있습니다. 
---
= 사용자 역할
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
비공개 모드에서 BlueXP 를 사용하는 경우 _BlueXP  계정 _ 을(를) 사용하여 사용자를 관리합니다. 계정 관리자, 작업 영역 관리자, 규정 준수 뷰어 및 SnapCenter 관리자 역할 중에서 선택하여 계정의 사용자에게 특정 권한을 제공할 수 있습니다.


NOTE: 2025년 2월부터 이러한 사용자 역할은 표준 및 제한된 배포 모드에 대해 더 이상 사용되지 않습니다. BlueXP  개인 모드는 모든 BlueXP  권한을 부여하는 Cloud Manager 관리자 역할인 사용자와 연결할 하나의 역할만 제공합니다.

표준 모드 또는 제한 모드에서 BlueXP 를 사용하는 경우 BlueXP  계정이 없습니다. 대신 BlueXP  ID 및 액세스 관리(IAM)를 사용하여 관리하는 _BlueXP  조직_ 이 있습니다.

* link:concept-identity-and-access-management.html["BlueXP  IAM에 대해 알아보십시오"]
* link:concept-modes.html["BlueXP 배포 모드에 대해 알아보십시오"]


[cols="24,19,19,19,19"]
|===
| 작업 | 계정 관리자 | 작업 영역 관리자 | 규정 준수 뷰어 | SnapCenter 관리자 


| 커넥터 작성 | 예 | 아니요 | 아니요 | 아니요 


| 작업 환경 관리 | 예 | 예 | 아니요 | 예 


| 작업 환경에 대한 서비스를 활성화합니다 | 예 | 예 | 아니요 | 예 


| BlueXP  서비스 사용 | 예 | 예 | 아니요 | 예 


| 작업 영역에서 작업 환경을 제거합니다 | 예 | 예 | 아니요 | 아니요 


| 작업 환경을 삭제합니다 | 예 | 예 | 아니요 | 아니요 


| 데이터 복제 상태를 봅니다 | 예 | 예 | 아니요 | 아니요 


| 타임라인을 봅니다 | 예 | 예 | 아니요 | 아니요 


| 작업 공간 간 전환 | 예 | 예 | 예 | 예 


| BlueXP 분류 검사 결과를 봅니다 | 예 | 예 | 예 | 아니요 


| Cloud Volumes ONTAP 보고서를 받습니다 | 예 | 아니요 | 아니요 | 아니요 


| BlueXP 계정을 관리합니다 | 예 | 아니요 | 아니요 | 아니요 


| 자격 증명 관리 | 예 | 예 | 아니요 | 아니요 


| BlueXP 설정을 수정합니다 | 예 | 예 | 아니요 | 아니요 


| 지원 대시보드 보기 및 관리 | 예 | 예 | 아니요 | 아니요 
|===
.관련 정보
link:task-managing-netapp-accounts.html["BlueXP 계정을 관리합니다"]
