---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP 에서 관리 작업을 수행할 수 있는 권한을 부여하기 위해 사용자에게 플랫폼 역할을 할당하고, 역할을 할당하고, 사용자를 추가하고, 커넥터를 만들고, 페더레이션을 관리합니다. 
---
= BlueXP  플랫폼 액세스 역할
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 에서 관리 작업을 수행할 수 있는 권한을 부여하기 위해 사용자에게 플랫폼 역할을 할당하고, 역할을 할당하고, 사용자를 추가하고, 커넥터를 만들고, 페더레이션을 관리합니다.

.대규모 다국적 조직에 대한 BlueXP 의 조직 역할의 예
XYZ Corporation은 북미, 유럽, 아시아 태평양 등 지역별로 데이터 저장소 액세스를 구성하여 중앙 집중식 감독을 통해 지역적 제어를 제공합니다.

XYZ Corporation의 BlueXP 에 있는 *조직 관리자*는 각 지역에 대한 초기 조직과 별도 폴더를 만듭니다.  각 지역의 *폴더 또는 프로젝트 관리자*는 해당 지역의 폴더 내에서 프로젝트(관련 리소스 포함)를 구성합니다.

*폴더 또는 프로젝트 관리자* 역할을 맡은 지역 관리자는 리소스와 사용자를 추가하여 폴더를 적극적으로 관리합니다.  이러한 지역 관리자는 자신이 관리하는 폴더와 프로젝트를 추가, 제거 또는 이름을 바꿀 수도 있습니다.  *조직 관리자*는 모든 새 리소스에 대한 권한을 상속받아 조직 전체의 저장소 사용량을 파악할 수 있습니다.

동일한 조직 내에서 한 명의 사용자에게 회사 IdP와의 조직 연합을 관리하는 *연합 관리자* 역할이 할당됩니다.  이 사용자는 연합 조직을 추가하거나 제거할 수 있지만, 조직 내의 사용자나 리소스를 관리할 수는 없습니다.  *조직 관리자*는 사용자에게 *연합 뷰어* 역할을 할당하여 연합 상태를 확인하고 연합 조직을 볼 수 있도록 합니다.

다음 표는 각 BlueXP 플랫폼 역할이 수행할 수 있는 작업을 나타냅니다.



== 조직 관리 역할

[cols="2,1,1"]
|===
| 작업 | 조직 관리자 | 폴더 또는 프로젝트 관리자 


| 커넥터 작성 | 예 | 아니요 


| 작업 환경 생성, 수정 또는 삭제(BlueXP  Canvas를 사용하여 새 리소스 추가 또는 검색) | 예 | 예 


| 삭제를 포함하여 폴더와 프로젝트를 작성합니다 | 예 | 아니요 


| 기존 폴더와 프로젝트의 이름을 바꿉니다 | 예 | 예 


| 역할을 할당하고 사용자를 추가합니다 | 예 | 예 


| 자원을 폴더 및 프로젝트와 연결합니다 | 예 | 예 


| 커넥터를 폴더 및 프로젝트와 연결합니다 | 예 | 아니요 


| 폴더 및 프로젝트에서 커넥터를 제거합니다 | 예 | 아니요 


| 커넥터 관리(인증서, 설정 등 편집) | 예 | 아니요 


| 설정 > 자격 증명에서 자격 증명을 관리합니다 | 예 | 예 


| 연합을 생성, 관리 및 보기 | 예 | 아니요 


| BlueXP 를 통해 지원을 등록하고 사례를 제출하세요 | 예 | 예 


| 데이터 서비스를 이용하세요 | 예 | 예 


| BlueXP 타임라인 및 알림 보기 | 예 | 예 
|===


== 연방 역할

[cols="2,1,1"]
|===
| 작업 | 연방 관리자 | 연방 뷰어 


| 연방을 만드세요 | 예 | 아니요 


| 도메인 확인 | 예 | 아니요 


| 페더레이션에 도메인 추가 | 예 | 아니요 


| 페더레이션 비활성화 및 삭제 | 예 | 아니요 


| 테스트 연합 | 예 | 아니요 


| 연합 및 해당 세부 정보 보기 | 예 | 예 
|===