---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: SaaS 계층을 통해 제공되는 BlueXP 웹 기반 콘솔을 사용할 때 몇 가지 관리 작업을 완료하면 여러 개의 엔드포인트에 연결됩니다. BlueXP 콘솔에 액세스하는 컴퓨터는 이러한 엔드포인트에 연결해야 합니다. 
---
= BlueXP 콘솔을 사용하기 위한 네트워킹을 준비합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SaaS 계층을 통해 제공되는 BlueXP 웹 기반 콘솔을 사용할 때 몇 가지 관리 작업을 완료하면 여러 개의 엔드포인트에 연결됩니다. BlueXP 콘솔에 액세스하는 컴퓨터는 이러한 엔드포인트에 연결해야 합니다.

이러한 엔드포인트는 BlueXP 콘솔에서 특정 작업을 완료할 때 사용자 컴퓨터에서 연결됩니다. 커넥터 및 특정 BlueXP 서비스의 네트워킹 요구사항도 참조해야 합니다. 자세한 내용은 이 페이지 끝에 있는 관련 링크를 참조하십시오.

[cols="2*"]
|===
| 엔드포인트 | 목적 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | 웹 브라우저는 BlueXP 웹 기반 콘솔을 사용할 때 이러한 URL에 연락합니다. 


| \https://aiq.netapp.com | BlueXP 디지털 어드바이저에 액세스하기 위해 필요합니다. 


 a| 
AWS 서비스(amazonaws.com):

* CloudFormation 을 참조하십시오
* EC2(탄력적인 컴퓨팅 클라우드)
* 키 관리 서비스(KMS)
* 보안 토큰 서비스(STS)
* S3(Simple Storage Service)

| AWS의 BlueXP에서 커넥터를 구축하는 데 필요합니다. 정확한 끝점은 Connector를 배포하는 영역에 따라 다릅니다. https://docs.aws.amazon.com/general/latest/gr/rande.html["자세한 내용은 AWS 설명서를 참조하십시오."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | 대부분의 Azure 지역에서 BlueXP의 커넥터를 배포하는 데 필요합니다. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Azure 독일 지역의 BlueXP에서 커넥터를 배포하는 데 필요합니다. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Azure US Gov 지역의 BlueXP에서 커넥터를 배포하는 데 필요합니다. 


| \https://www.googleapis.com | Google Cloud의 BlueXP에서 커넥터를 배포하는 데 필요합니다. 


| \https://signin.b2c.netapp.com | NetApp Support 사이트(NSS) 자격 증명을 업데이트하거나 BlueXP에 새 NSS 자격 증명을 추가하는 데 필요합니다. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | 웹 브라우저는 BlueXP를 통한 중앙 집중식 사용자 인증을 위해 이러한 엔드포인트에 연결됩니다. 


| \https://widget.intercom.io | 제품 내에서 NetApp 클라우드 전문가와 상담할 수 있는 채팅을 제공합니다. 
|===
이러한 엔드포인트 외에도, Connector가 일상적인 작업을 위해 특정 엔드포인트에 대한 아웃바운드 인터넷 액세스를 가지고 있는지 확인해야 합니다. 아래 다음 섹션의 링크를 따라 이러한 끝점 목록을 찾을 수 있습니다.

.관련 링크
* 커넥터를 위한 네트워킹을 준비합니다
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["AWS 네트워킹 설정"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Azure 네트워킹을 설정합니다"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Google Cloud 네트워킹을 설정합니다"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["사내 네트워킹을 설정합니다"]


* BlueXP 서비스를 위한 네트워킹을 준비합니다
+
각 BlueXP 서비스에 대한 문서를 참조하십시오.

+
https://docs.netapp.com/us-en/bluexp-family/["BlueXP 설명서"^]


