---
sidebar: sidebar 
permalink: reference-host-requirements-google.html 
keywords: cpu requirements, ram requirements, google cloud requirements, google cloud host requirements, connector host requirements, gcp machine type, machine type 
summary: Connector 소프트웨어는 특정 운영 체제 요구 사항, RAM 요구 사항, 포트 요구 사항 등을 충족하는 호스트에서 실행되어야 합니다. 커넥터를 수동으로 설치하려는 경우 호스트가 이러한 요구 사항을 충족하는지 확인해야 합니다. 커넥터를 설치하기 전에 호스트가 이러한 요구 사항을 충족하는지 확인하십시오. 
---
= Google Cloud 설치에 대한 커넥터 호스트 요구 사항을 검토합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Connector 소프트웨어는 특정 운영 체제 요구 사항, RAM 요구 사항, 포트 요구 사항 등을 충족하는 호스트에서 실행되어야 합니다. 커넥터를 수동으로 설치하려는 경우 호스트가 이러한 요구 사항을 충족하는지 확인해야 합니다.

BlueXP에서 커넥터를 배포하거나 glcoud를 사용하여 커넥터를 배포하는 경우 이미지에 필요한 OS 및 소프트웨어 구성 요소가 포함됩니다.

전용 호스트:: 다른 애플리케이션과 공유되는 호스트에서는 Connector가 지원되지 않습니다. 호스트는 전용 호스트여야 합니다.
지원되는 운영 체제::
+
--
* CentOS 7.6, 7.7, 7.8 및 7.9
* Red Hat Enterprise Linux 7.6, 7.7, 7.8, 7.9, 8.6, 8.7로 표시됩니다
+
호스트는 Red Hat Subscription Management에 등록되어 있어야 합니다. 등록되지 않은 경우 호스트는 Connector 설치 중에 필요한 타사 소프트웨어를 업데이트하기 위해 리포지토리에 액세스할 수 없습니다.

+
Connector는 이러한 운영 체제의 영어 버전에서 지원됩니다.



--
하이퍼바이저:: CentOS 또는 Red Hat Enterprise Linux 실행 인증을 받은 베어 메탈 또는 호스팅된 하이퍼바이저가 필요합니다. https://access.redhat.com/certified-hypervisors["Red Hat 솔루션: Red Hat Enterprise Linux 실행 인증을 받은 하이퍼바이저는 무엇입니까?"^]
CPU:: 코어 4개 또는 vCPU 4개
RAM:: 14GB
Google Cloud 컴퓨터 유형입니다:: 위의 CPU 및 RAM 요구 사항을 충족하는 인스턴스 유형입니다. n2-standard-4를 추천합니다.
+
--
Connector는 를 지원하는 OS가 있는 VM 인스턴스의 Google Cloud에서 지원됩니다 https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["차폐된 VM 기능"^]

--
/opt의 디스크 공간입니다:: 100GiB의 공간을 사용할 수 있어야 합니다
/var의 디스크 공간입니다:: 20GiB의 공간을 사용할 수 있어야 합니다
Docker 엔진:: 커넥터를 설치하기 전에 호스트에 Docker Engine 버전 19.3.1 이상이 필요합니다. https://docs.docker.com/engine/install/["설치 지침을 봅니다"^]

