---
sidebar: sidebar 
permalink: reference-iam-storage-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin 
summary: BlueXP  ID 및 액세스 관리는 조직의 구성원에게 할당할 수 있는 두 가지 관리 역할을 제공합니다. 
---
= BlueXP 에 대한 스토리지 액세스 역할
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
지원되는 스토리지 리소스와 연결된 BlueXP 의 스토리지 관리 기능에 대한 액세스 권한을 사용자에게 제공하기 위해 다음 역할을 할당할 수 있습니다. 사용자에게 저장소를 관리하는 관리자 역할이나 모니터링을 위한 뷰어 역할을 할당할 수 있습니다.


NOTE: 이러한 역할은 BlueXP 파트너십 API에서 사용할 수 없습니다.

관리자는 다음과 같은 스토리지 리소스 및 기능에 대해 사용자에게 스토리지 역할을 할당할 수 있습니다.

스토리지 리소스:

* 온프레미스 ONTAP 클러스터
* StorageGRID
* E-Series 를 참조하십시오


BlueXP  서비스 및 기능:

* 디지털 자문업체
* 소프트웨어 업데이트
* 경제적인 효율성
* 지속 가능성


.BlueXP 의 스토리지 역할에 대한 예
XYZ Corporation은 다국적 기업이며 스토리지 엔지니어와 스토리지 관리자로 구성된 대규모 팀을 운영하고 있습니다. 이를 통해 팀은 사용자 관리, 커넥터 생성, 디지털 지갑과 같은 비용 도구와 같은 핵심 BlueXP 작업에 대한 액세스를 제한하는 동시에 해당 지역의 스토리지 자산을 관리할 수 있습니다.

12명으로 구성된 팀 내에서 두 명의 사용자에게 * 스토리지 뷰어 * 역할이 부여되어 할당된 BlueXP  프로젝트와 관련된 스토리지 리소스를 모니터링할 수 있습니다. 나머지 9개 항목에는 소프트웨어 업데이트 관리, BlueXP 를 통한 ONTAP 시스템 관리자 액세스, 스토리지 리소스 검색(작업 환경 추가) 기능이 포함된 * 스토리지 관리자 * 역할이 부여됩니다. 팀 구성원 중 한 명은 * 시스템 상태 전문가 * 역할을 맡아 해당 지역에서 스토리지 리소스의 상태를 관리할 수 있지만 작업 환경을 수정하거나 삭제할 수는 없습니다. 할당된 프로젝트의 스토리지 리소스에 대한 소프트웨어 업데이트를 수행할 수도 있습니다.

조직에는 사용자 관리, 커넥터 생성 및 디지털 지갑과 같은 비용 관리 도구를 비롯한 BlueXP 의 모든 측면을 관리할 수 있는 * 조직 관리자 * 역할을 가진 두 명의 추가 사용자와 할당된 폴더 및 프로젝트에 대해 BlueXP  관리 작업을 수행할 수 있는 * 폴더 또는 프로젝트 관리자 * 역할을 가진 여러 사용자가 있습니다.

다음 표는 각 BlueXP 스토리지 역할이 수행하는 작업을 보여줍니다.

[cols="40,20a,20a,20a"]
|===
| 기능 및 동작 | 스토리지 관리자 | 시스템 상태 전문가 | 스토리지 뷰어 


4+| * 캔버스 *: 


| 새로운 리소스 검색(새로운 작업 환경 조성)  a| 
예
 a| 
예
 a| 
아니요



| 검색된 리소스를 봅니다  a| 
예
 a| 
예
 a| 
아니요



| 작업 환경을 삭제합니다  a| 
예
 a| 
아니요
 a| 
아니요



| 작업 환경을 수정합니다  a| 
예
 a| 
아니요
 a| 
아니요



| * 커넥터 만들기 *  a| 
아니요
 a| 
아니요
 a| 
아니요



4+| * 디지털 어드바이저 * 


| 모든 페이지 및 기능을 봅니다  a| 
예
 a| 
예
 a| 
예



4+| * 디지털 지갑 * 


| 모든 페이지 및 기능을 봅니다  a| 
아니요
 a| 
아니요
 a| 
아니요



4+| * 소프트웨어 업데이트 * 


| 랜딩 페이지 및 권장사항 보기  a| 
예
 a| 
예
 a| 
예



| 잠재적인 버전 권장사항 및 주요 이점을 검토하십시오  a| 
예
 a| 
예
 a| 
예



| 클러스터의 업데이트 세부 정보를 봅니다  a| 
예
 a| 
예
 a| 
예



| 사전 업데이트 확인을 실행하고 업그레이드 계획을 다운로드합니다  a| 
예
 a| 
예
 a| 
예



| 소프트웨어 업데이트를 설치합니다  a| 
예
 a| 
예
 a| 
아니요



4+| * 경제적 효율성 * 


| 용량 계획 상태를 검토합니다  a| 
예
 a| 
예
 a| 
예



| 다음 작업 선택(모범 사례, 등급)  a| 
예
 a| 
아니요
 a| 
아니요



| 콜드 데이터를 클라우드 스토리지에 계층화하여 스토리지를 확보하십시오  a| 
예
 a| 
예
 a| 
아니요



| 미리 알림을 설정합니다  a| 
예
 a| 
예
 a| 
예



4+| * 지속 가능성 * 


| 대시보드 및 권장 사항 보기  a| 
예
 a| 
예
 a| 
예



| 보고서 데이터를 다운로드합니다  a| 
예
 a| 
예
 a| 
예



| 탄소 완화 비율을 편집합니다  a| 
예
 a| 
예
 a| 
아니요



| 권장 사항을 수정합니다  a| 
예
 a| 
예
 a| 
아니요



| 권장 사항을 연기합니다  a| 
예
 a| 
예
 a| 
아니요



4+| * 시스템 관리자 액세스 * 


| 자격 증명을 입력할 수 있습니다  a| 
예
 a| 
예
 a| 
아니요



4+| 자격 증명 * 


| 사용자 자격 증명  a| 
예
 a| 
예
 a| 
아니요

|===