---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: BlueXP  ID 및 액세스 관리에는 조직의 구성원에게 할당할 수 있는 미리 정의된 여러 역할이 포함되어 있습니다. 
---
= BlueXP  액세스 역할
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  IAM(ID 및 액세스 관리)에는 리소스 계층 구조의 다양한 수준에서 조직 구성원에게 할당할 수 있는 미리 정의된 여러 역할이 포함되어 있습니다. 이러한 역할을 할당하기 전에 각 역할에 포함된 사용 권한을 이해해야 합니다. 역할은 플랫폼과 데이터 서비스의 두 가지 범주로 분류됩니다.



== 플랫폼 역할

플랫폼 역할은 사용자에게 할당할 수 있는 가장 광범위한 역할이며 역할 할당 및 사용자 추가, 모든 BlueXP  기능 수행 등 BlueXP  관리에 대한 광범위한 권한을 허용합니다. BlueXP  IAM에는 조직 관리자 및 폴더 또는 프로젝트 관리자의 두 가지 플랫폼 역할이 포함되어 있습니다. 두 BlueXP  IAM 플랫폼 역할의 주된 차이점은 범위입니다.



=== 조직 관리자

사용자가 조직 내의 모든 프로젝트 및 폴더에 제한 없이 액세스하고, 프로젝트 또는 폴더에 구성원을 추가하고, BlueXP  작업을 수행하고 모든 데이터 서비스를 사용할 수 있도록 합니다.



=== 폴더 또는 프로젝트 관리자

사용자가 할당된 특정 프로젝트 및 폴더에 대해 무제한 액세스를 허용합니다. 자신이 관리하는 프로젝트 또는 폴더에 구성원을 추가할 수 있을 뿐 아니라 BlueXP  작업을 수행하고 할당된 폴더 또는 프로젝트 내의 모든 데이터 서비스를 사용할 수 있습니다.

폴더 또는 프로젝트 관리자 역할은 커넥터를 만들 수 없습니다.



=== 플랫폼 역할 비교 표

[cols="24,19,19"]
|===
| 작업 | 조직 관리자 | 폴더 또는 프로젝트 관리자 


| 커넥터를 작성합니다 | 예 | 아니요 


| 작업 환경 생성, 수정 또는 삭제(BlueXP  Canvas를 사용하여 새 리소스 추가 또는 검색) | 예 | 예 


| 삭제를 포함하여 프로젝트/폴더를 작성합니다 | 예 | 아니요 


| 기존 프로젝트/폴더 이름을 바꿉니다 | 예 | 예 


| 역할을 할당하고 사용자를 추가합니다 | 예 | 예 


| 자원을 폴더 및 프로젝트와 연결합니다 | 예 | 예 


| 커넥터를 폴더 및 프로젝트에 연결합니다 | 예 | 아니요 


| 폴더 및 프로젝트에서 커넥터를 제거합니다 | 예 | 아니요 


| 커넥터 관리(인증서, 설정 등 편집) | 예 | 아니요 


| 설정 > 자격 증명에서 자격 증명을 관리합니다 | 예 | 예 


| BlueXP  타임라인을 봅니다 | 예 | 예 


| BlueXP  서비스 사용 | 예 | 예 


| 지원에 BlueXP 를 등록하고 사례를 제출합니다 | 예 | 예 
|===
대규모 다국적 조직에 대한 BlueXP 의 조직 역할의 예:: 다국적 기업인 XYZ Corporation은 북미, 유럽 및 아시아 태평양을 기준으로 데이터 스토리지 리소스에 대한 액세스 권한을 분리하는 것을 목표로 합니다. 이들은 각 지역에서 리소스를 독점적으로 제어하면서 중앙 집중식 감독을 유지하기를 원합니다.
+
--
이를 위해 XYZ Corporation의 BlueXP 에서 조직 관리자 역할을 할당한 사람이 초기 작업 환경을 만든 다음 BlueXP 에 각 지역에 대해 별도의 폴더를 만듭니다. 각 영역의 폴더에는 해당 영역과 관련된 프로젝트(관련 리소스 포함)가 포함되어 있습니다. 조직 관리자는 각 지역의 BlueXP  사용자에게 폴더/프로젝트 관리자 역할을 할당합니다.

초기 설정이 완료되면 폴더 또는 프로젝트 관리자 역할을 가진 지역 관리자는 새 작업 환경을 만들고 해당 지역 내에 사용자를 추가할 수 있습니다. 이러한 지역 관리자는 할당된 폴더 및 프로젝트를 추가/제거/이름 변경할 수도 있습니다. 조직 관리자는 새로운 작업 환경 또는 리소스에 대한 권한을 상속하여 전체 조직 전체의 스토리지 사용량에 대한 가시성을 유지합니다.

--




== 응용 프로그램 역할

다음은 응용 프로그램 범주의 역할 목록입니다.



=== Keystone 역할

다음 역할을 사용하여 Keystone에 대한 사용자 액세스 권한을 할당할 수 있습니다.


NOTE: BlueXP 를 통해 Keystone에 액세스하는 것은 현재 베타 버전입니다. Keystone 베타에 참여하려면 NetApp 담당자에게 문의하십시오.

* * Keystone admin *: Keystone 구독을 관리하고 경고, 보고서, 구독에 대한 조치를 취하십시오.
* * Keystone 뷰어 *: Keystone 구독은 물론 보고서, 알림 및 자산을 볼 수 있습니다.


다음 표에는 각 Keystone 역할이 수행할 수 있는 작업이 나와 있습니다.

[cols="40,20a,20a"]
|===
| 기능 및 동작 | Keystone 관리자 | Keystone 뷰어 


| 구독, 자산, 모니터 및 관리 탭을 봅니다  a| 
예
 a| 
예



3+| * Keystone 구독 페이지 *: 


| 구독을 볼 수 있습니다  a| 
예
 a| 
예



| 구독을 수정하거나 갱신할 수 있습니다  a| 
예
 a| 
아니요



3+| * Keystone 자산 페이지 *: 


| 자산을 봅니다  a| 
예
 a| 
예



| 자산 관리  a| 
예
 a| 
아니요



3+| * Keystone 알림 페이지 *: 


| 알림을 봅니다  a| 
예
 a| 
아니요



| 알림을 관리합니다  a| 
예
 a| 
아니요



| 자신에 대한 알림을 생성합니다  a| 
예
 a| 
예



3+| * 디지털 지갑 *: 


| 디지털 지갑을 볼 수 있습니다  a| 
예
 a| 
예



3+| * Keystone 보고서 페이지 *: 


| 보고서 다운로드  a| 
예
 a| 
예



| 보고서 관리  a| 
예
 a| 
예



| 자체 보고서를 생성합니다  a| 
예
 a| 
예



3+| * 서비스 요청 *: 


| 서비스 요청 작성  a| 
예
 a| 
아니요



| 조직 내의 모든 사용자가 작성한 서비스 요청을 볼 수 있습니다  a| 
예
 a| 
예

|===


== 데이터 서비스 역할

아래는 데이터 서비스 범주의 역할 목록입니다.



=== 분류 뷰어

BlueXP  분류 스캔 결과를 볼 수 있는 기능을 제공합니다.

분류에 관리자 역할이 없습니다.

권한:: 규정 준수 정보를 보고 액세스 권한이 있는 리소스에 대한 보고서를 생성합니다. 이러한 사용자는 볼륨, 버킷 또는 데이터베이스 스키마의 스캔을 활성화하거나 비활성화할 수 없습니다.


이 역할을 가진 구성원은 다른 작업을 사용할 수 없습니다.



=== 랜섬웨어 보호

다음 역할을 사용하여 사용자에게 랜섬웨어 보호에 대한 액세스 권한을 할당할 수 있습니다.

* * 랜섬웨어 방어 관리자 * : 보호, 경고, 복구, 설정 및 보고서 탭에서 작업을 관리합니다.
* * 랜섬웨어 방어 뷰어 * : 워크로드 데이터를 보고, 경고 데이터를 보고, 복구 데이터를 다운로드하고 보고서를 다운로드합니다.


다음 표는 각 BlueXP  랜섬웨어 차단 역할이 수행할 수 있는 작업을 나타냅니다.

[cols="40,20a,20a"]
|===
| 기능 및 동작 | 랜섬웨어 차단 관리자 | 랜섬웨어 방어 뷰어 


| 대시보드 및 모든 탭을 봅니다  a| 
예
 a| 
예



| 무료 평가판을 시작하십시오  a| 
예
 a| 
아니요



| 워크로드 검색 시작  a| 
예
 a| 
아니요



3+| * 보호 탭 *: 


| 정책을 추가, 수정 또는 삭제합니다  a| 
예
 a| 
아니요



| 워크로드 보호  a| 
예
 a| 
아니요



| 중요 데이터를 식별합니다  a| 
예
 a| 
아니요



| 워크로드 보호를 편집합니다  a| 
예
 a| 
아니요



| 워크로드 세부 정보를 봅니다  a| 
예
 a| 
예



| 데이터 다운로드  a| 
예
 a| 
예



3+| * 경고 탭 *: 


| 알림 세부 정보를 봅니다  a| 
예
 a| 
예



| 인시던트 상태를 편집합니다  a| 
예
 a| 
아니요



| 인시던트 세부 정보를 봅니다  a| 
예
 a| 
예



| 영향을 받는 파일의 전체 목록을 가져옵니다  a| 
예
 a| 
아니요



| 알림 데이터를 다운로드합니다  a| 
예
 a| 
예



3+| * 복구 탭 *: 


| 영향을 받는 파일을 다운로드합니다  a| 
예
 a| 
아니요



| 워크로드를 복원합니다  a| 
예
 a| 
아니요



| 복구 데이터를 다운로드합니다  a| 
예
 a| 
예



| 보고서 다운로드  a| 
예
 a| 
예



3+| * 설정 탭 *: 


| 백업 타겟을 추가하거나 수정합니다  a| 
예
 a| 
아니요



| SIEM 타겟을 추가하거나 수정합니다  a| 
예
 a| 
아니요



3+| * 보고서 탭 *: 


| 보고서 다운로드  a| 
예
 a| 
예

|===


=== SnapCenter 관리자

애플리케이션에 대한 BlueXP  백업 및 복구를 사용하여 온프레미스 ONTAP 클러스터의 스냅샷을 백업하는 기능을 제공합니다.

SnapCenter에는 뷰어 역할이 없습니다.

권한:: 이 역할을 가진 구성원은 BlueXP 에서 다음 작업을 수행할 수 있습니다.
+
--
* 백업 및 복구 > 애플리케이션에서 모든 작업을 완료합니다
* 권한이 있는 프로젝트 및 폴더의 모든 작업 환경을 관리합니다
* 모든 BlueXP  서비스 사용


--




== 관련 링크

* link:concept-identity-and-access-management.html["BlueXP  ID 및 액세스 관리에 대해 자세히 알아보십시오"]
* link:task-iam-get-started.html["BlueXP  IAM을 시작하십시오"]
* link:task-iam-manage-members-permissions.html["BlueXP  구성원 및 해당 사용 권한을 관리합니다"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["BlueXP  IAM용 API에 대해 알아보십시오"^]

