---
sidebar: sidebar 
permalink: task-install-connector-google-manual.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector 
summary: 자신의 Linux 호스트에 Connector를 수동으로 설치하려면 호스트 요구 사항을 검토하고, 네트워킹을 설정하고, Google Cloud 권한을 준비하고, Google Cloud API를 활성화하고, Connector를 설치한 다음 준비된 사용 권한을 제공해야 합니다. 
---
= Google Cloud에 Connector를 수동으로 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
자신의 Linux 호스트에 Connector를 수동으로 설치하려면 호스트 요구 사항을 검토하고, 네트워킹을 설정하고, Google Cloud 권한을 준비하고, Google Cloud API를 활성화하고, Connector를 설치한 다음 준비된 사용 권한을 제공해야 합니다.

.시작하기 전에
을(를) 검토해야 합니다 link:reference-limitations.html["커넥터 제한"].



== 1단계: 호스트 요구 사항을 검토합니다

Connector 소프트웨어는 특정 운영 체제 요구 사항, RAM 요구 사항, 포트 요구 사항 등을 충족하는 호스트에서 실행되어야 합니다.

전용 호스트:: 다른 애플리케이션과 공유되는 호스트에서는 Connector가 지원되지 않습니다. 호스트는 전용 호스트여야 합니다.
지원되는 운영 체제::
+
--
* 우분투 22.04 LTS
* CentOS 7.6, 7.7, 7.8 및 7.9
* Red Hat Enterprise Linux 7.6, 7.7, 7.8 및 7.9
+
호스트는 Red Hat Subscription Management에 등록되어 있어야 합니다. 등록되지 않은 경우 호스트는 Connector 설치 중에 필요한 타사 소프트웨어를 업데이트하기 위해 리포지토리에 액세스할 수 없습니다.

+
Connector는 이러한 운영 체제의 영어 버전에서 지원됩니다.



--
하이퍼바이저:: Ubuntu, CentOS 또는 Red Hat Enterprise Linux 실행 인증을 받은 베어 메탈 또는 호스팅된 하이퍼바이저가 필요합니다.
+
--
https://access.redhat.com/certified-hypervisors["Red Hat 솔루션: Red Hat Enterprise Linux 실행 인증을 받은 하이퍼바이저는 무엇입니까?"^]

--
CPU:: 코어 4개 또는 vCPU 4개
RAM:: 14GB
Google Cloud 컴퓨터 유형입니다:: 위의 CPU 및 RAM 요구 사항을 충족하는 인스턴스 유형입니다. n2-standard-4를 추천합니다.
+
--
Connector는 를 지원하는 OS가 있는 VM 인스턴스의 Google Cloud에서 지원됩니다 https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["차폐된 VM 기능"^]

--
/opt의 디스크 공간입니다:: 100GiB의 공간을 사용할 수 있어야 합니다
/var의 디스크 공간입니다:: 20GiB의 공간을 사용할 수 있어야 합니다
Docker 엔진:: 커넥터를 설치하기 전에 호스트에 Docker Engine 버전 19.3.1 이상이 필요합니다. https://docs.docker.com/engine/install/["설치 지침을 봅니다"^]




== 2단계: 네트워킹을 설정한다

Connector가 하이브리드 클라우드 환경 내의 리소스 및 프로세스를 관리할 수 있도록 네트워킹을 설정합니다. 예를 들어 대상 네트워크에 대한 연결을 사용할 수 있고 아웃바운드 인터넷 액세스를 사용할 수 있는지 확인해야 합니다.

대상 네트워크에 대한 연결:: Connector를 사용하려면 작업 환경을 만들고 관리할 위치에 대한 네트워크 연결이 필요합니다. 예를 들어, 온프레미스 환경에서 Cloud Volumes ONTAP 시스템 또는 스토리지 시스템을 생성할 네트워크를 예로 들 수 있습니다.


아웃바운드 인터넷 액세스:: 커넥터를 배포하는 네트워크 위치에 특정 끝점에 연결하려면 아웃바운드 인터넷 연결이 있어야 합니다.


수동 설치 중에 연결된 끝점입니다:: 자체 Linux 호스트에 커넥터를 수동으로 설치할 경우 Connector 설치 과정에서 다음 URL에 액세스해야 합니다.
+
--
* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io
+
설치 중에 호스트가 운영 체제 패키지를 업데이트하려고 할 수 있습니다. 호스트는 이러한 OS 패키지의 서로 다른 미러링 사이트에 연결할 수 있습니다.



--


커넥터에서 접촉된 끝점:: Connector는 일상적인 운영을 위해 퍼블릭 클라우드 환경 내의 리소스 및 프로세스를 관리하려면 다음 엔드포인트에 연결하는 아웃바운드 인터넷 액세스가 필요합니다.
+
--
아래 나열된 끝점은 모두 CNAME 항목입니다.

[cols="2a,1a"]
|===
| 엔드포인트 | 목적 


 a| 
\https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Google Cloud에서 리소스를 관리합니다.



 a| 
https://support.netapp.com 으로 문의하십시오
https://mysupport.netapp.com 으로 문의하십시오
 a| 
라이센스 정보를 얻고 AutoSupport 메시지를 NetApp 지원 팀에 전송합니다.



 a| 
\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com

\https://netapp-cloud-account.auth0.com
 a| 
BlueXP 내에서 SaaS 기능 및 서비스를 제공합니다.

현재 Connector가 "cloudmanager.cloud.netapp.com" 에 문의하고 있지만 곧 출시될 릴리스에서 "api.bluexp.netapp.com" 에 연락하기 시작합니다.



 a| 
\https://*.blob.core.windows.net

\https://cloudmanagerinfraprod.azurecr.io
 a| 
Connector 및 해당 Docker 구성 요소를 업그레이드합니다.

|===
--


프록시 서버:: 조직에서 모든 나가는 인터넷 트래픽에 대해 프록시 서버를 배포해야 하는 경우 HTTP 또는 HTTPS 프록시에 대한 다음 정보를 가져옵니다. 설치하는 동안 이 정보를 제공해야 합니다.
+
--
* IP 주소입니다
* 자격 증명
* HTTPS 인증서


--


포트:: 커넥터를 시작하거나 커넥터가 Cloud Volumes ONTAP에서 NetApp 지원으로 AutoSupport 메시지를 보내는 프록시로 사용되지 않는 한 커넥터로 들어오는 트래픽이 없습니다.
+
--
* HTTP(80) 및 HTTPS(443)는 드물게 사용되는 로컬 UI에 대한 액세스를 제공합니다.
* SSH(22)는 문제 해결을 위해 호스트에 연결해야 하는 경우에만 필요합니다.
* 아웃바운드 인터넷 연결을 사용할 수 없는 서브넷에 Cloud Volumes ONTAP 시스템을 배포하는 경우 포트 3128을 통한 인바운드 연결이 필요합니다.
+
Cloud Volumes ONTAP 시스템에 AutoSupport 메시지를 보내기 위한 아웃바운드 인터넷 연결이 없는 경우 BlueXP는 자동으로 해당 시스템이 커넥터에 포함된 프록시 서버를 사용하도록 구성합니다. 유일한 요구 사항은 커넥터 보안 그룹이 포트 3128을 통한 인바운드 연결을 허용하는지 확인하는 것입니다. Connector를 배포한 후 이 포트를 열어야 합니다.



--


NTP를 활성화합니다:: BlueXP 분류를 사용하여 회사 데이터 소스를 검사하려는 경우 BlueXP Connector 시스템과 BlueXP 분류 시스템 모두에서 NTP(Network Time Protocol) 서비스를 활성화하여 시스템 간에 시간이 동기화되도록 해야 합니다. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP 분류에 대해 자세히 알아보십시오"^]




== 3단계: 커넥터에 대한 사용 권한을 설정합니다

BlueXP에 Google Cloud의 리소스를 관리하는 데 필요한 권한을 Connector에 제공하려면 Google Cloud 서비스 계정이 필요합니다. Connector를 생성할 때 이 서비스 계정을 Connector VM에 연결해야 합니다.

.단계
. Google Cloud에서 사용자 지정 역할 생성:
+
.. 의 내용이 포함된 YAML 파일을 생성합니다 link:reference-permissions-gcp.html["Connector에 대한 서비스 계정 권한"].
.. Google Cloud에서 클라우드 쉘을 활성화합니다.
.. 필요한 권한이 포함된 YAML 파일을 업로드합니다.
.. 을 사용하여 사용자 지정 역할을 만듭니다 `gcloud iam roles create` 명령.
+
다음 예제에서는 프로젝트 수준에서 "connector"라는 역할을 만듭니다.

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud docs: 사용자 지정 역할 생성 및 관리"^]



. Google Cloud에서 서비스 계정을 생성하고 서비스 계정에 역할을 할당합니다.
+
.. IAM 및 관리 서비스에서 * 서비스 계정 > 서비스 계정 생성 * 을 선택합니다.
.. 서비스 계정 세부 정보를 입력하고 * 생성 및 계속 * 을 선택합니다.
.. 방금 만든 역할을 선택합니다.
.. 나머지 단계를 완료해서 역할을 만듭니다.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud docs: 서비스 계정 생성"^]



. 커넥터가 있는 프로젝트와 다른 프로젝트에 Cloud Volumes ONTAP 시스템을 배포하려는 경우 해당 프로젝트에 액세스할 수 있는 Connector의 서비스 계정을 제공해야 합니다.
+
예를 들어, 커넥터가 프로젝트 1에 있고 프로젝트 2에서 Cloud Volumes ONTAP 시스템을 만들려는 경우를 가정해 보겠습니다. 프로젝트 2에서 서비스 계정에 대한 액세스 권한을 부여해야 합니다.

+
.. IAM 및 관리자 서비스에서 Cloud Volumes ONTAP 시스템을 생성할 Google Cloud 프로젝트를 선택합니다.
.. IAM * 페이지에서 * 액세스 권한 부여 * 를 선택하고 필요한 세부 정보를 제공합니다.
+
*** Connector의 서비스 계정의 이메일을 입력합니다.
*** Connector의 사용자 정의 역할을 선택합니다.
*** 저장 * 을 선택합니다.




+
자세한 내용은 을 참조하십시오 https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud 설명서"^]



.결과
Connector VM에 대한 서비스 계정이 설정되어 있습니다.



== 4단계: 공유 VPC 권한 설정

공유 VPC를 사용하여 리소스를 서비스 프로젝트에 배포하는 경우 사용 권한을 준비해야 합니다.

이 표는 참조용이며 IAM 구성이 완료되면 사용 권한 테이블이 환경에 반영되어야 합니다.

.공유 VPC 권한을 봅니다
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| 아이덴티티 | 창조자 | 에서 호스팅됩니다 | 서비스 프로젝트 권한 | 호스트 프로젝트 권한 | 목적 


| Connector를 배포하기 위한 Google 계정 | 맞춤형 | 서비스 프로젝트  a| 
link:task-install-connector-google-bluexp-gcloud.html#step-2-set-up-permissions-to-create-the-connector["커넥터 배치 정책"]
 a| 
compute.networkUser
| 서비스 프로젝트에 Connector 배포 


| 커넥터 서비스 계정 | 맞춤형 | 서비스 프로젝트  a| 
link:reference-permissions-gcp.html["커넥터 서비스 계정 정책"]
| compute.networkUser

배포관리자.편집기 | 서비스 프로젝트에서 Cloud Volumes ONTAP 및 서비스를 배포 및 유지 관리합니다 


| Cloud Volumes ONTAP 서비스 계정입니다 | 맞춤형 | 서비스 프로젝트 | storage.admin을 선택합니다

회원: BlueXP 서비스 계정(serviceAccount.user) | 해당 없음 | (선택 사항) 데이터 계층화 및 BlueXP 백업 및 복구 


| Google API 서비스 에이전트입니다 | Google 클라우드 | 서비스 프로젝트  a| 
(기본값) 편집기
 a| 
compute.networkUser
| 배포를 대신하여 Google Cloud API와 상호 작용합니다. BlueXP에서 공유 네트워크를 사용할 수 있습니다. 


| Google Compute Engine 기본 서비스 계정입니다 | Google 클라우드 | 서비스 프로젝트  a| 
(기본값) 편집기
 a| 
compute.networkUser
| 배포를 대신하여 Google Cloud 인스턴스 및 컴퓨팅 인프라를 배포합니다. BlueXP에서 공유 네트워크를 사용할 수 있습니다. 
|===
참고:

. 배포관리자 .editor는 배포에 방화벽 규칙을 전달하지 않고 BlueXP에서 사용자를 위해 방화벽 규칙을 만들도록 선택한 경우에만 호스트 프로젝트에 필요합니다. BlueXP는 호스트 프로젝트에 VPC0 방화벽 규칙이 지정되지 않은 경우 이를 포함하는 배포를 생성합니다.
. Firewall.create 및 firewall.delete 은 배포에 방화벽 규칙을 전달하지 않고 BlueXP에서 사용자를 위해 방화벽 규칙을 만들도록 선택한 경우에만 필요합니다. 이러한 권한은 BlueXP 계정 .YAML 파일에 있습니다. 공유 VPC를 사용하여 HA 쌍을 구축하는 경우 이러한 사용 권한을 사용하여 VPC1, 2 및 3에 대한 방화벽 규칙을 생성합니다. 다른 모든 배포의 경우 이러한 사용 권한을 사용하여 VPC0에 대한 규칙을 만들 수도 있습니다.
. 데이터 계층화의 경우 계층화 서비스 계정은 프로젝트 수준뿐만 아니라 서비스 계정에서 serviceAccount.user 역할을 가져야 합니다. 현재 프로젝트 수준에서 serviceAccount.user 를 할당하는 경우 getIAMPolicy를 사용하여 서비스 계정을 쿼리할 때 사용 권한이 표시되지 않습니다.


====


== 5단계: Google Cloud API를 활성화합니다

Google Cloud에 Cloud Volumes ONTAP 시스템을 배포하기 전에 여러 Google Cloud API를 활성화해야 합니다.

.단계
. 프로젝트에서 다음 Google Cloud API를 활성화합니다.
+
** Cloud Deployment Manager V2 API
** 클라우드 로깅 API
** Cloud Resource Manager API를 참조하십시오
** 컴퓨팅 엔진 API
** IAM(Identity and Access Management) API
** 클라우드 키 관리 서비스(KMS) API
+
(고객이 관리하는 암호화 키(CMEK)로 BlueXP 백업 및 복구를 사용하려는 경우에만 필요)





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Google Cloud 설명서: API 활성화"^]



== 6단계: 커넥터를 설치합니다

필수 구성 요소를 완료한 후 자신의 Linux 호스트에 소프트웨어를 수동으로 설치할 수 있습니다.

.시작하기 전에
다음과 같은 항목이 있어야 합니다.

* 커넥터를 설치할 수 있는 루트 권한
* Connector의 인터넷 액세스에 프록시가 필요한 경우 프록시 서버에 대한 세부 정보입니다.
+
설치 후 프록시 서버를 구성할 수 있지만 이렇게 하려면 커넥터를 다시 시작해야 합니다.

* 프록시 서버가 HTTPS를 사용하거나 프록시가 가로채기 프록시인 경우 CA 서명 인증서입니다.


.이 작업에 대해
NetApp Support 사이트에서 제공되는 설치 프로그램은 이전 버전일 수 있습니다. 새 버전이 있는 경우 설치 후 커넥터가 자동으로 업데이트됩니다.

.단계
. Docker가 설정 및 실행 중인지 확인합니다.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----
. _http_proxy_or_https_proxy_system 변수가 호스트에 설정되어 있으면 이를 제거합니다.
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
이러한 시스템 변수를 제거하지 않으면 설치가 실패합니다.

. 에서 Connector 소프트웨어를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp Support 사이트"^]를 선택한 다음 Linux 호스트에 복사합니다.
+
네트워크 또는 클라우드에서 사용하도록 고안된 "온라인" 커넥터 설치 프로그램을 다운로드해야 합니다. Connector에 대해 별도의 "오프라인" 설치 프로그램을 사용할 수 있지만 전용 모드 배포에서만 지원됩니다.

. 스크립트를 실행할 권한을 할당합니다.
+
[source, cli]
----
chmod +x BlueXP-Connector-Cloud-<version>
----
+
여기서 <version>는 다운로드한 커넥터 버전입니다.

. 설치 스크립트를 실행합니다.
+
[source, cli]
----
 ./BlueXP-Connector-Cloud-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
proxy 및 -- cacert 매개 변수는 선택 사항입니다. 프록시 서버가 있는 경우 그림과 같이 매개 변수를 입력해야 합니다. 설치 프로그램에서 프록시에 대한 정보를 제공하라는 메시지를 표시하지 않습니다.

+
다음은 두 가지 선택적 매개 변수를 사용하는 명령의 예입니다.

+
[source, cli]
----
 ./BlueXP-Connector-Cloud-v3.9.35 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
-- 프록시는 다음 형식 중 하나를 사용하여 커넥터가 HTTP 또는 HTTPS 프록시 서버를 사용하도록 구성합니다.

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
다음 사항에 유의하십시오.

+
*** 사용자는 로컬 사용자 또는 도메인 사용자일 수 있습니다.
*** 도메인 사용자의 경우 위에 표시된 \ 에 ASCII 코드를 사용해야 합니다.
*** BlueXP는 @ 문자를 포함하는 암호를 지원하지 않습니다.




+
cacert는 Connector와 프록시 서버 간의 HTTPS 액세스에 사용할 CA 서명 인증서를 지정합니다. 이 매개 변수는 HTTPS 프록시 서버를 지정하거나 프록시가 가로채기 프록시인 경우에만 필요합니다.

. 설치가 완료될 때까지 기다립니다.
+
프록시 서버를 지정한 경우 설치가 끝나면 커넥터 서비스(occm)가 두 번 다시 시작됩니다.

. Connector 가상 머신에 연결된 호스트에서 웹 브라우저를 열고 다음 URL을 입력합니다.
+
https://_ipaddress_[]

. 로그인한 후 Connector를 설정합니다.
+
.. Connector와 연결할 BlueXP 계정을 지정합니다.
.. 시스템의 이름을 입력합니다.
.. 에서 * 보안 환경에서 실행 중입니까? * 제한된 모드를 사용하지 않도록 설정합니다.
+
이 단계에서는 표준 모드에서 BlueXP를 사용하는 방법을 설명하므로 제한된 모드를 사용하지 않도록 설정해야 합니다. 보안 환경이 있고 BlueXP 백엔드 서비스에서 이 계정의 연결을 끊으려면 제한된 모드만 활성화해야 합니다. 그렇다면 link:task-quick-start-restricted-mode.html["제한된 모드에서 BlueXP를 시작하려면 다음 단계를 따르십시오"].

.. Let's start * 를 선택합니다.




.결과
이제 커넥터가 설치되어 BlueXP 계정으로 설정됩니다.

Connector를 생성한 동일한 Google Cloud 계정에 Google Cloud Storage 버킷이 있는 경우 BlueXP 캔버스에 Google Cloud 스토리지 작업 환경이 자동으로 표시됩니다. https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html["BlueXP에서 Google Cloud 스토리지를 관리하는 방법에 관해 알아보십시오"^]



== 7단계: BlueXP에 권한 제공

이전에 설정한 Google Cloud 권한을 BlueXP에 제공해야 합니다. 권한을 제공하면 BlueXP가 Google Cloud에서 데이터 및 스토리지 인프라를 관리할 수 있습니다.

.단계
. Google Cloud 포털로 이동하여 Connector VM 인스턴스에 서비스 계정을 할당합니다.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Google Cloud 설명서: 인스턴스에 대한 서비스 계정 및 액세스 범위 변경"^]

. 다른 Google Cloud 프로젝트의 리소스를 관리하려면 해당 프로젝트에 BlueXP 역할의 서비스 계정을 추가하여 액세스 권한을 부여합니다. 각 프로젝트에 대해 이 단계를 반복해야 합니다.


.결과
BlueXP는 이제 Google Cloud에서 대신 작업을 수행하는 데 필요한 권한을 가지고 있습니다.
