---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: BlueXP에 로그인하는 방법은 계정에 사용하는 BlueXP 구축 모드에 따라 다릅니다. 
---
= BlueXP에 로그인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP에 로그인하는 방법은 계정에 사용하는 BlueXP 구축 모드에 따라 다릅니다.

link:concept-modes.html["BlueXP 배포 모드에 대해 알아보십시오"].

[role="tabbed-block"]
====
.표준 모드
--
BlueXP에 등록하면 웹 기반 콘솔에서 로그인하여 데이터 및 스토리지 인프라 관리를 시작할 수 있습니다.

.이 작업에 대해
다음 옵션 중 하나를 사용하여 BlueXP 웹 기반 콘솔에 로그인할 수 있습니다.

* 기존 NetApp Support 사이트(NSS) 자격 증명
* 이메일 주소 및 암호를 사용하여 NetApp 클라우드 로그인
* 통합 연결
+
Single Sign-On을 사용하여 회사 디렉터리(통합 ID)의 자격 증명을 사용하여 로그인할 수 있습니다. link:concept-federation.html["BlueXP에서 ID 페더레이션을 사용하는 방법에 대해 알아봅니다"].



.단계
. 웹 브라우저를 열고 로 이동합니다 https://console.bluexp.netapp.com["BlueXP 콘솔"^]
. 로그인 * 페이지에서 로그인과 관련된 이메일 주소를 입력합니다.
. 로그인과 관련된 인증 방법에 따라 자격 증명을 입력하라는 메시지가 표시됩니다.
+
** NetApp 클라우드 자격 증명: 암호를 입력합니다
** 통합 사용자: 통합 ID 자격 증명을 입력합니다
** NetApp Support 사이트 계정: NetApp Support 사이트 자격 증명을 입력합니다




.결과
이제 로그인하고 BlueXP를 사용하여 하이브리드 멀티 클라우드 인프라를 관리할 수 있습니다.

--
.제한된 모드
--
제한된 모드에서 BlueXP를 사용하는 경우 Connector에서 로컬로 실행되는 사용자 인터페이스에서 BlueXP 콘솔에 로그인해야 합니다.

.이 작업에 대해
BlueXP에서는 계정이 제한된 모드로 설정된 경우 다음 옵션 중 하나로 로그인할 수 있습니다.

* 이메일 주소 및 암호를 사용하여 NetApp 클라우드 로그인
* 통합 연결
+
Single Sign-On을 사용하여 회사 디렉터리(통합 ID)의 자격 증명을 사용하여 로그인할 수 있습니다. link:concept-federation.html["BlueXP에서 ID 페더레이션을 사용하는 방법에 대해 알아봅니다"].



.단계
. 웹 브라우저를 열고 다음 URL을 입력합니다.
+
https://_ipaddress_[]

+
_ipaddress_는 Connector를 설치한 호스트의 구성에 따라 localhost, 개인 IP 주소 또는 공용 IP 주소일 수 있습니다. 예를 들어, Connector 호스트에 접속되어 있는 호스트의 전용 IP 주소를 입력해야 할 수 있습니다.

. 로그인하려면 사용자 이름과 암호를 입력하십시오.


.결과
이제 로그인하고 BlueXP를 사용하여 하이브리드 멀티 클라우드 인프라를 관리할 수 있습니다.

--
.비공개 모드
--
비공개 모드에서 BlueXP를 사용하는 경우 Connector에서 로컬로 실행되는 사용자 인터페이스에서 BlueXP 콘솔에 로그인해야 합니다.

.이 작업에 대해
비공개 모드는 로컬 사용자 관리 및 액세스를 지원합니다. BlueXP의 클라우드 서비스를 통해 인증이 제공되지 않습니다.

.단계
. 웹 브라우저를 열고 다음 URL을 입력합니다.
+
https://_ipaddress_[]

+
_ipaddress_는 Connector를 설치한 호스트의 구성에 따라 localhost, 개인 IP 주소 또는 공용 IP 주소일 수 있습니다. 예를 들어, Connector 호스트에 접속되어 있는 호스트의 전용 IP 주소를 입력해야 할 수 있습니다.

. 로그인하려면 사용자 이름과 암호를 입력하십시오.


.결과
이제 로그인하고 BlueXP를 사용하여 하이브리드 멀티 클라우드 인프라를 관리할 수 있습니다.

--
====