---
sidebar: sidebar 
permalink: task-install-connector-on-prem.html 
keywords: install connector, on prem connector installation, on prem connector, install connector on prem, manual install 
summary: 구내 커넥터를 설치한 다음 로그인하여 BlueXP 계정과 작동하도록 설정합니다. 
---
= 온-프레미스에 커넥터를 설치하고 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
구내 커넥터를 설치한 다음 로그인하여 BlueXP 계정과 작동하도록 설정합니다.



== 커넥터를 설치합니다

기존 Linux 호스트에서 Connector 소프트웨어를 다운로드하여 설치합니다.

.필요한 것
* 커넥터를 설치할 수 있는 루트 권한
* Connector의 인터넷 액세스에 프록시가 필요한 경우 프록시 서버에 대한 세부 정보입니다.
+
설치 후 프록시 서버를 구성할 수 있지만 이렇게 하려면 커넥터를 다시 시작해야 합니다.

* 프록시 서버가 HTTPS를 사용하거나 프록시가 가로채기 프록시인 경우 CA 서명 인증서입니다.


.이 작업에 대해
NetApp Support 사이트에서 제공되는 설치 프로그램은 이전 버전일 수 있습니다. 새 버전이 있는 경우 설치 후 커넥터가 자동으로 업데이트됩니다.

.단계
. Docker가 설정 및 실행 중인지 확인합니다.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----
. _http_proxy_or_https_proxy_system 변수가 호스트에 설정되어 있으면 이를 제거합니다.
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
이러한 시스템 변수를 제거하지 않으면 설치가 실패합니다.

. 에서 Connector 소프트웨어를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp Support 사이트"^]를 선택한 다음 Linux 호스트에 복사합니다.
+
네트워크 또는 클라우드에서 사용하도록 고안된 "온라인" 커넥터 설치 프로그램을 다운로드해야 합니다. Connector에 대해 별도의 "오프라인" 설치 프로그램을 사용할 수 있지만 전용 모드 배포에서만 지원됩니다.

. 스크립트를 실행할 권한을 할당합니다.
+
[source, cli]
----
chmod +x OnCommandCloudManager-<version>
----
+
여기서 <version>는 다운로드한 커넥터 버전입니다.

. 설치 스크립트를 실행합니다.
+
[source, cli]
----
 ./OnCommandCloudManager-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
proxy 및 -- cacert 매개 변수는 선택 사항입니다. 프록시 서버가 있는 경우 표시된 대로 매개 변수를 입력해야 합니다. 설치 프로그램에서 프록시에 대한 정보를 제공하라는 메시지를 표시하지 않습니다.

+
다음은 두 가지 선택적 매개 변수를 사용하는 명령의 예입니다.

+
[source, cli]
----
 ./OnCommandCloudManager-V3.9.26 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
-- 프록시는 다음 형식 중 하나를 사용하여 커넥터가 HTTP 또는 HTTPS 프록시 서버를 사용하도록 구성합니다.

+
** http://address:port 으로 문의하십시오
** http://username:password@address:port 으로 문의하십시오
** https://address:port 으로 문의하십시오
** https://username:password@address:port 으로 문의하십시오
+
사용자는 로컬 사용자여야 합니다. 도메인 사용자는 지원되지 않습니다.



+
cacert는 Connector와 프록시 서버 간의 HTTPS 액세스에 사용할 CA 서명 인증서를 지정합니다. 이 매개 변수는 HTTPS 프록시 서버를 지정하거나 프록시가 가로채기 프록시인 경우에만 필요합니다.



.결과
이제 커넥터가 설치되었습니다. 프록시 서버를 지정한 경우 설치가 끝나면 커넥터 서비스(occm)가 두 번 다시 시작됩니다.



== 커넥터를 설정합니다

가입하거나 로그인한 다음 Connector를 설정하여 계정을 사용할 수 있습니다.

.단계
. 웹 브라우저를 열고 다음 URL을 입력합니다.
+
https://_ipaddress_[]

+
_ipaddress_는 호스트 구성에 따라 localhost, 개인 IP 주소 또는 공용 IP 주소일 수 있습니다. 예를 들어, Connector가 공용 IP 주소가 없는 공용 클라우드에 있는 경우 Connector 호스트에 대한 연결이 있는 호스트의 전용 IP 주소를 입력해야 합니다.

. 가입 또는 로그인
. 로그인한 후 BlueXP를 설정합니다.
+
.. Connector와 연결할 BlueXP 계정을 지정합니다.
.. 시스템의 이름을 입력합니다.
.. 에서 * 보안 환경에서 실행 중입니까? * 제한된 모드를 사용하지 않도록 설정합니다.
+
이 단계에서는 표준 모드에서 BlueXP를 사용하는 방법을 설명하므로 제한된 모드를 사용하지 않도록 설정해야 합니다. (또한 Connector가 구내에 설치된 경우에는 제한된 모드가 지원되지 않습니다.)

.. 시작 * 을 클릭합니다.




.결과
BlueXP는 이제 방금 설치한 커넥터를 사용하여 설정됩니다.

.다음 단계
link:task-provide-permissions-on-prem.html["이전에 설정한 권한을 BlueXP에 제공합니다"].
