---
sidebar: sidebar 
permalink: task-upgrade-connector.html 
keywords: upgrade, manual upgrade, connector upgrade, manual connector upgrade, upgrade connector manually, private mode upgrade, offline upgrade, upgrade private mode 
summary: BlueXP는 표준 모드 또는 제한된 모드에서 BlueXP를 사용할 때 커넥터를 최신 릴리즈로 자동으로 업그레이드합니다. 새 버전은 일반적으로 새로운 기능을 소개하고 안정성을 개선하기 위해 매월 릴리스됩니다. 원하는 경우 대신 커넥터를 구성하여 로컬 리포지토리에서 이미지 업데이트를 가져올 수 있습니다. 비공개 모드 배포의 경우 항상 수동으로 커넥터를 업그레이드해야 합니다. 
---
= 커넥터 업그레이드를 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
표준 모드 또는 제한 모드에서 BlueXP 를 사용하는 경우 BlueXP 는 소프트웨어 업데이트를 얻기 위해 커넥터에 아웃바운드 인터넷 액세스가 있는 경우 커넥터를 자동으로 최신 릴리스로 업그레이드합니다. 커넥터를 업그레이드할 때 수동으로 관리해야 하는 경우 표준 모드 또는 제한된 모드에 대한 자동 업그레이드를 비활성화할 수 있습니다.


NOTE: BlueXP 를 비공개 모드로 실행할 때는 항상 커넥터를 직접 업그레이드해야 합니다.



== 자동 업그레이드를 비활성화합니다

커넥터의 자동 업그레이드 비활성화는 두 단계로 구성됩니다. 먼저 커넥터가 정상이고 최신 상태인지 확인해야 합니다. 그런 다음 구성 파일을 편집하여 자동 업그레이드 기능을 해제합니다.


NOTE: 커넥터 버전 3.9.48 이상이 있는 경우에만 자동 업그레이드를 비활성화할 수 있습니다.



=== 커넥터의 상태를 확인합니다

커넥터가 안정적이며 커넥터 VM에서 실행 중인 모든 컨테이너가 정상이고 실행 중인지 확인해야 합니다. 자동 업그레이드를 비활성화하면 커넥터 VM이 새 서비스나 업그레이드 패키지 검사를 중지합니다.

다음 명령 중 하나를 사용하여 커넥터를 확인합니다. 모든 서비스의 상태는 _running_이어야 합니다. 그렇지 않은 경우 자동 업그레이드를 비활성화하기 전에 NetApp 지원에 문의하십시오.

Docker 를 참조하십시오::
+
--
[source, cli]
----
docker ps -a
----
--
팟맨::
+
--
[source, cli]
----
podman ps -a
----
--




=== 커넥터에 대한 자동 업그레이드를 비활성화합니다

_com/opt/application/NetApp/service-manager-2/config.json_file에서 _isUpgradeDisabled_flag를 설정하여 자동 업그레이드를 비활성화합니다. 기본적으로 이 플래그는 false로 설정되며 커넥터가 자동으로 업그레이드됩니다. 이 플래그를 true 로 설정하면 자동 업그레이드를 비활성화할 수 있습니다. 이 단계를 완료하기 전에 JSON 구문을 잘 알고 있어야 합니다.

자동 업그레이드를 다시 활성화하려면 다음 단계를 수행하고 _isUpgradeDisabled_flag를 false로 설정하십시오.

.단계
. 커넥터가 최신 상태이고 정상 상태인지 확인하십시오.
. 변경 내용을 되돌릴 수 있도록 _/opt/application/NetApp/service-manager-2/config.json_file의 백업 복사본을 생성합니다.
. //opt/application/NetApp/service-manager-2/config.json_file을 편집하고 _isUpgradeDisabled_flag 값을 true로 변경합니다.
+
[source]
----
  "isUpgradeDisabled": true,
----
. 파일을 저장합니다.
. 다음 명령을 실행하여 서비스 관리자 2 서비스를 다시 시작합니다.
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. 다음 명령을 실행하여 커넥터 상태가 _ACTIVE(Running)_:_로 표시되는지 확인합니다
+
[source, cli]
----
systemctl status netapp-service-manager.service
----




== 커넥터를 업그레이드합니다

업그레이드 프로세스 중에 Connector를 다시 시작해야 업그레이드 중에 웹 기반 콘솔을 사용할 수 없게 됩니다.

.단계
. 에서 Connector 소프트웨어를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp Support 사이트"^].
+
인터넷 액세스 없이 개인 네트워크용 오프라인 설치 프로그램을 다운로드해야 합니다.

. Linux 호스트에 설치 프로그램을 복사합니다.
. 스크립트를 실행할 권한을 할당합니다.
+
[source, cli]
----
chmod +x /path/BlueXP-Connector-offline-<version>
----
+
여기서 <version>는 다운로드한 커넥터 버전입니다.

. 설치 스크립트를 실행합니다.
+
[source, cli]
----
sudo /path/BlueXP-Connector-offline-<version>
----
+
여기서 <version>는 다운로드한 커넥터 버전입니다.

. 업그레이드가 완료되면 * 도움말 > 지원 > 커넥터 * 로 이동하여 커넥터 버전을 확인할 수 있습니다.

