---
sidebar: sidebar 
permalink: task-create-connectors-gov.html 
keywords: government region, gov, govcloud, connector 
summary: 정부 지역에서 운영하는 경우 클라우드 공급자의 마켓플레이스에서 또는 수동 설치 방법을 사용하여 Connector를 배포해야 합니다. BlueXP의 SaaS 웹 사이트에서 정부 지역에 Connector를 배포할 수 없습니다. 
---
= 정부 지역에서 커넥터를 생성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
정부 지역에서 운영 중인 경우 클라우드 공급자의 마켓플레이스에서 Connector를 배포하거나 기존 Linux 호스트에 Connector 소프트웨어를 수동으로 설치해야 합니다. BlueXP의 SaaS 웹 사이트에서 정부 지역에 Connector를 배포할 수 없습니다.

커넥터 작성에 대한 지침을 보려면 다음 링크 중 하나를 사용하십시오.

* link:task-launching-aws-mktp.html#create-the-connector-in-an-aws-government-region["AWS Marketplace에서 Connector를 생성합니다"]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws-c2s.html["AWS C2S 환경에서 커넥터 및 Cloud Volumes ONTAP를 생성합니다"^]
* link:task-launching-azure-mktp.html["Azure Marketplace에서 Connector를 생성합니다"]
* link:task-installing-linux.html["자체 Linux 호스트에 커넥터를 설치합니다"]
+
자체 Linux 호스트에 수동으로 설치하려면 "온라인" 설치 프로그램을 사용하여 인터넷에 액세스할 수 있는 호스트에 커넥터를 설치해야 합니다. Connector에 대해 별도의 "오프라인" 설치 프로그램을 사용할 수 있지만 인터넷에 액세스할 수 없는 사내 사이트에서만 지원됩니다. 정부 지역에서는 지원되지 않습니다.



Connector를 배포한 후 웹 브라우저를 열고 Connector 인스턴스의 IP 주소에 연결하여 BlueXP에 액세스할 수 있습니다. https://_ipaddress_[]

Connector는 정부 지역에 배포되었기 때문에 에서 액세스할 수 없습니다 https://cloudmanager.netapp.com[].
