---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: BlueXP에 등록하면 SaaS 기반 사용자 인터페이스를 통해 웹 브라우저에서 로그인할 수 있습니다. 
---
= BlueXP에 로그인합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP에 등록하면 SaaS 기반 사용자 인터페이스를 통해 웹 브라우저에서 로그인할 수 있습니다.

link:task-sign-up-saas.html["BlueXP에 등록하고 조직을 만드는 방법에 대해 알아보십시오"].

정부 지역 또는 아웃바운드 인터넷 액세스가 없는 사이트에서 BlueXP에 액세스하는 경우 Connector에서 로컬로 실행되는 BlueXP 사용자 인터페이스에 로그인해야 합니다. link:task-managing-connectors.html#access-the-local-ui["Connector에서 로컬 UI에 액세스하는 방법에 대해 알아봅니다"].

.로그인 옵션
다음 옵션 중 하나를 사용하여 BlueXP에 로그인할 수 있습니다.

* 기존 NetApp Support 사이트(NSS) 자격 증명
* 이메일 주소 및 암호를 사용하여 NetApp 클라우드 로그인
* 통합 연결
+
Single Sign-On을 사용하여 회사 디렉터리(통합 ID)의 자격 증명을 사용하여 로그인할 수 있습니다. 자세한 내용은 로 이동하십시오 https://cloud.netapp.com/help-center["BlueXP 도움말 센터"^] 그런 다음 * 로그인 옵션 * 을 클릭합니다.



.단계
. 웹 브라우저를 열고 로 이동합니다 https://console.bluexp.netapp.com["BlueXP 콘솔"^]
. 로그인 * 페이지에서 로그인과 관련된 이메일 주소를 입력합니다.
. 로그인과 관련된 인증 방법에 따라 자격 증명을 입력하라는 메시지가 표시됩니다.
+
** NetApp 클라우드 자격 증명: 암호를 입력합니다
** 통합 사용자: 통합 ID 자격 증명을 입력합니다
** NetApp Support 사이트 계정: NetApp Support 사이트 자격 증명을 입력합니다




.결과
이제 로그인하고 BlueXP를 사용하여 하이브리드 멀티 클라우드 인프라를 관리할 수 있습니다.
