---
sidebar: sidebar 
permalink: task-set-up-networking-google.html 
keywords: networking, on prem networking, endpoints, urls, ports, ip address, proxy, proxy server, connections 
summary: Connector가 하이브리드 클라우드 환경 내의 리소스 및 프로세스를 관리할 수 있도록 네트워킹을 설정합니다. 예를 들어 대상 네트워크에 대한 연결을 사용할 수 있고 아웃바운드 인터넷 액세스를 사용할 수 있는지 확인해야 합니다. 
---
= Google Cloud 네트워킹을 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Connector가 하이브리드 클라우드 환경 내의 리소스 및 프로세스를 관리할 수 있도록 네트워킹을 설정합니다. 예를 들어 대상 네트워크에 대한 연결을 사용할 수 있고 아웃바운드 인터넷 액세스를 사용할 수 있는지 확인해야 합니다.



== VPC 및 서브넷

Connector를 생성할 때 Connector가 상주할 VPC와 서브넷을 지정해야 합니다.



== 대상 네트워크에 대한 연결

Connector를 사용하려면 작업 환경을 만들고 관리할 위치에 대한 네트워크 연결이 필요합니다.



== 아웃바운드 인터넷 액세스

커넥터를 배포하는 네트워크 위치에 아웃바운드 인터넷 연결이 있어야 합니다. BlueXP 콘솔에서 커넥터를 배포할 때는 웹 브라우저에서도 아웃바운드 인터넷 액세스가 필요합니다.



=== BlueXP 콘솔에서 연결된 엔드포인트에는

SaaS 계층을 통해 제공되는 BlueXP 웹 기반 콘솔을 사용하면 여러 엔드포인트에 접속하여 데이터 관리 작업을 완료합니다. 여기에는 BlueXP 콘솔에서 커넥터를 배포하기 위해 연결된 엔드포인트가 포함됩니다.

link:reference-networking-saas-console.html["BlueXP 콘솔에서 연결된 엔드포인트 목록을 봅니다"].



=== 수동 설치 중에 연결된 끝점입니다

자체 Linux 호스트에 커넥터를 수동으로 설치할 경우 Connector 설치 과정에서 다음 URL에 액세스해야 합니다.

* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io


설치 중에 호스트가 운영 체제 패키지를 업데이트하려고 할 수 있습니다. 호스트는 이러한 OS 패키지의 서로 다른 미러링 사이트에 연결할 수 있습니다.



=== 커넥터에서 접촉된 끝점

Connector는 일상적인 운영을 위해 퍼블릭 클라우드 환경 내의 리소스 및 프로세스를 관리하려면 다음 엔드포인트에 연결하는 아웃바운드 인터넷 액세스가 필요합니다.

[cols="2a,1a"]
|===
| 엔드포인트 | 목적 


 a| 
\https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Google Cloud에서 리소스를 관리합니다.



 a| 
\https://support.netapp.com
 a| 
라이센스 정보를 얻고 AutoSupport 메시지를 NetApp 지원 팀에 전송합니다.



 a| 
\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com
 a| 
BlueXP 내에서 SaaS 기능 및 서비스를 제공합니다.

현재 Connector가 "cloudmanager.cloud.netapp.com" 에 문의하고 있지만 곧 출시될 릴리스에서 "api.bluexp.netapp.com" 에 연락하기 시작합니다.



 a| 
\https://*.blob.core.windows.net

\https://cloudmanagerinfraprod.azurecr.io
 a| 
Connector 및 해당 Docker 구성 요소를 업그레이드합니다.

|===


== 프록시 서버

조직에서 모든 나가는 인터넷 트래픽에 대해 프록시 서버를 배포해야 하는 경우 HTTP 또는 HTTPS 프록시에 대한 다음 정보를 가져옵니다. 설치하는 동안 이 정보를 제공해야 합니다.

* IP 주소입니다
* 자격 증명
* HTTPS 인증서




== 포트

커넥터를 시작하거나 커넥터가 Cloud Volumes ONTAP에서 NetApp 지원으로 AutoSupport 메시지를 보내는 프록시로 사용되지 않는 한 커넥터로 들어오는 트래픽이 없습니다.

* HTTP(80) 및 HTTPS(443)는 드물게 사용되는 로컬 UI에 대한 액세스를 제공합니다.
* SSH(22)는 문제 해결을 위해 호스트에 연결해야 하는 경우에만 필요합니다.
* 아웃바운드 인터넷 연결을 사용할 수 없는 서브넷에 Cloud Volumes ONTAP 시스템을 배포하는 경우 포트 3128을 통한 인바운드 연결이 필요합니다.
+
Cloud Volumes ONTAP 시스템에 AutoSupport 메시지를 보내기 위한 아웃바운드 인터넷 연결이 없는 경우 BlueXP는 자동으로 해당 시스템이 커넥터에 포함된 프록시 서버를 사용하도록 구성합니다. 유일한 요구 사항은 커넥터 보안 그룹이 포트 3128을 통한 인바운드 연결을 허용하는지 확인하는 것입니다. Connector를 배포한 후 이 포트를 열어야 합니다.





== IP 주소 제한

172 범위의 IP 주소와 충돌할 수 있습니다. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-limitations.html["이 제한 사항에 대해 자세히 알아보십시오"].
