---
sidebar: sidebar 
permalink: task-set-up-permissions-aws.html 
keywords: aws permissions, set up permissions, set up aws permissions, permissions, iam role, iam policy, json, policy, role, credentials 
summary: AWS에서 사용 권한을 설정하여 Connector를 데이터 및 스토리지 인프라 관리에 필요한 권한으로 구축할 수 있습니다. 사용 권한을 설정하고 제공하는 방법은 사용하려는 설치 옵션에 따라 다릅니다. 
---
= AWS 권한을 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AWS에서 사용 권한을 설정하여 Connector를 데이터 및 스토리지 인프라 관리에 필요한 권한으로 구축할 수 있습니다. 사용 권한을 설정하고 제공하는 방법은 사용하려는 설치 옵션에 따라 다릅니다.

다음 설치 옵션 중에서 선택할 수 있습니다.

* * BlueXP * 에서 설치 *: BlueXP에서 AWS를 인증하고 인스턴스를 배포할 수 있도록 권한을 설정합니다. BlueXP는 배포 중에 Connector 인스턴스에 대한 권한을 자동으로 설정합니다.
+
<<BlueXP에서 커넥터를 생성할 수 있는 권한을 설정합니다,단계별 지침을 봅니다>>.

* * AWS Marketplace에서 설치 *: Connector 인스턴스와 연결할 수 있는 IAM 역할을 설정합니다.
+
<<AWS Marketplace에서 구축할 때 Connector에 대한 권한을 설정합니다,단계별 지침을 봅니다>>.

* * 수동 설치 *: IAM 정책을 생성하여 IAM 역할 또는 IAM 사용자에게 연결합니다.
+
<<수동 설치 후 할당할 권한을 설정합니다,단계별 지침을 봅니다>>.





== BlueXP에서 커넥터를 생성할 수 있는 권한을 설정합니다

BlueXP는 VPC에 Connector 인스턴스를 구축하기 전에 AWS를 인증해야 합니다. 다음 인증 방법 중 하나를 선택할 수 있습니다.

* BlueXP에서 필요한 권한이 있는 IAM 역할을 가정하도록 합니다
* 필요한 권한이 있는 IAM 사용자를 위해 AWS 액세스 키 및 비밀 키를 제공합니다


두 옵션 중 하나를 사용할 경우 첫 번째 단계는 IAM 정책을 생성하는 것입니다. 이 정책에는 BlueXP에서 AWS에서 Connector 인스턴스를 시작하는 데 필요한 권한만 포함되어 있습니다.

필요한 경우 IAM을 사용하여 IAM 정책을 제한할 수 있습니다 `Condition` 요소. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html["AWS 설명서:조건 요소"^]


TIP: BlueXP에서 Connector를 만들면 Connector가 AWS 리소스를 관리할 수 있도록 Connector 인스턴스에 새 권한 집합이 적용됩니다.

.단계
. AWS IAM 콘솔로 이동합니다.
. 정책 > 정책 생성 * 을 선택합니다.
. JSON * 을 선택합니다.
. 다음 정책을 복사하여 붙여 넣습니다.
+
이 정책은 BlueXP에서 AWS에서 Connector 인스턴스를 실행하는 데 필요한 권한만 포함합니다. link:reference-permissions-aws.html["Connector 인스턴스 자체에 필요한 권한을 봅니다"].

+
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "iam:PassRole",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:CreateTags",
                "ec2:DescribeImages",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "iam:GetRole",
                "iam:TagRole",
                "iam:ListRoles",
                "kms:ListAliases"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/OCCMInstance": "*"
                }
            },
            "Resource": [
                "arn:aws:ec2:*:*:instance/*"
            ]
        }
    ]
}
----
. 필요한 경우 * 다음 * 을 선택하고 태그를 추가합니다.
. 다음 * 을 선택하고 이름과 설명을 입력합니다.
. Create policy * 를 선택합니다.
. BlueXP에서 사용할 수 있는 IAM 역할 또는 IAM 사용자에게 정책을 연결하여 BlueXP에 액세스 키를 제공할 수 있도록 합니다.
+
** (옵션 1) BlueXP가 가정할 수 있는 IAM 역할을 설정합니다.
+
... 대상 계정에서 AWS IAM 콘솔로 이동합니다.
... 액세스 관리에서 * 역할 > 역할 만들기 * 를 선택하고 단계를 따라 역할을 만듭니다.
... 신뢰할 수 있는 엔터티 유형 * 에서 * AWS 계정 * 을 선택합니다.
... 다른 AWS 계정 * 을 선택하고 BlueXP SaaS 계정의 ID를 입력합니다. 952013314444
... 이전 섹션에서 생성한 정책을 선택합니다.
... 역할을 만든 후 역할 ARN을 복사하여 Connector를 만들 때 BlueXP에 붙여 넣을 수 있습니다.


** (옵션 2) BlueXP에 액세스 키를 제공할 수 있도록 IAM 사용자에 대한 권한을 설정합니다.
+
... AWS IAM 콘솔에서 * Users * 를 선택한 다음 사용자 이름을 선택합니다.
... Add permissions > Attach existing policies directly * 를 선택합니다.
... 생성한 정책을 선택합니다.
... 다음 * 을 선택한 다음 * 권한 추가 * 를 선택합니다.
... IAM 사용자를 위한 액세스 키와 비밀 키가 있는지 확인합니다.






.결과
필요한 권한이 있는 IAM 역할 또는 필요한 권한이 있는 IAM 사용자가 있어야 합니다. BlueXP에서 커넥터를 생성할 때 역할 또는 액세스 키에 대한 정보를 제공할 수 있습니다.



== AWS Marketplace에서 구축할 때 Connector에 대한 권한을 설정합니다

시장 구축을 준비하려면 AWS에서 IAM 정책을 생성하고 IAM 역할에 연결합니다. AWS Marketplace에서 Connector를 생성하면 해당 IAM 역할을 선택하라는 메시지가 표시됩니다.

.단계
. AWS 콘솔에 로그인하고 IAM 서비스로 이동합니다.
. 정책 생성:
+
.. 정책 > 정책 생성 * 을 선택합니다.
.. JSON * 을 선택하고 의 내용을 복사하여 붙여 넣습니다 link:reference-permissions-aws.html["Connector에 대한 IAM 정책"].
.. 나머지 단계를 완료하고 정책을 생성합니다.
+
사용할 BlueXP 서비스에 따라 두 번째 정책을 만들어야 할 수도 있습니다. 표준 영역의 경우 권한이 두 정책에 분산됩니다. AWS에서 관리되는 정책의 최대 문자 크기 제한으로 인해 두 개의 정책이 필요합니다. link:reference-permissions-aws.html["Connector에 대한 IAM 정책에 대해 자세히 알아보십시오"].



. IAM 역할 생성:
+
.. 역할 > 역할 생성 * 을 선택합니다.
.. AWS 서비스 > EC2 * 를 선택합니다.
.. 방금 만든 정책을 첨부하여 사용 권한을 추가합니다.
.. 나머지 단계를 완료해서 역할을 만듭니다.




.결과
AWS Marketplace에서 구축하는 동안 IAM 역할을 EC2 인스턴스와 연결할 수 있습니다.



== 수동 설치 후 할당할 권한을 설정합니다

AWS의 자체 Linux 호스트에 Connector 소프트웨어를 수동으로 설치하려는 경우 다음과 같은 방법으로 권한을 제공할 수 있습니다.

* 옵션 1: IAM 정책을 생성하고 EC2 인스턴스와 연결할 수 있는 IAM 역할에 정책을 연결합니다.
* 옵션 2: 필요한 권한이 있는 IAM 사용자를 위해 BlueXP에 AWS 액세스 키를 제공합니다.


[role="tabbed-block"]
====
.IAM 역할
--
.단계
. AWS 콘솔에 로그인하고 IAM 서비스로 이동합니다.
. 정책 생성:
+
.. 정책 > 정책 생성 * 을 선택합니다.
.. JSON * 을 선택하고 의 내용을 복사하여 붙여 넣습니다 link:reference-permissions-aws.html["Connector에 대한 IAM 정책"].
.. 나머지 단계를 완료하고 정책을 생성합니다.
+
사용할 BlueXP 서비스에 따라 두 번째 정책을 만들어야 할 수도 있습니다. 표준 영역의 경우 권한이 두 정책에 분산됩니다. AWS에서 관리되는 정책의 최대 문자 크기 제한으로 인해 두 개의 정책이 필요합니다. link:reference-permissions-aws.html["Connector에 대한 IAM 정책에 대해 자세히 알아보십시오"].



. IAM 역할 생성:
+
.. 역할 > 역할 생성 * 을 선택합니다.
.. AWS 서비스 > EC2 * 를 선택합니다.
.. 방금 만든 정책을 첨부하여 사용 권한을 추가합니다.
.. 나머지 단계를 완료해서 역할을 만듭니다.




.결과
이제 Connector를 설치한 후 EC2 인스턴스와 연결할 수 있는 IAM 역할이 있습니다. link:task-provide-permissions-aws.html["이러한 권한을 BlueXP에 제공하는 방법을 알아보십시오"].

--
.AWS 액세스 키입니다
--
.단계
. AWS 콘솔에 로그인하고 IAM 서비스로 이동합니다.
. 정책 생성:
+
.. 정책 > 정책 생성 * 을 선택합니다.
.. JSON * 을 선택하고 의 내용을 복사하여 붙여 넣습니다 link:reference-permissions-aws.html["Connector에 대한 IAM 정책"].
.. 나머지 단계를 완료하고 정책을 생성합니다.
+
사용할 BlueXP 서비스에 따라 두 번째 정책을 만들어야 할 수도 있습니다.

+
표준 영역의 경우 권한이 두 정책에 분산됩니다. AWS에서 관리되는 정책의 최대 문자 크기 제한으로 인해 두 개의 정책이 필요합니다. link:reference-permissions-aws.html["Connector에 대한 IAM 정책에 대해 자세히 알아보십시오"].



. IAM 사용자에게 정책을 연결합니다.
+
** https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html["AWS 설명서: IAM 역할 생성"^]
** https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html["AWS 설명서: IAM 정책 추가 및 제거"^]


. 커넥터를 설치한 후 BlueXP에 추가할 수 있는 액세스 키가 사용자에게 있는지 확인합니다.


.결과
이제 필요한 권한이 있는 IAM 사용자와 BlueXP에 제공할 수 있는 액세스 키가 있습니다. link:task-provide-permissions-aws.html["이러한 권한을 BlueXP에 제공하는 방법을 알아보십시오"].

--
====