---
sidebar: sidebar 
permalink: task-maintain-connectors.html 
keywords: connector operating system, connector maintenance, vm maintenance, os updates, operating system updates, stop connector, restart connector 
summary: 커넥터 호스트에서 운영 체제를 유지 관리하는 것은 사용자의 책임입니다. 예를 들어, 회사의 운영 체제 배포 표준 절차에 따라 Connector 호스트의 운영 체제에 보안 업데이트를 적용해야 합니다. 
---
= Connector VM 및 운영 체제를 유지 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
커넥터 호스트에서 운영 체제를 유지 관리하는 것은 사용자의 책임입니다. 예를 들어, 회사의 운영 체제 배포 표준 절차에 따라 Connector 호스트의 운영 체제에 보안 업데이트를 적용해야 합니다.


TIP: 기존 커넥터가 있는 경우 에 유의하십시오 link:reference-connector-operating-system-changes.html["지원되는 Linux 운영 체제 변경 사항"].



== 운영 체제 패치 및 커넥터

OS 보안 패치를 적용할 때 Connector 호스트의 서비스를 중지할 필요가 없습니다.



== VM 또는 인스턴스 유형입니다

BlueXP에서 Connector를 직접 생성한 경우 BlueXP는 기본 구성을 사용하여 클라우드 공급자에 가상 머신 인스턴스를 구축했습니다. Connector를 생성한 후에는 CPU 또는 RAM이 적은 더 작은 VM 인스턴스로 변경하지 마십시오.

CPU 및 RAM 요구 사항은 다음과 같습니다.

CPU:: 코어 8개 또는 vCPU 8개
RAM:: 32GB


link:reference-connector-default-config.html["Connector의 기본 설정에 대해 알아봅니다"].



== Connector VM 중지 및 시작

Connector VM을 중지했다가 시작해야 하는 경우에는 클라우드 공급자의 콘솔에서 또는 온-프레미스 관리를 위한 표준 절차를 사용해야 합니다.

link:concept-connectors.html#connectors-must-be-operational-at-all-times["커넥터는 항상 작동해야 합니다"].



== Linux VM에 연결합니다

Connector가 실행되는 Linux VM에 연결해야 하는 경우 클라우드 공급자에서 제공하는 연결 옵션을 사용하여 연결할 수 있습니다.

설치하고:: AWS에서 Connector 인스턴스를 생성한 경우 AWS 액세스 키와 암호 키를 제공했습니다. 이 키 쌍을 사용하여 인스턴스에 SSH를 사용할 수 있습니다. EC2 Linux 인스턴스의 사용자 이름은 Ubuntu입니다(2023년 5월 이전에 생성된 커넥터의 경우 사용자 이름은 EC2-user입니다).
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["AWS Docs: Linux 인스턴스에 연결합니다"^]

--
Azure를 지원합니다:: Azure에서 Connector VM을 생성할 때 사용자 이름을 지정하고 암호 또는 SSH 공개 키로 인증하도록 선택했습니다. VM에 연결하도록 선택한 인증 방법을 사용합니다.
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure Docs: VM에 SSH를 연결합니다"^]

--
Google 클라우드:: Google Cloud에서 Connector를 만들 때는 인증 방법을 지정할 수 없습니다. 그러나 Google Cloud Console 또는 Google Cloud CLI(gcloud)를 사용하여 Linux VM 인스턴스에 연결할 수 있습니다.
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs: Linux VM에 연결합니다"^]

--




== 커넥터의 IP 주소를 변경합니다

비즈니스에 필요한 경우 클라우드 공급자가 자동으로 할당하는 Connector 인스턴스의 내부 IP 주소와 공용 IP 주소를 변경할 수 있습니다.

.단계
. 클라우드 공급자의 지침에 따라 Connector 인스턴스의 로컬 IP 주소 또는 공용 IP 주소(또는 둘 다)를 변경합니다.
. 공용 IP 주소를 변경한 경우 Connector에서 실행 중인 로컬 사용자 인터페이스에 연결해야 하는 경우 Connector 인스턴스를 다시 시작하여 새 IP 주소를 BlueXP에 등록합니다.
. 전용 IP 주소를 변경한 경우 백업이 커넥터의 새 전용 IP 주소로 전송되도록 Cloud Volumes ONTAP 구성 파일의 백업 위치를 업데이트합니다.
+
각 Cloud Volumes ONTAP 시스템의 백업 위치를 업데이트해야 합니다.

+
.. Cloud Volumes ONTAP CLI에서 권한 수준을 advanced로 설정합니다.
+
[source, cli]
----
set -privilege advanced
----
.. 다음 명령을 실행하여 현재 백업 타겟을 표시합니다.
+
[source, cli]
----
system configuration backup settings show
----
.. 다음 명령을 실행하여 백업 대상의 IP 주소를 업데이트합니다.
+
[source, cli]
----
system configuration backup settings modify -destination <target-location>
----






== Connector의 URI를 편집합니다

Connector 의 URI(Uniform Resource Identifier)를 추가하고 제거합니다.

.단계
. BlueXP 헤더에서 * 커넥터 * 드롭다운을 선택합니다.
. 커넥터 관리 * 를 선택합니다.
. 커넥터의 작업 메뉴를 선택하고 * 커넥터 편집 * 을 선택합니다.
. 커넥터 URI * 표시줄을 확장하여 커넥터의 URI를 확인합니다.
. URI를 추가 및 제거한 다음 * 적용 * 을 선택합니다.

