---
sidebar: sidebar 
permalink: task-set-up-permissions-google.html 
keywords: set up permissions, set up gcp permissions, set up google cloud permissions, google permissions, gcp permissions, service account, create service account, gcp service account, google service account 
summary: Google Cloud에서 BlueXP를 사용하여 데이터 및 스토리지 인프라를 관리할 수 있도록 Google Cloud 권한을 설정합니다. 
---
= Google Cloud 권한을 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
데이터 및 스토리지 인프라를 관리하는 데 필요한 권한으로 Connector를 배포할 수 있도록 Google Cloud에서 사용 권한을 설정합니다.

다음과 같이 Google Cloud 권한을 설정해야 합니다.

* BlueXP에서 Connector를 생성하거나 gcloud를 사용할 계획이라면 Connector VM을 배포할 Google Cloud 사용자에 대한 권한을 설정해야 합니다.
* 역할을 만들고 서비스 계정에 역할을 부여하여 Connector에 대한 권한을 설정합니다.
+
BlueXP에 필요한 권한이 있도록 이 서비스 계정을 Connector VM과 연결합니다.



구성에 따라 다음 단계를 완료해야 할 수도 있습니다.

* 프로젝트 간 사용 권한 설정
* 공유 VPC에 대한 권한 설정




== BlueXP 또는 gcloud에서 Connector를 생성할 수 있는 권한을 설정합니다

BlueXP에서 Connector를 배포하거나 gcloud를 사용하려면 먼저 Google Cloud 계정에 올바른 권한이 있는지 확인해야 합니다.

.단계
. Google Cloud에서 사용자 지정 역할 생성:
+
.. 다음 권한이 포함된 YAML 파일을 생성합니다.
+
[source, yaml]
----
title: Connector deployment policy
description: Permissions for the user who deploys the Connector from BlueXP
stage: GA
includedPermissions:
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.list
----
.. Google Cloud에서 클라우드 쉘을 활성화합니다.
.. 필요한 권한이 포함된 YAML 파일을 업로드합니다.
.. 을 사용하여 사용자 지정 역할을 만듭니다 `gcloud iam roles create` 명령.
+
다음 예제에서는 프로젝트 수준에서 "connectorDeployment"라는 역할을 만듭니다.

+
gcloud iam 역할은 connectorDeployment를 생성합니다.- project=MyProject--file=connector-deployment.yAML

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud docs: 사용자 지정 역할 생성 및 관리"^]



. BlueXP에서 Connector를 배포하거나 gcloud를 사용하는 사용자에게 이 사용자 지정 역할을 할당합니다.
+
https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud docs: 단일 역할 부여"^]



.결과
이제 Google Cloud 사용자에게 Connector를 만드는 데 필요한 권한이 있습니다.



== Connector에 대한 권한을 설정합니다

Google Cloud에서 BlueXP가 리소스를 관리하는 데 필요한 권한을 Connector에 제공하려면 서비스 계정이 필요합니다. 이 서비스 계정을 Connector VM에 연결해야 합니다.

.단계
. Google Cloud에서 사용자 지정 역할 생성:
+
.. 의 내용이 포함된 YAML 파일을 생성합니다 link:reference-permissions-gcp.html["Connector에 대한 서비스 계정 권한"].
.. Google Cloud에서 클라우드 쉘을 활성화합니다.
.. 필요한 권한이 포함된 YAML 파일을 업로드합니다.
.. 을 사용하여 사용자 지정 역할을 만듭니다 `gcloud iam roles create` 명령.
+
다음 예제에서는 프로젝트 수준에서 "connector"라는 역할을 만듭니다.

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud docs: 사용자 지정 역할 생성 및 관리"^]



. Google Cloud에서 서비스 계정 생성:
+
.. IAM 및 관리 서비스에서 * 서비스 계정 > 서비스 계정 생성 * 을 선택합니다.
.. 서비스 계정 세부 정보를 입력하고 * 생성 및 계속 * 을 선택합니다.
.. 방금 만든 역할을 선택합니다.
.. 나머지 단계를 완료해서 역할을 만듭니다.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud docs: 서비스 계정 생성"^]





.결과
Connector VM에 대한 서비스 계정이 설정되어 있습니다.



== 프로젝트 간 사용 권한 설정

커넥터가 있는 프로젝트와 다른 프로젝트에 Cloud Volumes ONTAP 시스템을 배포하려는 경우 해당 프로젝트에 액세스할 수 있는 Connector의 서비스 계정을 제공해야 합니다.

예를 들어, 커넥터가 프로젝트 1에 있고 프로젝트 2에서 Cloud Volumes ONTAP 시스템을 만들려는 경우를 가정해 보겠습니다. 프로젝트 2에서 서비스 계정에 대한 액세스 권한을 부여해야 합니다.

.단계
. Google Cloud 콘솔에서 IAM 서비스로 이동하여 Cloud Volumes ONTAP 시스템을 생성할 프로젝트를 선택합니다.
. IAM * 페이지에서 * 액세스 권한 부여 * 를 선택하고 필요한 세부 정보를 제공합니다.
+
** Connector의 서비스 계정의 이메일을 입력합니다.
** Connector의 사용자 정의 역할을 선택합니다.
** 저장 * 을 선택합니다.




자세한 내용은 을 참조하십시오 https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Google Cloud 설명서"^]



== 공유 VPC 권한 설정

공유 VPC를 사용하여 리소스를 서비스 프로젝트에 배포하는 경우 사용 권한을 준비해야 합니다.

이 표는 참조용이며 IAM 구성이 완료되면 사용 권한 테이블이 환경에 반영되어야 합니다.

[cols="10,10,10,20,20,30"]
|===
| 아이덴티티 | 창조자 | 에서 호스팅됩니다 | 서비스 프로젝트 권한 | 호스트 프로젝트 권한 | 목적 


| Connector를 배포하기 위한 Google 계정 | 맞춤형 | 서비스 프로젝트  a| 
link:task-set-up-permissions-google.html#set-up-permissions-to-create-the-connector-from-bluexp-or-gcloud["커넥터 배치 정책"]
 a| 
compute.networkUser
| 서비스 프로젝트에 Connector 배포 


| 커넥터 서비스 계정 | 맞춤형 | 서비스 프로젝트  a| 
link:reference-permissions-gcp.html["커넥터 서비스 계정 정책"]
 a| 
* compute.networkUser
* 배포관리자.편집기

| 서비스 프로젝트에서 Cloud Volumes ONTAP 및 서비스를 배포 및 유지 관리합니다 


| Cloud Volumes ONTAP 서비스 계정입니다 | 맞춤형 | 서비스 프로젝트  a| 
* storage.admin을 선택합니다
* 회원: BlueXP 서비스 계정(serviceAccount.user)

| 해당 없음 | (선택 사항) 데이터 계층화 및 BlueXP 백업 및 복구 


| Google API 서비스 에이전트입니다 | Google 클라우드 | 서비스 프로젝트  a| 
(기본값) 편집기
 a| 
compute.networkUser
| 배포를 대신하여 Google Cloud API와 상호 작용합니다. BlueXP에서 공유 네트워크를 사용할 수 있습니다. 


| Google Compute Engine 기본 서비스 계정입니다 | Google 클라우드 | 서비스 프로젝트  a| 
(기본값) 편집기
 a| 
compute.networkUser
| 배포를 대신하여 Google Cloud 인스턴스 및 컴퓨팅 인프라를 배포합니다. BlueXP에서 공유 네트워크를 사용할 수 있습니다. 
|===
참고:

. 배포관리자 .editor는 배포에 방화벽 규칙을 전달하지 않고 BlueXP에서 사용자를 위해 방화벽 규칙을 만들도록 선택한 경우에만 호스트 프로젝트에 필요합니다. BlueXP는 호스트 프로젝트에 VPC0 방화벽 규칙이 지정되지 않은 경우 이를 포함하는 배포를 생성합니다.
. Firewall.create 및 firewall.delete 은 배포에 방화벽 규칙을 전달하지 않고 BlueXP에서 사용자를 위해 방화벽 규칙을 만들도록 선택한 경우에만 필요합니다. 이러한 권한은 BlueXP 계정 .YAML 파일에 있습니다. 공유 VPC를 사용하여 HA 쌍을 구축하는 경우 이러한 사용 권한을 사용하여 VPC1, 2 및 3에 대한 방화벽 규칙을 생성합니다. 다른 모든 배포의 경우 이러한 사용 권한을 사용하여 VPC0에 대한 규칙을 만들 수도 있습니다.
. 데이터 계층화의 경우 계층화 서비스 계정은 프로젝트 수준뿐만 아니라 서비스 계정에서 serviceAccount.user 역할을 가져야 합니다. 현재 프로젝트 수준에서 serviceAccount.user 를 할당하는 경우 getIAMPolicy를 사용하여 서비스 계정을 쿼리할 때 사용 권한이 표시되지 않습니다.

