---
sidebar: sidebar 
permalink: task-set-up-networking-on-prem.html 
keywords: networking, on prem networking, endpoints, urls, ports, ip address, proxy, proxy server, connections 
summary: Connector가 하이브리드 클라우드 환경 내의 리소스 및 프로세스를 관리할 수 있도록 네트워킹을 설정합니다. 예를 들어 대상 네트워크에 대한 연결을 사용할 수 있고 아웃바운드 인터넷 액세스를 사용할 수 있는지 확인해야 합니다. 
---
= 사내 네트워킹을 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Connector가 하이브리드 클라우드 환경 내의 리소스 및 프로세스를 관리할 수 있도록 네트워킹을 설정합니다. 예를 들어 대상 네트워크에 대한 연결을 사용할 수 있고 아웃바운드 인터넷 액세스를 사용할 수 있는지 확인해야 합니다.



== 대상 네트워크에 대한 연결

Connector를 사용하려면 만들고 있는 작업 환경 유형과 활성화할 서비스에 대한 네트워크 연결이 필요합니다.

예를 들어 클라우드에서 Cloud Volumes ONTAP를 실행하려면 회사 네트워크에서 Cloud Volumes ONTAP를 시작할 가상 네트워크로의 VPN 연결을 설정해야 합니다.



== 아웃바운드 인터넷 액세스

커넥터를 배포하는 네트워크 위치에 아웃바운드 인터넷 연결이 있어야 합니다.



=== 수동 설치 중에 연결된 끝점입니다

자체 Linux 호스트에 커넥터를 수동으로 설치할 경우 Connector 설치 과정에서 다음 URL에 액세스해야 합니다.

* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://cloudmanagerinfraprod.azurecr.io
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net


설치 중에 호스트가 운영 체제 패키지를 업데이트하려고 할 수 있습니다. 호스트는 이러한 OS 패키지의 서로 다른 미러링 사이트에 연결할 수 있습니다.



=== 커넥터에서 접촉된 끝점

Connector는 일상적인 운영을 위해 퍼블릭 클라우드 환경 내의 리소스 및 프로세스를 관리하려면 다음 엔드포인트에 연결하는 아웃바운드 인터넷 액세스가 필요합니다.

[cols="2*"]
|===
| 엔드포인트 | 목적 


 a| 
AWS 서비스(amazonaws.com):

* CloudFormation 을 참조하십시오
* EC2(탄력적인 컴퓨팅 클라우드)
* IAM(Identity and Access Management)
* 키 관리 서비스(KMS)
* 보안 토큰 서비스(STS)
* S3(Simple Storage Service)

| 를 사용하여 AWS에서 리소스를 관리합니다. 정확한 끝점은 Connector를 배포하는 영역에 따라 다릅니다. https://docs.aws.amazon.com/general/latest/gr/rande.html["자세한 내용은 AWS 설명서를 참조하십시오"^] 


| \https://management.azure.com
\https://login.microsoftonline.com | Azure 공공 지역의 리소스를 관리합니다. 


| \https://management.chinacloudapi.cn
\https://login.chinacloudapi.cn | Azure 중국 지역의 리소스를 관리합니다. 


| \https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects | Google Cloud에서 리소스를 관리합니다. 


| \https://support.netapp.com | 라이센스 정보를 얻고 AutoSupport 메시지를 NetApp 지원 팀에 전송합니다. 


 a| 
\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com
 a| 
BlueXP 내에서 SaaS 기능 및 서비스를 제공합니다.


NOTE: 커넥터가 현재 "cloudmanager.cloud.netapp.com" 에 문의하고 있지만 곧 출시될 릴리스에서 "api.bluexp.netapp.com" 에 연락하기 시작합니다.



| \https://cloudmanagerinfraprod.azurecr.io

\https://*.blob.core.windows.net | Connector 및 해당 Docker 구성 요소를 업그레이드합니다. 
|===
.관련 링크
link:reference-networking-saas-console.html["BlueXP 콘솔에 대한 사용자 액세스를 위한 네트워킹을 준비합니다"]



== 프록시 서버

조직에서 나가는 모든 인터넷 트래픽에 대해 프록시 서버를 배포해야 하는 경우 HTTP 또는 HTTPS 프록시에 대한 다음 정보를 가져옵니다.

* IP 주소입니다
* 자격 증명
* HTTPS 인증서




== 포트

커넥터를 시작하거나 커넥터가 AutoSupport 메시지의 프록시로 사용되지 않는 한 커넥터로 들어오는 트래픽이 없습니다.

* HTTP(80) 및 HTTPS(443)는 드물게 사용되는 로컬 UI에 대한 액세스를 제공합니다.
* SSH(22)는 문제 해결을 위해 호스트에 연결해야 하는 경우에만 필요합니다.
* 아웃바운드 인터넷 연결을 사용할 수 없는 서브넷에 Cloud Volumes ONTAP 시스템을 배포하는 경우 포트 3128을 통한 인바운드 연결이 필요합니다. Cloud Volumes ONTAP 시스템에 AutoSupport 메시지를 보내기 위한 아웃바운드 인터넷 연결이 없는 경우 BlueXP는 자동으로 해당 Cloud Volumes ONTAP 시스템이 커넥터에 포함된 프록시 서버를 사용하도록 구성합니다. 유일한 요구 사항은 커넥터 보안 그룹이 포트 3128을 통한 인바운드 연결을 허용하는지 확인하는 것입니다. Connector를 배포한 후 이 포트를 열어야 합니다.




== IP 주소 제한

172 범위의 IP 주소와 충돌할 수 있습니다. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-limitations.html["이 제한 사항에 대해 자세히 알아보십시오"].
