---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: BlueXP에서 수행한 작업에 따라 ONTAP 자격 증명 및 NetApp Support 사이트 NSS 자격 증명을 BlueXP 사용자 로그인과 연결할 수 있습니다. 연결한 후 BlueXP에서 이러한 자격 증명을 보고 관리할 수 있습니다. 예를 들어 이러한 자격 증명의 암호를 변경하는 경우 BlueXP에서 암호를 업데이트해야 합니다. 
---
= BlueXP 로그인과 관련된 자격 증명을 관리합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP에서 수행한 작업에 따라 ONTAP 자격 증명 및 NSS(NetApp Support 사이트) 자격 증명을 BlueXP 사용자 로그인에 연결할 수 있습니다. 연결한 후 BlueXP에서 이러한 자격 증명을 보고 관리할 수 있습니다. 예를 들어 이러한 자격 증명의 암호를 변경하는 경우 BlueXP에서 암호를 업데이트해야 합니다.



== ONTAP 자격 증명

사용자는 BlueXP에서 ONTAP 클러스터를 검색하려면 ONTAP 관리자 자격 증명이 필요합니다. 그러나 ONTAP 시스템 관리자 액세스는 커넥터 사용 여부에 따라 달라집니다.

.커넥터 없음
사용자가 클러스터의 ONTAP System Manager에 액세스할 때 ONTAP 자격 증명을 입력하라는 메시지가 표시됩니다. 사용자는 이러한 자격 증명을 BlueXP 에 저장하도록 선택할 수 있습니다. 즉, 매번 자격 증명을 입력하라는 메시지가 표시되지 않습니다. 사용자 자격 증명은 해당 사용자에게만 표시되며 사용자 자격 증명 페이지에서 관리할 수 있습니다.

.커넥터 포함
기본적으로 사용자는 ONTAP System Manager에 액세스할 때 ONTAP 자격 증명을 입력하라는 메시지가 표시되지 않습니다. 그러나 조직 관리자 역할을 가진 BlueXP  관리자는 사용자에게 ONTAP 자격 증명을 입력하라는 메시지를 표시하도록 BlueXP 를 구성할 수 있습니다. 이 설정을 사용하는 경우 사용자는 매번 ONTAP 자격 증명을 입력해야 합니다.

link:task-ontap-access-connector.html["자세한 정보."^]



== NSS 자격 증명

BlueXP 로그인과 관련된 NSS 자격 증명을 통해 등록, 케이스 관리 및 Digital Advisor에 액세스할 수 있습니다.

* 지원 > 리소스 * 에 액세스하여 지원을 등록하면 NSS 자격 증명을 BlueXP 로그인에 연결하라는 메시지가 표시됩니다.
+
이렇게 하면 귀하의 조직이나 계정이 지원을 위해 등록되고 지원 자격이 활성화됩니다. 지원을 등록하고 지원 권한을 활성화하려면 BlueXP  조직 또는 계정에서 한 명의 사용자만 NetApp 지원 사이트 계정을 BlueXP  로그인과 연결해야 합니다. 이 작업이 완료되면 * 리소스 * 페이지에 계정이 지원을 위해 등록되었다는 내용이 표시됩니다.

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["지원 등록 방법을 알아보십시오"^]

* 지원 > 케이스 관리 * 에 액세스하면 NSS 자격 증명을 입력하라는 메시지가 표시됩니다(아직 입력하지 않은 경우). 이 페이지에서는 NSS 계정 및 회사와 관련된 지원 사례를 만들고 관리할 수 있습니다.
* BlueXP의 Digital Advisor에 액세스하면 NSS 자격 증명을 입력하여 Digital Advisor에 로그인하라는 메시지가 표시됩니다.


BlueXP 로그인과 관련된 NSS 계정은 다음과 같습니다.

* 계정은 사용자 수준에서 관리되므로 로그인한 다른 사용자가 볼 수 없습니다.
* 사용자당 Digital Advisor 및 지원 케이스 관리와 연결된 NSS 계정은 하나만 있을 수 있습니다.
* NetApp 지원 사이트 계정을 Cloud Volumes ONTAP 작업 환경에 연결하려는 경우 BlueXP  조직에 추가된 NSS 계정 또는 사용자가 속한 계정에서만 선택할 수 있습니다.
+
NSS 계정 수준 자격 증명은 BlueXP 로그인과 연결된 NSS 계정과 다릅니다. NSS 계정 수준 자격 증명을 사용하면 BYOL로 Cloud Volumes ONTAP을 배포하고, PAYGO 시스템을 등록하고, 소프트웨어를 업그레이드할 수 있습니다.

+
link:task-adding-nss-accounts.html["BlueXP  조직 또는 계정에서 NSS 자격 증명을 사용하는 방법에 대해 자세히 알아보십시오"]..





== 사용자 자격 증명을 관리합니다

사용자 이름과 암호를 업데이트하거나 자격 증명을 삭제하여 사용자 자격 증명을 관리합니다.

.단계
. BlueXP 콘솔의 오른쪽 상단에서 설정 아이콘을 선택하고 * 자격 증명 * 을 선택합니다.
. 사용자 자격 증명 * 을 선택합니다.
. 아직 사용자 자격 증명이 없는 경우 * NSS 자격 증명 추가 * 를 선택하여 NetApp Support 사이트 계정을 추가할 수 있습니다.
. 다음 옵션을 작업 메뉴에서 선택하여 기존 자격 증명을 관리하세요.
+
** * 자격 증명 업데이트 *: 계정의 사용자 이름과 암호를 업데이트합니다.
** * 자격 증명 삭제 *: BlueXP 사용자 계정과 연결된 계정을 제거합니다.




.결과
BlueXP가 사용자 자격 증명을 업데이트하면 ONTAP 클러스터, 디지털 어드바이저 또는 사례 관리 페이지에 액세스할 때 변경 사항을 확인할 수 있습니다.
