= 커넥터 3.9.54
:allow-uri-read: 




=== 커넥터 3.9.54

BlueXP 커넥터의 이번 릴리스에는 보안 개선, 버그 수정 및 다음과 같은 새로운 기능이 포함되어 있습니다.

* Cloud Volumes ONTAP 서비스를 지원하는 커넥터에 대한 투명 프록시 지원. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["투명 프록시 구성에 대해 자세히 알아보세요."]
* Google Cloud 환경에 커넥터가 배포된 경우 네트워크 태그를 사용하여 커넥터 트래픽을 라우팅하는 기능입니다.
* CPU 및 RAM 사용량을 포함한 커넥터 상태 모니터링을 위한 추가 제품 내 알림입니다.


현재 3.9.54 릴리스는 표준 모드 및 제한 모드에서 사용할 수 있습니다.



=== BlueXP  ID 및 액세스 관리(IAM)

BlueXP 의 ID 및 액세스 관리 기능은 이제 다음과 같은 기능을 제공합니다.

* 개인 모드에서 IAM을 지원하여 BlueXP 서비스와 애플리케이션에 대한 사용자 액세스와 권한을 관리할 수 있습니다.
* 더 쉬운 탐색, 페더레이션 연결을 구성하기 위한 더 명확한 옵션, 기존 페더레이션에 대한 가시성 향상 등 ID 페더레이션의 관리가 간소화되었습니다.
* BlueXP backup and recovery, BlueXP disaster recovery, 페더레이션 관리에 대한 액세스 역할입니다.




==== 개인 모드에서 IAM 지원

BlueXP 이제 프라이빗 모드에서 IAM을 지원하여 BlueXP 서비스 및 애플리케이션의 사용자 액세스 및 권한을 관리할 수 있습니다. 이 향상된 기능을 통해 프라이빗 모드 고객은 역할 기반 액세스 제어(RBAC)를 활용하여 보안 및 규정 준수를 강화할 수 있습니다.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#iam["BlueXP 의 IAM에 대해 자세히 알아보세요."]



==== ID 연합의 간소화된 관리

BlueXP 이제 ID 페더레이션 관리를 위한 더욱 직관적인 인터페이스를 제공합니다. 더욱 간편한 탐색, 페더레이션 연결 구성 옵션의 명확성, 그리고 기존 페더레이션에 대한 가시성 향상이 포함됩니다.

ID 페더레이션을 통해 단일 로그인(SSO)을 활성화하면 사용자가 회사 자격 증명으로 BlueXP 에 로그인할 수 있습니다. 이를 통해 보안이 강화되고, 비밀번호 사용이 줄어들며, 온보딩이 간소화됩니다.

새로운 관리 기능에 액세스하려면 기존 페더레이션 연결을 새 인터페이스로 가져오라는 메시지가 표시됩니다. 이를 통해 페더레이션 연결을 다시 만들지 않고도 최신 개선 사항을 활용할 수 있습니다. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-federation-import.html["기존 페더레이션 연결을 BlueXP 로 가져오는 방법에 대해 자세히 알아보세요."]

개선된 페더레이션 관리를 통해 다음을 수행할 수 있습니다.

* 여러 개의 검증된 도메인을 페더레이션 연결에 추가하면 동일한 ID 공급자(IdP)를 사용하여 여러 도메인을 사용할 수 있습니다.
* 필요한 경우 페더레이션 연결을 비활성화하거나 삭제하여 사용자 액세스 및 보안을 제어할 수 있습니다.
* IAM 역할을 사용하여 페더레이션 관리에 대한 액세스를 제어합니다.


link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-federation.html["BlueXP 의 ID 페더레이션에 대해 자세히 알아보세요."]



==== BlueXP backup and recovery, BlueXP disaster recovery 및 페더레이션 관리를 위한 새로운 액세스 역할

이제 BlueXP 다음 기능과 데이터 서비스에 대해 IAM 역할을 사용할 수 있도록 지원합니다.

* BlueXP 백업 및 복구
* BlueXP 재해 복구
* 연합


link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["액세스 역할 사용에 대해 자세히 알아보세요."]
