= 커넥터 3.9.50
:allow-uri-read: 




=== 커넥터 3.9.50

이 BlueXP  커넥터 릴리스에는 다음과 같은 기능뿐만 아니라 사소한 보안 개선 사항 및 버그 수정이 포함되어 있습니다.

현재 3.9.50 릴리스는 표준 모드 및 제한 모드에서 사용할 수 있습니다.



=== 커넥터 3.9.49 업데이트



==== BlueXP 에서 커넥터를 사용할 때 ONTAP 시스템 관리자 액세스

BlueXP  관리자(조직 관리자 역할을 가진 사용자)는 ONTAP 시스템 관리자에 액세스하기 위해 사용자에게 ONTAP 자격 증명을 입력하라는 메시지를 표시하도록 BlueXP 를 구성할 수 있습니다. 이 설정을 사용하는 경우 사용자는 ONTAP 자격 증명이 BlueXP 에 저장되지 않으므로 매번 해당 자격 증명을 입력해야 합니다.

이 기능은 커넥터 버전 3.9.49 이상에서 사용할 수 있습니다. link:task-ontap-access-connector.html["자격 증명 설정을 구성하는 방법에 대해 알아봅니다."^]..



=== 커넥터 3.9.48 업데이트



==== 커넥터에 대한 자동 업그레이드 설정을 비활성화할 수 있습니다

커넥터의 자동 업그레이드 기능을 비활성화할 수 있습니다.

표준 모드 또는 제한 모드에서 BlueXP 를 사용하는 경우 BlueXP 는 소프트웨어 업데이트를 얻기 위해 커넥터에 아웃바운드 인터넷 액세스가 있는 경우 커넥터를 자동으로 최신 릴리스로 업그레이드합니다. 커넥터를 업그레이드할 때 수동으로 관리해야 하는 경우 표준 모드 또는 제한된 모드에 대한 자동 업그레이드를 비활성화할 수 있습니다.


NOTE: 이 변경 사항은 항상 커넥터를 직접 업그레이드해야 하는 BlueXP  개인 모드에 영향을 주지 않습니다.

이 기능은 커넥터 버전 3.9.48 이상에서 사용할 수 있습니다.

link:task-upgrade-connector.html["커넥터에 대한 자동 업그레이드를 비활성화하는 방법에 대해 알아봅니다."^]
