= 대상 네트워크에 연결
:allow-uri-read: 


Connector가 공용 클라우드 환경 내에서 리소스 및 프로세스를 관리할 수 있도록 네트워킹을 설정합니다. Connector에 대한 가상 네트워크 및 서브넷을 사용하는 것 외에 다음 요구 사항이 충족되는지 확인해야 합니다.



=== 대상 네트워크에 연결

Connector를 사용하려면 만들고 있는 작업 환경 유형과 활성화할 서비스에 대한 네트워크 연결이 필요합니다.

예를 들어 회사 네트워크에 커넥터를 설치하는 경우 Cloud Volumes ONTAP를 실행하는 가상 네트워크에 대한 VPN 연결을 설정해야 합니다.



=== 아웃바운드 인터넷 액세스

Connector를 사용하려면 공용 클라우드 환경 내의 리소스와 프로세스를 관리하기 위한 아웃바운드 인터넷 액세스가 필요합니다.

[cols="2*"]
|===
| 엔드포인트 | 목적 


| \https://support.netapp.com | 라이센스 정보를 얻고 AutoSupport 메시지를 NetApp 지원 팀에 전송합니다. 


 a| 
\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com
 a| 
BlueXP 내에서 SaaS 기능 및 서비스를 제공합니다.


NOTE: 커넥터가 현재 "cloudmanager.cloud.netapp.com" 에 문의하고 있지만 곧 출시될 릴리스에서 "api.bluexp.netapp.com" 에 연락하기 시작합니다.



| \https://cloudmanagerinfraprod.azurecr.io

\https://*.blob.core.windows.net | Connector 및 해당 Docker 구성 요소를 업그레이드합니다. 


 a| 
AWS 서비스(amazonaws.com):

* CloudFormation 을 참조하십시오
* EC2(탄력적인 컴퓨팅 클라우드)
* 키 관리 서비스(KMS)
* 보안 토큰 서비스(STS)
* S3(Simple Storage Service)

| 를 사용하여 AWS에서 리소스를 관리합니다. 정확한 끝점은 Connector를 배포하는 영역에 따라 다릅니다. https://docs.aws.amazon.com/general/latest/gr/rande.html["자세한 내용은 AWS 설명서를 참조하십시오"^] 


| \https://management.azure.com
\https://login.microsoftonline.com
\https://blob.core.windows.net
\https://core.windows.net | Azure 공공 지역의 리소스를 관리합니다. 


| \https://management.usgovcloudapi.net
\https://login.microsoftonline.us
\https://blob.core.usgovcloudapi.net
\https://core.usgovcloudapi.net | Azure Government 지역의 리소스를 관리합니다. 


| \https://management.azure.microsoft.scloud
\https://login.microsoftonline.microsoft.scloud
\https://blob.core.microsoft.scloud
\https://core.microsoft.scloud | Azure IL6 영역의 리소스를 관리합니다. 


| \https://management.chinacloudapi.cn
\https://login.chinacloudapi.cn
\https://blob.core.chinacloudapi.cn
\https://core.chinacloudapi.cn | Azure 중국 지역의 리소스를 관리합니다. 


| \https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects | Google Cloud에서 리소스를 관리합니다. 
|===


=== 프록시 서버

조직에서 나가는 모든 인터넷 트래픽에 대해 프록시 서버를 배포해야 하는 경우 HTTP 또는 HTTPS 프록시에 대한 다음 정보를 가져옵니다.

* IP 주소입니다
* 자격 증명
* HTTPS 인증서




=== 보안 그룹

커넥터를 시작하거나 커넥터가 AutoSupport 메시지의 프록시로 사용되지 않는 한 커넥터로 들어오는 트래픽이 없습니다. HTTP 및 HTTPS는 에 대한 액세스를 제공합니다 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#the-local-user-interface["로컬 UI"]이는 드문 경우지만 사용할 수 있습니다. SSH는 문제 해결을 위해 호스트에 연결해야 하는 경우에만 필요합니다.



=== IP 주소 제한

172 범위의 IP 주소와 충돌할 수 있습니다. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-limitations.html["이 제한 사항에 대해 자세히 알아보십시오"].
