= 
:allow-uri-read: 


공유 VPC를 사용하여 리소스를 서비스 프로젝트에 배포하는 경우 사용 권한을 준비해야 합니다.

이 표는 참조용이며 IAM 구성이 완료되면 사용 권한 테이블이 환경에 반영되어야 합니다.

.공유 VPC 권한을 봅니다
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| 아이덴티티 | 창조자 | 에서 호스팅됩니다 | 서비스 프로젝트 권한 | 호스트 프로젝트 권한 | 목적 


| Connector를 배포하기 위한 Google 계정 | 맞춤형 | 서비스 프로젝트  a| 
link:task-install-connector-google-bluexp-gcloud.html#step-2-set-up-permissions-to-create-the-connector["커넥터 배치 정책"]
 a| 
compute.networkUser
| 서비스 프로젝트에 Connector 배포 


| 커넥터 서비스 계정 | 맞춤형 | 서비스 프로젝트  a| 
link:reference-permissions-gcp.html["커넥터 서비스 계정 정책"]
| compute.networkUser

배포관리자.편집기 | 서비스 프로젝트에서 Cloud Volumes ONTAP 및 서비스를 배포 및 유지 관리합니다 


| Cloud Volumes ONTAP 서비스 계정입니다 | 맞춤형 | 서비스 프로젝트 | storage.admin을 선택합니다

회원: BlueXP 서비스 계정(serviceAccount.user) | 해당 없음 | (선택 사항) 데이터 계층화 및 BlueXP 백업 및 복구 


| Google API 서비스 에이전트입니다 | Google 클라우드 | 서비스 프로젝트  a| 
(기본값) 편집기
 a| 
compute.networkUser
| 배포를 대신하여 Google Cloud API와 상호 작용합니다. BlueXP에서 공유 네트워크를 사용할 수 있습니다. 


| Google Compute Engine 기본 서비스 계정입니다 | Google 클라우드 | 서비스 프로젝트  a| 
(기본값) 편집기
 a| 
compute.networkUser
| 배포를 대신하여 Google Cloud 인스턴스 및 컴퓨팅 인프라를 배포합니다. BlueXP에서 공유 네트워크를 사용할 수 있습니다. 
|===
참고:

. 배포관리자 .editor는 배포에 방화벽 규칙을 전달하지 않고 BlueXP에서 사용자를 위해 방화벽 규칙을 만들도록 선택한 경우에만 호스트 프로젝트에 필요합니다. BlueXP는 호스트 프로젝트에 VPC0 방화벽 규칙이 지정되지 않은 경우 이를 포함하는 배포를 생성합니다.
. Firewall.create 및 firewall.delete 은 배포에 방화벽 규칙을 전달하지 않고 BlueXP에서 사용자를 위해 방화벽 규칙을 만들도록 선택한 경우에만 필요합니다. 이러한 권한은 BlueXP 계정 .YAML 파일에 있습니다. 공유 VPC를 사용하여 HA 쌍을 구축하는 경우 이러한 사용 권한을 사용하여 VPC1, 2 및 3에 대한 방화벽 규칙을 생성합니다. 다른 모든 배포의 경우 이러한 사용 권한을 사용하여 VPC0에 대한 규칙을 만들 수도 있습니다.
. 데이터 계층화의 경우 계층화 서비스 계정은 프로젝트 수준뿐만 아니라 서비스 계정에서 serviceAccount.user 역할을 가져야 합니다. 현재 프로젝트 수준에서 serviceAccount.user 를 할당하는 경우 getIAMPolicy를 사용하여 서비스 계정을 쿼리할 때 사용 권한이 표시되지 않습니다.


====