= 
:allow-uri-read: 


.시작하기 전에
다음과 같은 항목이 있어야 합니다.

* 커넥터를 설치할 수 있는 루트 권한
* Connector의 인터넷 액세스에 프록시가 필요한 경우 프록시 서버에 대한 세부 정보입니다.
+
설치 후 프록시 서버를 구성할 수 있지만 이렇게 하려면 커넥터를 다시 시작해야 합니다.

+
BlueXP는 투명한 프록시 서버를 지원하지 않습니다.

* 프록시 서버가 HTTPS를 사용하거나 프록시가 가로채기 프록시인 경우 CA 서명 인증서입니다.


.이 작업에 대해
NetApp Support 사이트에서 제공되는 설치 프로그램은 이전 버전일 수 있습니다. 새 버전이 있는 경우 설치 후 커넥터가 자동으로 업데이트됩니다.

.단계
. _http_proxy_or_https_proxy_system 변수가 호스트에 설정되어 있으면 이를 제거합니다.
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
이러한 시스템 변수를 제거하지 않으면 설치가 실패합니다.

. 에서 Connector 소프트웨어를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp Support 사이트"^]를 선택한 다음 Linux 호스트에 복사합니다.
+
네트워크 또는 클라우드에서 사용하도록 고안된 "온라인" 커넥터 설치 프로그램을 다운로드해야 합니다. Connector에 대해 별도의 "오프라인" 설치 프로그램을 사용할 수 있지만 전용 모드 배포에서만 지원됩니다.

. 스크립트를 실행할 권한을 할당합니다.
+
[source, cli]
----
chmod +x BlueXP-Connector-Cloud-<version>
----
+
여기서 <version>는 다운로드한 커넥터 버전입니다.

. 설치 스크립트를 실행합니다.
+
[source, cli]
----
 ./BlueXP-Connector-Cloud-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
proxy 및 -- cacert 매개 변수는 선택 사항입니다. 프록시 서버가 있는 경우 그림과 같이 매개 변수를 입력해야 합니다. 설치 프로그램에서 프록시에 대한 정보를 제공하라는 메시지를 표시하지 않습니다.

+
다음은 두 가지 선택적 매개 변수를 사용하는 명령의 예입니다.

+
[source, cli]
----
 ./BlueXP-Connector-Cloud-v3.9.40--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
-- 프록시는 다음 형식 중 하나를 사용하여 커넥터가 HTTP 또는 HTTPS 프록시 서버를 사용하도록 구성합니다.

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
다음 사항에 유의하십시오.

+
*** 사용자는 로컬 사용자 또는 도메인 사용자일 수 있습니다.
*** 도메인 사용자의 경우 위에 표시된 \ 에 대해 ASCII 코드를 사용해야 합니다.
*** BlueXP는 @ 문자가 포함된 사용자 이름 또는 암호를 지원하지 않습니다.
*** 암호에 다음과 같은 특수 문자가 포함된 경우 백슬래시(& or!)를 사용하여 해당 특수 문자를 이스케이프해야 합니다.
+
예를 들면 다음과 같습니다.

+
\http://bxpproxyuser:netapp1\!@address:3128





+
cacert는 Connector와 프록시 서버 간의 HTTPS 액세스에 사용할 CA 서명 인증서를 지정합니다. 이 매개 변수는 HTTPS 프록시 서버를 지정하거나 프록시가 가로채기 프록시인 경우에만 필요합니다.



. 설치가 완료될 때까지 기다립니다.
+
프록시 서버를 지정한 경우 설치가 끝나면 커넥터 서비스(occm)가 두 번 다시 시작됩니다.

. Connector 가상 머신에 연결된 호스트에서 웹 브라우저를 열고 다음 URL을 입력합니다.
+
https://_ipaddress_[]

. 로그인한 후 Connector를 설정합니다.
+
.. Connector와 연결할 BlueXP 계정을 지정합니다.
.. 시스템의 이름을 입력합니다.
.. 에서 * 보안 환경에서 실행 중입니까? * 제한된 모드를 사용하지 않도록 설정합니다.
+
이 단계에서는 표준 모드에서 BlueXP를 사용하는 방법을 설명하므로 제한된 모드를 사용하지 않도록 설정해야 합니다. 보안 환경이 있고 BlueXP 백엔드 서비스에서 이 계정의 연결을 끊으려면 제한된 모드만 활성화해야 합니다. 그렇다면 link:task-quick-start-restricted-mode.html["제한된 모드에서 BlueXP를 시작하려면 다음 단계를 따르십시오"].

.. Let's start * 를 선택합니다.




.결과
이제 커넥터가 설치되어 BlueXP 계정으로 설정됩니다.
