= 
:allow-uri-read: 


운영 체제에 따라 Connector를 설치하기 전에 Podman 또는 Docker Engine이 필요합니다.

* Red Hat Enterprise Linux 8 및 9에는 Podman이 필요합니다.
* Ubuntu에는 Docker 엔진이 필요합니다.


.단계
[role="tabbed-block"]
====
.팟맨
--
지원되는 버전의 Podman을 설치합니다. <<podman-versions,BlueXP 가 지원하는 Podman 버전을 봅니다>>..

.단계
. podman-docker 패키지가 호스트에 설치되어 있는 경우 이를 제거합니다.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Podman을 설치합니다.
+
Podman은 공식 Red Hat Enterprise Linux 저장소에서 구할 수 있습니다.

+
Red Hat Enterprise Linux 9의 경우:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
여기서 <version>는 설치 중인 Podman의 지원되는 버전입니다. <<podman-versions,BlueXP 가 지원하는 Podman 버전을 봅니다>>..

+
Red Hat Enterprise Linux 8의 경우:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
여기서 <version>는 설치 중인 Podman의 지원되는 버전입니다. <<podman-versions,BlueXP 가 지원하는 Podman 버전을 봅니다>>..

. podman.socket 서비스를 활성화하고 시작합니다.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. python3 을 장착합니다.
+
[source, cli]
----
sudo dnf install python3
----
. EPEL 리포지토리 패키지를 시스템에 사용할 수 없는 경우 설치합니다.
+
EPEL(Extra Packages for Enterprise Linux) 리포지토리에서 podman-composition을 사용할 수 있기 때문에 이 단계가 필요합니다.

+
Red Hat Enterprise Linux 9의 경우:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Red Hat Enterprise Linux 8의 경우:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. podman-comp 패키지 1.0.6을 설치합니다.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: 를 사용합니다 `dnf install` 명령은 PATH 환경 변수에 podman-composition을 추가하기 위한 요구 사항을 충족합니다. 설치 명령은 podman-composition을 이미 에 포함되어 있는 /usr/bin에 추가합니다 `secure_path` 호스트 옵션.



--
.Docker 엔진
--
지원되는 버전의 Docker Engine을 설치합니다. <<podman-versions,BlueXP 가 지원하는 Docker Engine 버전을 확인합니다>>..

.단계
. Docker Engine을 설치합니다.
+
https://docs.docker.com/engine/install/["Docker의 설치 지침을 봅니다"^]

+
특정 버전의 Docker Engine을 설치하려면 다음 단계를 따르십시오. 최신 버전을 설치하면 BlueXP가 지원하지 않는 Docker 버전이 설치됩니다.

. Docker가 활성화되어 실행 중인지 확인합니다.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====